id = "1373237869069598810"
name = "(1) Raiden Shogun [Kirigame_5]"
archived = true
locked = false
createdAt = "2025-05-17T09:57:01.512Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1373237869069598810"
author = "korieuko"
content = "https://rule34video.com/video/3795869/1-raiden-shogun-kirigame-5/"
createdAt = "2025-05-17T09:57:01.512Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
