id = "1411580713672642650"
name = "[FULL] - The 'Eternal' Sparring Session - Raiden Shogun"
archived = true
locked = false
createdAt = "2025-08-31T05:17:48.041Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1411580713672642650"
author = "korieuko"
content = "https://rule34video.com/video/3993753/full-the-eternal-sparring-session-raiden-shogun/"
createdAt = "2025-08-31T05:17:48.041Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
