id = "1376406277307105382"
name = "[kusotaro] Raiden Tied Up"
archived = true
locked = false
createdAt = "2025-05-26T03:47:08.902Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376406277307105382"
author = "korieuko"
content = "https://rule34video.com/video/3814249/kusotaro-raiden-tied-up/"
createdAt = "2025-05-26T03:47:08.902Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3814000/3814249/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3814249/kusotaro-raiden-tied-up/"
title = "[kusotaro] Raiden Tied Up"
image = "https://rule34video.com/contents/videos_screenshots/3814000/3814249/preview.jpg"
site = "rule34video.com"
desc = ""
