id = "1393202920497090560"
name = "(nirakust) Raiden Shogun Backshots"
archived = true
locked = false
createdAt = "2025-07-11T12:11:00.705Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1393202920497090560"
author = "korieuko"
content = "https://rule34video.com/video/3926153/nirakust-raiden-shogun-backshots/"
createdAt = "2025-07-11T12:11:00.705Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3926000/3926153/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3926153/nirakust-raiden-shogun-backshots/"
title = "(nirakust) Raiden Shogun Backshots"
image = "https://rule34video.com/contents/videos_screenshots/3926000/3926153/preview.jpg"
site = "rule34video.com"
desc = "Artist: nirakust\nTwitter: https://x.com/nirakust_\nhttps://x.com/nirakust_/status/1943309243333120266"
