id = "1413180390620921916"
name = "【PastaPaprika】2025.08.31 49 AisaBathhouse Anim_4K"
archived = true
locked = false
createdAt = "2025-09-04T15:14:20.746Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413180390620921916"
author = "korieuko"
content = "https://rule34video.com/video/4007857/pastapaprika-2025-08-31-49-aisabathhouse-anim-4k/"
createdAt = "2025-09-04T15:14:20.746Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4007000/4007857/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4007857/pastapaprika-2025-08-31-49-aisabathhouse-anim-4k/"
title = "【PastaPaprika】2025.08.31 49 AisaBathhouse Anim_4K"
image = "https://rule34video.com/contents/videos_screenshots/4007000/4007857/preview.jpg"
site = "rule34video.com"
desc = "49 AisaBathhouse Anim_4K.mp4"
