id = "1411549972985548932"
name = "[Tir_Al] Raiden Ei's Punishment"
archived = true
locked = false
createdAt = "2025-08-31T03:15:38.890Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1411549972985548932"
author = "korieuko"
content = "https://rule34video.com/video/3125741/tir-al-raiden-ei-s-punishment/"
createdAt = "2025-08-31T03:15:38.890Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3125000/3125741/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3125741/tir-al-raiden-ei-s-punishment/"
title = "[Tir_Al] Raiden Ei's Punishment"
image = "https://rule34video.com/contents/videos_screenshots/3125000/3125741/preview.jpg"
site = "rule34video.com"
desc = ""
