id = "1314854153310437377"
name = "[YESUI] Raiden Ei／雷電影 4K60FPS"
archived = true
locked = false
createdAt = "2024-12-07T07:20:58.958Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314854153310437377"
author = "korieuko"
content = "https://avbebe.com/archives/243824"
createdAt = "2024-12-07T07:20:58.958Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/08/Raiden-Ei%EF%BC%8F%E9%9B%B7%E9%9B%BB%E5%BD%B1-4K60FPS.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/243824"
title = "[YESUI] Raiden Ei／雷電影 4K60FPS"
image = "https://avbebe.com/wp-content/uploads/2024/08/Raiden-Ei%EF%BC%8F%E9%9B%B7%E9%9B%BB%E5%BD%B1-4K60FPS.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish (下"
