id = "1314861225661698048"
name = "[YESUI]【原神】雷電將軍(黑絲襪OL)"
archived = true
locked = false
createdAt = "2024-12-07T07:49:05.138Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314861225661698048"
author = "korieuko"
content = "https://avbebe.com/archives/186323"
createdAt = "2024-12-07T07:49:05.138Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2023/11/YESUI%E3%80%90%E5%8E%9F%E7%A5%9E%E3%80%91%E9%9B%B7%E9%9B%BB%E5%B0%87%E8%BB%8D%E9%BB%91%E7%B5%B2%E8%A5%AA.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/186323"
title = "[YESUI]【原神】雷電將軍(黑絲襪OL)"
image = "https://avbebe.com/wp-content/uploads/2023/11/YESUI%E3%80%90%E5%8E%9F%E7%A5%9E%E3%80%91%E9%9B%B7%E9%9B%BB%E5%B0%87%E8%BB%8D%E9%BB%91%E7%B5%B2%E8%A5%AA.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe影片 SERVER #2 A"
