id = "1314865466115883059"
name = "[YESUI] Raiden Ei／雷电影 Animation"
archived = true
locked = false
createdAt = "2024-12-07T08:05:56.141Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314865466115883059"
author = "korieuko"
content = "https://avbebe.com/archives/192050"
createdAt = "2024-12-07T08:05:56.141Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2023/12/%E3%80%8A%E5%8E%9F%E7%A5%9E%E3%80%8B%E9%9B%B7%E9%9B%BB%E5%B0%87%E8%BB%8D-1.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/192050"
title = "[YESUI] Raiden Ei／雷电影 Animation"
image = "https://avbebe.com/wp-content/uploads/2023/12/%E3%80%8A%E5%8E%9F%E7%A5%9E%E3%80%8B%E9%9B%B7%E9%9B%BB%E5%B0%87%E8%BB%8D-1.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "虎克 虎克 《原神》雷電將軍 《原神》雷"
