id = "1413830663760646206"
name = "Raiden Shogun [kirigame_5]"
archived = true
locked = false
createdAt = "2025-09-06T10:18:17.944Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413830663760646206"
author = "korieuko"
content = "https://rule34video.com/video/3527202/raiden-shogun-kirigame-52/"
createdAt = "2025-09-06T10:18:17.944Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
