id = "1411550122860609678"
name = "Raiden ape"
archived = true
locked = false
createdAt = "2025-08-31T03:16:14.623Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1411550122860609678"
author = "korieuko"
content = "https://rule34video.com/video/3075178/raiden-rape/"
createdAt = "2025-08-31T03:16:14.623Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3075000/3075178/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3075178/raiden-rape/"
title = "Raiden Rape"
image = "https://rule34video.com/contents/videos_screenshots/3075000/3075178/preview.jpg"
site = "rule34video.com"
desc = "https://twitter.com/Tir_Al_/status/1525459142046908417?s=20&t=M5YNW8OsW_aeLh23ZdehMg"

[[messages]]
id = "1411580763702558802"
author = "korieuko"
content = "good"
createdAt = "2025-08-31T05:17:59.969Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
