id = "1376406368193347656"
name = "Raiden Ei cowgirl [VikLodn]"
archived = true
locked = false
createdAt = "2025-05-26T03:47:30.571Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376406368193347656"
author = "korieuko"
content = "https://rule34video.com/video/3802477/raiden-ei-cowgirl-viklodn/"
createdAt = "2025-05-26T03:47:30.571Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
