id = "1413830309375508480"
name = "Raiden Shogun (Clothed - Compiled) [Kirigame_5]"
archived = true
locked = false
createdAt = "2025-09-06T10:16:53.452Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413830309375508480"
author = "korieuko"
content = "https://rule34video.com/video/3958463/raiden-shogun-clothed-compiled-kirigame-5/"
createdAt = "2025-09-06T10:16:53.452Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3958000/3958463/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3958463/raiden-shogun-clothed-compiled-kirigame-5/"
title = "Raiden Shogun (Clothed - Compiled) [Kirigame_5]"
image = "https://rule34video.com/contents/videos_screenshots/3958000/3958463/preview.jpg"
site = "rule34video.com"
desc = ""
