id = "1476248351099064461"
name = "Raiden Ei legs up [lazyrice3d]"
archived = false
locked = false
createdAt = "2026-02-25T16:03:54.270Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1476248351099064461"
author = "korieuko"
content = "https://rule34video.com/video/4259242/raiden-ei-legs-up-lazyrice3d/"
createdAt = "2026-02-25T16:03:54.270Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4259000/4259242/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4259242/raiden-ei-legs-up-lazyrice3d/"
title = "Raiden Ei legs up [lazyrice3d]"
image = "https://rule34video.com/contents/videos_screenshots/4259000/4259242/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/lazyrice3d/status/2019972476902715523"
