id = "1389230019062005770"
name = "Raiden Shogun [Lazyrice3D]"
archived = true
locked = false
createdAt = "2025-06-30T13:04:07.190Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389230019062005770"
author = "korieuko"
content = "https://rule34video.com/video/3904861/raiden-shogun-lazyrice3d/"
createdAt = "2025-06-30T13:04:07.190Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3904000/3904861/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3904861/raiden-shogun-lazyrice3d/"
title = "Raiden Shogun [Lazyrice3D]"
image = "https://rule34video.com/contents/videos_screenshots/3904000/3904861/preview.jpg"
site = "rule34video.com"
desc = ""
