id = "1416313678839418940"
name = "Raiden's Feast [Bubukuin]"
archived = true
locked = false
createdAt = "2025-09-13T06:44:54.871Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1416313678839418940"
author = "korieuko"
content = "https://rule34video.com/video/4024809/raiden-s-feast-bubukuin/"
createdAt = "2025-09-13T06:44:54.871Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4024000/4024809/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4024809/raiden-s-feast-bubukuin/"
title = "Raiden's Feast [Bubukuin]"
image = "https://rule34video.com/contents/videos_screenshots/4024000/4024809/preview.jpg"
site = "rule34video.com"
desc = "Support him:\nhttps://x.com/bubukuin\nhttps://www.patreon.com/cw/bubukuin"
