id = "1315179914722410526"
name = "Rinjo_18] Raiden｜Full"
archived = true
locked = false
createdAt = "2024-12-08T04:55:26.531Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1315179914722410526"
author = "korieuko"
content = "https://avbebe.com/archives/214239"
createdAt = "2024-12-08T04:55:26.531Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
