id = "1314850708746403850"
name = "Genshin Impact[NSFW]"
guildId = "1314839006717935696"
guildName = "Invrs ✦ NSFW"
backedUpAt = "2026-03-08T13:31:42.106Z"
contents = ["forum: forum-citlali", "forum: forum-navia", "forum: forum-raiden-ei", "forum: forum-ayaka", "forum: forum-ganyu", "forum: forum-yae-miko", "forum: forum-yelan", "forum: forum-arlecchino", "forum: forum-shenhe", "forum: forum-columbina", "forum: forum-faruzuan", "forum: forum-furina", "forum: forum-mavuika", "forum: forum-eula", "forum: forum-xianyun", "forum: forum-skirk", "forum: forum-jean", "forum: forum-escoffier", "forum: forum-keqing", "forum: forum-clorinde", "forum: forum-mualani", "forum: forum-ningguang", "forum: forum-xilonen", "forum: forum-nilou", "forum: forum-varesa", "forum: forum-lauma", "forum: forum-sandrone", "forum: forum-nefer", "forum: forum-zibai"]

[stats]
totalForums = 29
totalChannels = 0
totalThreads = 313
totalMessages = 333
