id = "1462033922786463826"
name = "(4K) Chisa (Full) [Sileter]"
archived = true
locked = false
createdAt = "2026-01-17T10:40:50.469Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1462033922786463826"
author = "korieuko"
content = "https://rule34video.com/video/4201701/4k-chisa-full-sileter/"
createdAt = "2026-01-17T10:40:50.469Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4201000/4201701/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4201701/4k-chisa-full-sileter/"
title = "(4K) Chisa (Full) [Sileter]"
image = "https://rule34video.com/contents/videos_screenshots/4201000/4201701/preview.jpg"
site = "rule34video.com"
desc = ""
