id = "1462031173571051522"
name = "Cartethyia cums inside Chisa | Wuthering Waves"
archived = true
locked = false
createdAt = "2026-01-17T10:29:55.005Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1462031173571051522"
author = "korieuko"
content = "https://rule34video.com/video/4196077/cartethyia-cums-inside-chisa-wuthering-waves/"
createdAt = "2026-01-17T10:29:55.005Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4196000/4196077/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4196077/cartethyia-cums-inside-chisa-wuthering-waves/"
title = "Cartethyia cums inside Chisa | Wuthering Waves"
image = "https://rule34video.com/contents/videos_screenshots/4196000/4196077/preview.jpg"
site = "rule34video.com"
desc = "Enjoy the full animation!\nYou can see more animations on my patreon\npatreon.com/SuChie"
