id = "1468223165695000627"
name = "Chisa's Worst Place to Land [720p/Subbed]"
archived = true
locked = false
createdAt = "2026-02-03T12:34:40.969Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1468223165695000627"
author = "korieuko"
content = "https://rule34video.com/video/4227782/chisa-s-worst-place-to-land-720p-subbed2/"
createdAt = "2026-02-03T12:34:40.969Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4227000/4227782/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4227782/chisa-s-worst-place-to-land-720p-subbed2/"
title = "Chisa's Worst Place to Land [720p/Subbed]"
image = "https://rule34video.com/contents/videos_screenshots/4227000/4227782/preview.jpg"
site = "rule34video.com"
desc = "Chisa from Tir_AL with subtitles, for ambience enjoyers\n\nFor 4k and preggers version, go support the artist:\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"

[[messages]]
id = "1468224466944528445"
author = "korieuko"
content = "peaker"
createdAt = "2026-02-03T12:39:51.211Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
