id = "1472259970304311509"
name = "Chisa [Croove]"
archived = false
locked = false
createdAt = "2026-02-14T15:55:30.188Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1472259970304311509"
author = "korieuko"
content = "https://rule34video.com/video/4234570/chisa-croove/"
createdAt = "2026-02-14T15:55:30.188Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4234000/4234570/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4234570/chisa-croove/"
title = "Chisa [Croove]"
image = "https://rule34video.com/contents/videos_screenshots/4234000/4234570/preview.jpg"
site = "rule34video.com"
desc = ""
