id = "1455484891239288893"
name = "Chisa [Akt]"
archived = true
locked = false
createdAt = "2025-12-30T08:57:19.673Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1455484891239288893"
author = "korieuko"
content = "https://rule34video.com/video/4163142/chisa-akt/"
createdAt = "2025-12-30T08:57:19.673Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4163000/4163142/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4163142/chisa-akt/"
title = "Chisa [Akt]"
image = "https://rule34video.com/contents/videos_screenshots/4163000/4163142/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://akt.fanbox.cc\nhttps://www.patreon.com/c/akt_shop\nhttps://ganknow.com/animationakt"
