id = "1442537590979952760"
name = "RDreamer Chisa FULL"
archived = true
locked = false
createdAt = "2025-11-24T15:29:22.742Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442537590979952760"
author = "korieuko"
content = "https://rule34video.com/video/4118738/rdreamer-chisa-full/"
createdAt = "2025-11-24T15:29:22.742Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4118000/4118738/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4118738/rdreamer-chisa-full/"
title = "RDreamer Chisa FULL"
image = "https://rule34video.com/contents/videos_screenshots/4118000/4118738/preview.jpg"
site = "rule34video.com"
desc = ""
