id = "1455485171565330516"
name = "Romantic sex with Chisa (Clothed)"
archived = true
locked = false
createdAt = "2025-12-30T08:58:26.508Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1455485171565330516"
author = "korieuko"
content = "https://rule34video.com/video/4171011/romantic-sex-with-chisa-clothed/"
createdAt = "2025-12-30T08:58:26.508Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4171000/4171011/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4171011/romantic-sex-with-chisa-clothed/"
title = "Romantic sex with Chisa (Clothed)"
image = "https://rule34video.com/contents/videos_screenshots/4171000/4171011/preview.jpg"
site = "rule34video.com"
desc = ""

[[messages]]
id = "1468223996616114332"
author = "korieuko"
content = "ts so peak"
createdAt = "2026-02-03T12:37:59.076Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
