id = "1468941408537677824"
name = "Wuwa Chisa Unhappy Rover Come Too Quickly (Sound Version) - Lazyrice3D"
archived = true
locked = false
createdAt = "2026-02-05T12:08:43.407Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468941408537677824"
author = "korieuko"
content = "https://rule34video.com/video/4230086/wuwa-chisa-unhappy-rover-come-too-quickly-sound-version-lazyrice3d/"
createdAt = "2026-02-05T12:08:43.407Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4230000/4230086/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4230086/wuwa-chisa-unhappy-rover-come-too-quickly-sound-version-lazyrice3d/"
title = "Wuwa Chisa Unhappy Rover Come Too Quickly (Sound Version) - Lazyrice3D"
image = "https://rule34video.com/contents/videos_screenshots/4230000/4230086/preview.jpg"
site = "rule34video.com"
desc = ""
