id = "1314900735812436028"
name = "リル] 24.10 JaneDoe"
archived = true
locked = false
createdAt = "2024-12-07T10:26:05.092Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314900735812436028"
author = "korieuko"
content = "https://avbebe.com/archives/259846"
createdAt = "2024-12-07T10:26:05.092Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/10/%E3%83%AA%E3%83%AB24.10-JaneDoe.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/259846"
title = "[リル] 24.10 JaneDoe"
image = "https://avbebe.com/wp-content/uploads/2024/10/%E3%83%AA%E3%83%AB24.10-JaneDoe.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
