id = "1314890692044128256"
name = "Jane x hoshimi futa"
archived = true
locked = false
createdAt = "2024-12-07T09:46:10.471Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314890692044128256"
author = "korieuko"
content = "https://rule34video.com/video/3592335/048-jane-x-hoshimi-futa-sex-sound-full-on-des-zzz/"
createdAt = "2024-12-07T09:46:10.471Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3592000/3592335/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3592335/048-jane-x-hoshimi-futa-sex-sound-full-on-des-zzz/"
title = "048 Jane x hoshimi FUTA sex [sound] full on des 【ZzZ】"
image = "https://rule34video.com/contents/videos_screenshots/3592000/3592335/preview.jpg"
site = "rule34video.com"
desc = "Full version (10:48) here: \n\nhttps://www.fanbox.cc/@acidrain002/posts/8871660\n\nScene by hongcha & imsayaa34 & ToTheMoon & yurabe \nThis video made by Acidrain\nWorks: https://www.iwara.tv/profile/nikonikoni002\nMore & Longer videos & Support creator: https://acidrain002.fanbox.cc"
