id = "1480058101016297683"
name = "Jane Doe - 1 : 'Mouse Trap' [SingularityNSFW]"
archived = false
locked = false
createdAt = "2026-03-08T04:22:29.432Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480058101016297683"
author = "korieuko"
content = "https://rule34video.com/video/4272175/jane-doe-1-mouse-trap-singularitynsfw/"
createdAt = "2026-03-08T04:22:29.432Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4272000/4272175/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4272175/jane-doe-1-mouse-trap-singularitynsfw/"
title = "Jane Doe - 1 : 'Mouse Trap' [SingularityNSFW]"
image = "https://rule34video.com/contents/videos_screenshots/4272000/4272175/preview.jpg"
site = "rule34video.com"
desc = "[\nJane wants to show you her new swimsuit...\nOr maybe something a little more than that~"
