id = "1377548011739283476"
name = "Ciaccona Doggy [half naked]"
archived = true
locked = false
createdAt = "2025-05-29T07:23:59.603Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377548011739283476"
author = "korieuko"
content = "https://rule34video.com/video/3857661/ciaccona-doggy-half-naked/"
createdAt = "2025-05-29T07:23:59.603Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3857000/3857661/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3857661/ciaccona-doggy-half-naked/"
title = "Ciaccona Doggy [half naked]"
image = "https://rule34video.com/contents/videos_screenshots/3857000/3857661/preview.jpg"
site = "rule34video.com"
desc = "https://realize.fanbox.cc/\n\n**Pls support the aritst !! **"
