id = "1390122257841651733"
name = "[Mellewd] Yixuan x Wise - Welcome to Suibian Temple"
archived = true
locked = false
createdAt = "2025-07-03T00:09:33.492Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1390122257841651733"
author = "korieuko"
content = "https://rule34video.com/video/3912929/mellewd-yixuan-x-wise-welcome-to-suibian-temple/"
createdAt = "2025-07-03T00:09:33.492Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3912000/3912929/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3912929/mellewd-yixuan-x-wise-welcome-to-suibian-temple/"
title = "[Mellewd] Yixuan x Wise - Welcome to Suibian Temple"
image = "https://rule34video.com/contents/videos_screenshots/3912000/3912929/preview.jpg"
site = "rule34video.com"
desc = ""
