id = "1375442505805332512"
name = "[SeventyFive3D] Yi xuan x Wise"
archived = true
locked = false
createdAt = "2025-05-23T11:57:27.870Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375442505805332512"
author = "korieuko"
content = "https://rule34video.com/video/3846997/seventyfive3d-yi-xuan-x-wise/"
createdAt = "2025-05-23T11:57:27.870Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3846000/3846997/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3846997/seventyfive3d-yi-xuan-x-wise/"
title = "[SeventyFive3D] Yi xuan x Wise"
image = "https://rule34video.com/contents/videos_screenshots/3846000/3846997/preview.jpg"
site = "rule34video.com"
desc = ""
