id = "1410626110961615043"
name = "[Tir_Al]2025.07 Yixuan all-angles 2K"
archived = true
locked = false
createdAt = "2025-08-28T14:04:33.019Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1410626110961615043"
author = "korieuko"
content = "https://rule34video.com/video/3992937/tir-al-2025-07-yixuan-all-angles-2k/"
createdAt = "2025-08-28T14:04:33.019Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3992000/3992937/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3992937/tir-al-2025-07-yixuan-all-angles-2k/"
title = "[Tir_Al]2025.07 Yixuan all-angles 2K"
image = "https://rule34video.com/contents/videos_screenshots/3992000/3992937/preview.jpg"
site = "rule34video.com"
desc = "yixuan-all-angles-tir-al_1080p.mp4"
