id = "1382976094478536764"
name = "[ZZZ]: Yixuan Sex~ 💛 | Iwara"
archived = true
locked = false
createdAt = "2025-06-13T06:53:15.377Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382976094478536764"
author = "korieuko"
content = "https://www.iwara.tv/video/sLIl8Q7wU1u2Pb/zzz-yixuan-sex"
createdAt = "2025-06-13T06:53:15.377Z"
pinned = false
attachments = ""
thumbnail = ""

[[messages.linkPreviews]]
url = "https://www.iwara.tv/video/sLIl8Q7wU1u2Pb/zzz-yixuan-sex"
title = "Iwara"
image = ""
site = "www.iwara.tv"
desc = "Iwara"
