id = "1463025092979200246"
name = "Lovest Oral inserion"
archived = true
locked = false
createdAt = "2026-01-20T04:19:23.858Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1463025092979200246"
author = "korieuko"
content = "https://rule34video.com/video/4206082/lovest-oral-inserion/"
createdAt = "2026-01-20T04:19:23.858Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4206000/4206082/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4206082/lovest-oral-inserion/"
title = "Lovest Oral inserion"
image = "https://rule34video.com/contents/videos_screenshots/4206000/4206082/preview.jpg"
site = "rule34video.com"
desc = "ko-fi.com/Saynor - Full 4 min , Link in bio"
