id = "1404846369608564958"
name = "SP25S3 Yixuan"
archived = true
locked = false
createdAt = "2025-08-12T15:17:55.298Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404846369608564958"
author = "korieuko"
content = "https://rule34video.com/video/3953885/sp25s3-yixuan/"
createdAt = "2025-08-12T15:17:55.298Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3953000/3953885/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3953885/sp25s3-yixuan/"
title = "SP25S3 Yixuan"
image = "https://rule34video.com/contents/videos_screenshots/3953000/3953885/preview.jpg"
site = "rule34video.com"
desc = ""
