id = "1404845961200664688"
name = "What Yixuan must do to protect her students [720p]"
archived = true
locked = false
createdAt = "2025-08-12T15:16:17.926Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404845961200664688"
author = "korieuko"
content = "https://rule34video.com/video/3961186/what-yixuan-must-do-to-protect-her-students-720p/"
createdAt = "2025-08-12T15:16:17.926Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3961000/3961186/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3961186/what-yixuan-must-do-to-protect-her-students-720p/"
title = "What Yixuan must do to protect her students [720p]"
image = "https://rule34video.com/contents/videos_screenshots/3961000/3961186/preview.jpg"
site = "rule34video.com"
desc = "All angles\n\nYixuan from Tir_Al with subtitles, for ambience enjoyers\n\nI personally don't like to sub these videos so early, but man, this one is just so peak! I almost turned it NTR ;)\n\nFor 4k and normal outfit version, go support the artist:\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"
