id = "1375442997042348032"
name = "Wise's First Training Session with Yixuan - Part 3 (4K) [Sileter]"
archived = true
locked = false
createdAt = "2025-05-23T11:59:24.990Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375442997042348032"
author = "korieuko"
content = "https://rule34video.com/video/3845321/wise-s-first-training-with-yixuan-part-3-4k-sileter/"
createdAt = "2025-05-23T11:59:24.990Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3845000/3845321/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3845321/wise-s-first-training-with-yixuan-part-3-4k-sileter/"
title = "Wise's First Training Session with Yixuan - Part 3 (4K) [Sileter]"
image = "https://rule34video.com/contents/videos_screenshots/3845000/3845321/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/sileter\nx.com/SileterNSFW"
