id = "1468940864662405191"
name = "Yixuan Hangout in Room (Sound Version) - Lazyrice3D"
archived = true
locked = false
createdAt = "2026-02-05T12:06:33.737Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468940864662405191"
author = "korieuko"
content = "https://rule34video.com/video/4230078/yixuan-hangout-in-room-sound-version-lazyrice3d/"
createdAt = "2026-02-05T12:06:33.737Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4230000/4230078/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4230078/yixuan-hangout-in-room-sound-version-lazyrice3d/"
title = "Yixuan Hangout in Room (Sound Version) - Lazyrice3D"
image = "https://rule34video.com/contents/videos_screenshots/4230000/4230078/preview.jpg"
site = "rule34video.com"
desc = ""
