id = "1382977340409249852"
name = "Yixuan"
archived = true
locked = false
createdAt = "2025-06-13T06:58:12.430Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382977340409249852"
author = "korieuko"
content = "https://rule34video.com/video/3876345/yixuan/"
createdAt = "2025-06-13T06:58:12.430Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
