id = "1382975518017585232"
name = "Yixuan smashed by ethereal"
archived = true
locked = false
createdAt = "2025-06-13T06:50:57.938Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382975518017585232"
author = "korieuko"
content = "https://rule34video.com/video/3865645/yixuan-smashed-by-ethereal/"
createdAt = "2025-06-13T06:50:57.938Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3865000/3865645/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3865645/yixuan-smashed-by-ethereal/"
title = "Yixuan smashed by ethereal"
image = "https://rule34video.com/contents/videos_screenshots/3865000/3865645/preview.jpg"
site = "rule34video.com"
desc = "Scene edit by : MintyCat \nOriginal scene by : Nyanify"
