id = "1404846206496149635"
name = "Yixuan"
archived = true
locked = false
createdAt = "2025-08-12T15:17:16.409Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404846206496149635"
author = "korieuko"
content = "https://rule34video.com/video/3956467/yixuan5/"
createdAt = "2025-08-12T15:17:16.409Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3956000/3956467/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3956467/yixuan5/"
title = "Yixuan"
image = "https://rule34video.com/contents/videos_screenshots/3956000/3956467/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/HeikeLuxur"
