id = "1418852885265125528"
name = "Nilou Aline_EN"
archived = true
locked = false
createdAt = "2025-09-20T06:54:48.859Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = ["1391323430212599901"]

[[messages]]
id = "1418852885265125528"
author = "korieuko"
content = "https://rule34video.com/video/3647111/nilou-aline-en/"
createdAt = "2025-09-20T06:54:48.859Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3647000/3647111/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3647111/nilou-aline-en/"
title = "Nilou Aline_EN"
image = "https://rule34video.com/contents/videos_screenshots/3647000/3647111/preview.jpg"
site = "rule34video.com"
desc = ""
