id = "1406600409950195722"
name = "Lumine continues wring out Clorinde (4K) [Lyusfyuring]"
archived = true
locked = false
createdAt = "2025-08-17T11:27:51.104Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406600409950195722"
author = "korieuko"
content = "https://rule34video.com/video/3949309/lumine-continues-wring-out-clorinde-4k-lyusfyuring/"
createdAt = "2025-08-17T11:27:51.104Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3949000/3949309/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3949309/lumine-continues-wring-out-clorinde-4k-lyusfyuring/"
title = "Lumine continues wring out Clorinde (4K) [Lyusfyuring]"
image = "https://rule34video.com/contents/videos_screenshots/3949000/3949309/preview.jpg"
site = "rule34video.com"
desc = ""
