id = "1394118678169125046"
name = "Lumine x Clorinde part 1-2 - Lyusfyuring"
archived = true
locked = false
createdAt = "2025-07-14T00:49:54.348Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394118678169125046"
author = "korieuko"
content = "https://rule34video.com/video/3443469/lumine-x-clorinde-part-1-2-lyusfyuring/"
createdAt = "2025-07-14T00:49:54.348Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3443000/3443469/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3443469/lumine-x-clorinde-part-1-2-lyusfyuring/"
title = "Lumine x Clorinde part 1-2 - Lyusfyuring"
image = "https://rule34video.com/contents/videos_screenshots/3443000/3443469/preview.jpg"
site = "rule34video.com"
desc = "Zzz"
