id = "1322519260848853083"
name = "[01]【ruan mei】0612 Clothed Sound Ver"
archived = true
locked = false
createdAt = "2024-12-28T10:59:23.006Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1322519260848853083"
author = "korieuko"
content = "https://rule34video.com/video/3526863/01-ruan-mei-0612-clothed-sound-ver/"
createdAt = "2024-12-28T10:59:23.006Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3526000/3526863/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3526863/01-ruan-mei-0612-clothed-sound-ver/"
title = "[01]【ruan mei】0612 Clothed Sound Ver"
image = "https://rule34video.com/contents/videos_screenshots/3526000/3526863/preview.jpg"
site = "rule34video.com"
desc = "2024.06"
