id = "1314867199881646152"
name = "[akira_Brave777] 2024年SP6月 崩壊スターレイル02ルアン・メェイ"
archived = true
locked = false
createdAt = "2024-12-07T08:12:49.503Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314867199881646152"
author = "korieuko"
content = "https://avbebe.com/archives/232614"
createdAt = "2024-12-07T08:12:49.503Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
