id = "1383698538235428864"
name = "(HD) Ruan Mei [Velnier]"
archived = true
locked = false
createdAt = "2025-06-15T06:43:59.391Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1383698538235428864"
author = "korieuko"
content = "https://rule34video.com/video/3837681/hd-ruan-mei-velnier/"
createdAt = "2025-06-15T06:43:59.391Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
