id = "1314844327989739562"
name = "[Sutekimeppou] Ruan Mei Release!"
archived = true
locked = false
createdAt = "2024-12-07T06:41:56.419Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314844327989739562"
author = "korieuko"
content = "https://avbebe.com/archives/229310"
createdAt = "2024-12-07T06:41:56.419Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/06/Ruan-Mei-Release.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/229310"
title = "[Sutekimeppou] Ruan Mei Release!"
image = "https://avbebe.com/wp-content/uploads/2024/06/Ruan-Mei-Release.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
