id = "1388460871281414245"
name = "A day with Ruan Mei[vel velnier] [4k 60fps]"
archived = true
locked = false
createdAt = "2025-06-28T10:07:48.069Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388460871281414245"
author = "korieuko"
content = "https://rule34video.com/video/3838101/a-day-with-ruan-mei-vel-velnier-4k-60fps/"
createdAt = "2025-06-28T10:07:48.069Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
