id = "1418854072194437186"
name = "Rayx - Ruan mei"
archived = true
locked = false
createdAt = "2025-09-20T06:59:31.845Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = ["1418853154631585843"]

[[messages]]
id = "1418854072194437186"
author = "korieuko"
content = "https://rule34video.com/video/3323439/rayx-ruan-mei/"
createdAt = "2025-09-20T06:59:31.845Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3323000/3323439/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3323439/rayx-ruan-mei/"
title = "Rayx - Ruan mei"
image = "https://rule34video.com/contents/videos_screenshots/3323000/3323439/preview.jpg"
site = "rule34video.com"
desc = ""
