id = "1314889205318553642"
name = "Ruan Mei X Lingsha"
archived = true
locked = false
createdAt = "2024-12-07T09:40:16.008Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314889205318553642"
author = "korieuko"
content = "https://rule34video.com/video/3563676/adler-ruan-mei-x-lingsha/"
createdAt = "2024-12-07T09:40:16.008Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3563000/3563676/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3563676/adler-ruan-mei-x-lingsha/"
title = "[ADLER] Ruan Mei x Lingsha"
image = "https://rule34video.com/contents/videos_screenshots/3563000/3563676/preview.jpg"
site = "rule34video.com"
desc = ""
