id = "1322518379239706644"
name = "Ruan Mei [Short]"
archived = true
locked = false
createdAt = "2024-12-28T10:55:52.814Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1322518379239706644"
author = "korieuko"
content = "https://rule34video.com/video/3207819/ruanmei/"
createdAt = "2024-12-28T10:55:52.814Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3207000/3207819/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3207819/ruanmei/"
title = "ruanmei"
image = "https://rule34video.com/contents/videos_screenshots/3207000/3207819/preview.jpg"
site = "rule34video.com"
desc = ""
