id = "1377547265505234967"
name = "Jinhsi Doggy [mw9]"
archived = true
locked = false
createdAt = "2025-05-29T07:21:01.687Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377547265505234967"
author = "korieuko"
content = "https://rule34video.com/video/3857269/jinhsi-doggy-mw9/"
createdAt = "2025-05-29T07:21:01.687Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3857000/3857269/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3857269/jinhsi-doggy-mw9/"
title = "Jinhsi Doggy [mw9]"
image = "https://rule34video.com/contents/videos_screenshots/3857000/3857269/preview.jpg"
site = "rule34video.com"
desc = "Animation: https://x.com/mw9_tw\n\n***Futa Version on artist twitter page***"
