id = "1377546227851333692"
name = "Jinhsi - Peach Blossom"
archived = true
locked = false
createdAt = "2025-05-29T07:16:54.291Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377546227851333692"
author = "korieuko"
content = "https://rule34video.com/video/3854985/jinhsi-peach-blossom2/"
createdAt = "2025-05-29T07:16:54.291Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
