id = "1396158301049454602"
name = "Jinhsi_Wuthering Waves [RDreamer]"
archived = true
locked = false
createdAt = "2025-07-19T15:54:38.337Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1396158301049454602"
author = "korieuko"
content = "https://rule34video.com/video/3939677/jinhsi-wuthering-waves-rdreamer/"
createdAt = "2025-07-19T15:54:38.337Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3939000/3939677/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3939677/jinhsi-wuthering-waves-rdreamer/"
title = "Jinhsi_Wuthering Waves [RDreamer]"
image = "https://rule34video.com/contents/videos_screenshots/3939000/3939677/preview.jpg"
site = "rule34video.com"
desc = "Jinhsi_Wuthering Waves [RDreamer]\n\n:||"
