id = "1322520382560927765"
name = "Wuthering Waves Jinshi"
archived = true
locked = false
createdAt = "2024-12-28T11:03:50.443Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1322520382560927765"
author = "korieuko"
content = "https://rule34video.com/video/3471504/wuthering-waves-jinhsi/"
createdAt = "2024-12-28T11:03:50.443Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
