id = "1314904300266455091"
name = "[リル] FireFly"
archived = true
locked = false
createdAt = "2024-12-07T10:40:14.924Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314904300266455091"
author = "korieuko"
content = "https://avbebe.com/archives/259842"
createdAt = "2024-12-07T10:40:14.924Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
