id = "1314902847556419594"
name = "[トプ/Topu] ホタル Live2D"
archived = true
locked = false
createdAt = "2024-12-07T10:34:28.571Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314902847556419594"
author = "korieuko"
content = "https://avbebe.com/archives/231938"
createdAt = "2024-12-07T10:34:28.571Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/06/%E3%83%9B%E3%82%BF%E3%83%AB-Live2D.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/231938"
title = "[トプ/Topu] ホタル Live2D"
image = "https://avbebe.com/wp-content/uploads/2024/06/%E3%83%9B%E3%82%BF%E3%83%AB-Live2D.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe #1 streamwish"
