id = "1314901112855335072"
name = "[トプ (topu)] Firefly Live2D"
archived = true
locked = false
createdAt = "2024-12-07T10:27:34.986Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314901112855335072"
author = "korieuko"
content = "https://avbebe.com/archives/236746"
createdAt = "2024-12-07T10:27:34.986Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
