id = "1314848704917803009"
name = "Yuluer [FireFly]"
archived = true
locked = false
createdAt = "2024-12-07T06:59:19.960Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314848704917803009"
author = "korieuko"
content = "https://avbebe.com/archives/207008"
createdAt = "2024-12-07T06:59:19.960Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/03/%E3%83%9B%E3%82%BF%E3%83%AB.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/207008"
title = "[Yuluer] ホタル"
image = "https://avbebe.com/wp-content/uploads/2024/03/%E3%83%9B%E3%82%BF%E3%83%AB.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe #1 SERVER #2"
