id = "1467177633706934378"
name = "Wuthering Waves Compilation With Sound"
archived = true
locked = false
createdAt = "2026-01-31T15:20:06.718Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1467177633706934378"
author = "korieuko"
content = "https://rule34video.com/video/4219966/wuthering-waves-compilation-with-sound/"
createdAt = "2026-01-31T15:20:06.718Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4219000/4219966/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4219966/wuthering-waves-compilation-with-sound/"
title = "Wuthering Waves Compilation With Sound"
image = "https://rule34video.com/contents/videos_screenshots/4219000/4219966/preview.jpg"
site = "rule34video.com"
desc = ""
