id = "1383698306407993425"
name = "2 best maid Phoebe & Cartethyia"
archived = true
locked = false
createdAt = "2025-06-15T06:43:04.119Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1383698306407993425"
author = "korieuko"
content = "https://rule34video.com/video/3880885/2-best-maid-phoebe-cartethyia/"
createdAt = "2025-06-15T06:43:04.119Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3880000/3880885/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3880885/2-best-maid-phoebe-cartethyia/"
title = "2 best maid  Phoebe & Cartethyia"
image = "https://rule34video.com/contents/videos_screenshots/3880000/3880885/preview.jpg"
site = "rule34video.com"
desc = "C606\n@cchhen2604"
