id = "1384537766355927120"
name = "[RDreamer] Fleurdelys x Rover"
archived = true
locked = false
createdAt = "2025-06-17T14:18:46.967Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1384537766355927120"
author = "korieuko"
content = "https://rule34video.com/video/3887677/rdreamer-fleurdelys-x-rover/"
createdAt = "2025-06-17T14:18:46.967Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3887000/3887677/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3887677/rdreamer-fleurdelys-x-rover/"
title = "[RDreamer] Fleurdelys x Rover"
image = "https://rule34video.com/contents/videos_screenshots/3887000/3887677/preview.jpg"
site = "rule34video.com"
desc = ""
