id = "1369525191243337748"
name = "[RDreamer] Cartethyia x Rover"
archived = true
locked = false
createdAt = "2025-05-07T04:04:10.140Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1369525191243337748"
author = "korieuko"
content = "https://rule34video.com/video/3819149/rdreamer-cartethyia-x-rover/"
createdAt = "2025-05-07T04:04:10.140Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3819000/3819149/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3819149/rdreamer-cartethyia-x-rover/"
title = "[RDreamer] Cartethyia x Rover"
image = "https://rule34video.com/contents/videos_screenshots/3819000/3819149/preview.jpg"
site = "rule34video.com"
desc = "Artist: https://rdreamer.fanbox.cc/\n\nEdited and compiled by me"
