id = "1369525324089397288"
name = "[VikLodn] Cartethyia 4K"
archived = true
locked = false
createdAt = "2025-05-07T04:04:41.813Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1369525324089397288"
author = "korieuko"
content = "https://rule34video.com/video/3820445/4k-cartethyia-viklodn/"
createdAt = "2025-05-07T04:04:41.813Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3820000/3820445/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3820445/4k-cartethyia-viklodn/"
title = "[VikLodn] Cartethyia 4K"
image = "https://rule34video.com/contents/videos_screenshots/3820000/3820445/preview.jpg"
site = "rule34video.com"
desc = ""
