id = "1404845297556787262"
name = "Carthetyia 4k by Kiramekuhoshi"
archived = true
locked = false
createdAt = "2025-08-12T15:13:39.701Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404845297556787262"
author = "korieuko"
content = "https://rule34video.com/video/3968962/carthetyia-4k-by-kiramekuhoshi/"
createdAt = "2025-08-12T15:13:39.701Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3968000/3968962/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3968962/carthetyia-4k-by-kiramekuhoshi/"
title = "Carthetyia 4k by Kiramekuhoshi"
image = "https://rule34video.com/contents/videos_screenshots/3968000/3968962/preview.jpg"
site = "rule34video.com"
desc = ""
