id = "1384881075993706506"
name = "Cartethyia getting pumped by a Monster"
archived = true
locked = false
createdAt = "2025-06-18T13:02:58.363Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1384881075993706506"
author = "korieuko"
content = "https://rule34video.com/video/3888509/cartethyia-getting-pumped/"
createdAt = "2025-06-18T13:02:58.363Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3888000/3888509/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3888509/cartethyia-getting-pumped/"
title = "Cartethyia getting pumped by a Monster"
image = "https://rule34video.com/contents/videos_screenshots/3888000/3888509/preview.jpg"
site = "rule34video.com"
desc = "Artist: JibrishNSFW,\n\nEnjoy the Video (:"
