id = "1385583756349542400"
name = "Cartethyia sex initiation"
archived = true
locked = false
createdAt = "2025-06-20T11:35:10.415Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1385583756349542400"
author = "korieuko"
content = "https://rule34video.com/video/3892485/cartethyia-sex-initiation/"
createdAt = "2025-06-20T11:35:10.415Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
