id = "1375455785773039797"
name = "Cartethyia×Fleurdelys_Wuthering Waves [6aminoac9]"
archived = true
locked = false
createdAt = "2025-05-23T12:50:14.061Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375455785773039797"
author = "korieuko"
content = "https://rule34video.com/video/3849217/cartethyia-fleurdelys-wuthering-waves-6aminoac9/"
createdAt = "2025-05-23T12:50:14.061Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3849000/3849217/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3849217/cartethyia-fleurdelys-wuthering-waves-6aminoac9/"
title = "Cartethyia×Fleurdelys_Wuthering Waves [6aminoac9]"
image = "https://rule34video.com/contents/videos_screenshots/3849000/3849217/preview.jpg"
site = "rule34video.com"
desc = ":||"
