id = "1377662685071675452"
name = "Carthetyia/fleurdelys"
archived = true
locked = false
createdAt = "2025-05-29T14:59:39.856Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377662685071675452"
author = "korieuko"
content = "https://rule34video.com/video/3856981/carthetyia-fleurdelys/"
createdAt = "2025-05-29T14:59:39.856Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3856000/3856981/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3856981/carthetyia-fleurdelys/"
title = "carthetyia/fleurdelys"
image = "https://rule34video.com/contents/videos_screenshots/3856000/3856981/preview.jpg"
site = "rule34video.com"
desc = "creator: makoda_mako\nmakoda's X: https://x.com/makoda_mako"
