id = "1385583629970706432"
name = "Fleur de Lys Assfucked"
archived = true
locked = false
createdAt = "2025-06-20T11:34:40.284Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1385583629970706432"
author = "korieuko"
content = "https://rule34video.com/video/3892481/fleur-de-lys-assfucked/"
createdAt = "2025-06-20T11:34:40.284Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3892000/3892481/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3892481/fleur-de-lys-assfucked/"
title = "Fleur de Lys Assfucked"
image = "https://rule34video.com/contents/videos_screenshots/3892000/3892481/preview.jpg"
site = "rule34video.com"
desc = ""
