id = "1377547927907598427"
name = "Fleurdelys [Rdreamer]"
archived = true
locked = false
createdAt = "2025-05-29T07:23:39.616Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377547927907598427"
author = "korieuko"
content = "https://rule34video.com/video/3857681/fleurdelys-rdreamer/"
createdAt = "2025-05-29T07:23:39.616Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
