id = "1429127182437060690"
name = "Special Time&#34; with Fleurdelys"
archived = true
locked = false
createdAt = "2025-10-18T15:21:12.192Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1429127182437060690"
author = "korieuko"
content = "https://rule34video.com/video/4069326/special-time-with-fleurdelys/"
createdAt = "2025-10-18T15:21:12.192Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4069000/4069326/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4069326/special-time-with-fleurdelys/"
title = "&#34;Special Time&#34; with Fleurdelys"
image = "https://rule34video.com/contents/videos_screenshots/4069000/4069326/preview.jpg"
site = "rule34video.com"
desc = "You make a special request to Cartethyia, to bring out Fleurdelys...\n\nBut you'll surely thank Cartethyia later too, won't you?\n\nFollow me on X: https://x.com/Singularity618\nPatreon: patreon.com/SingularityNSFW"
