id = "1314904463622017124"
name = "[リル] 八重神子 Live2dko"
archived = true
locked = false
createdAt = "2024-12-07T10:40:53.871Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314904463622017124"
author = "korieuko"
content = "https://avbebe.com/archives/200910"
createdAt = "2024-12-07T10:40:53.871Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/02/%E5%85%AB%E9%87%8D%E7%A5%9E%E5%AD%90-Live2dko.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/200910"
title = "[リル] 八重神子 Live2dko"
image = "https://avbebe.com/wp-content/uploads/2024/02/%E5%85%AB%E9%87%8D%E7%A5%9E%E5%AD%90-Live2dko.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "虎克 虎克 八重神子 八重神子 推薦 影"
