id = "1314862470589972522"
name = "[YESUI] Yae Miko 八重神子 Animation [原神]"
archived = true
locked = false
createdAt = "2024-12-07T07:54:01.952Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314862470589972522"
author = "korieuko"
content = "https://avbebe.com/archives/181790"
createdAt = "2024-12-07T07:54:01.952Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2023/09/YESUI-Yae-Miko-%E5%85%AB%E9%87%8D%E7%A5%9E%E5%AD%90-Animation-%E5%8E%9F%E7%A5%9E-scaled.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/181790"
title = "[YESUI] Yae Miko 八重神子 Animation [原神]"
image = "https://avbebe.com/wp-content/uploads/2023/09/YESUI-Yae-Miko-%E5%85%AB%E9%87%8D%E7%A5%9E%E5%AD%90-Animation-%E5%8E%9F%E7%A5%9E-scaled.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe影片 SERVER #2 A"
