id = "1440355653213356082"
name = "Yae Miko - Passionate Breeding Fuck[NO WM][Velnier][4k 60fps]"
archived = true
locked = false
createdAt = "2025-11-18T14:59:08.240Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1440355653213356082"
author = "korieuko"
content = "https://rule34video.com/video/4099371/yae-miko-teen-s-passionate-breeding-fuck-no-wm-velnier-4k-60fps/"
createdAt = "2025-11-18T14:59:08.240Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4099000/4099371/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4099371/yae-miko-teen-s-passionate-breeding-fuck-no-wm-velnier-4k-60fps/"
title = "Yae Miko - Passionate Breeding Fuck[NO WM][Velnier][4k 60fps]"
image = "https://rule34video.com/contents/videos_screenshots/4099000/4099371/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Velnier\n\nhttps://www.patreon.com/Velnier\n\nhttps://velnier.fanbox.cc/"
