id = "1314846034861494302"
name = "[Yuluer] march"
archived = true
locked = false
createdAt = "2024-12-07T06:48:43.369Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314846034861494302"
author = "korieuko"
content = "https://avbebe.com/archives/244586"
createdAt = "2024-12-07T06:48:43.369Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
