id = "1390121305457823838"
name = "Strinova - Lawine x Yvette x Kokona"
archived = true
locked = false
createdAt = "2025-07-03T00:05:46.426Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1390121305457823838"
author = "korieuko"
content = "https://rule34video.com/video/3858097/strinova-sex-lawine-x-yvette-x-kokona/"
createdAt = "2025-07-03T00:05:46.426Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3858000/3858097/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3858097/strinova-sex-lawine-x-yvette-x-kokona/"
title = "Strinova - Lawine x Yvette x Kokona"
image = "https://rule34video.com/contents/videos_screenshots/3858000/3858097/preview.jpg"
site = "rule34video.com"
desc = "link: https://www.iwara.tv/video/DUVaq2nJPArtQS"
