id = "1472260531544133632"
name = "Fluorite"
archived = false
locked = false
createdAt = "2026-02-14T15:57:43.998Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1472260531544133632"
author = "korieuko"
content = "https://rule34video.com/video/4235906/fluorite/"
createdAt = "2026-02-14T15:57:43.998Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4235000/4235906/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4235906/fluorite/"
title = "Fluorite"
image = "https://rule34video.com/contents/videos_screenshots/4235000/4235906/preview.jpg"
site = "rule34video.com"
desc = ""
