id = "1468226771429232642"
name = "Naturally Toxic"
archived = true
locked = false
createdAt = "2026-02-03T12:49:00.643Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468226771429232642"
author = "korieuko"
content = "https://rule34video.com/video/4225474/naturally-toxic/"
createdAt = "2026-02-03T12:49:00.643Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4225000/4225474/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4225474/naturally-toxic/"
title = "Naturally Toxic"
image = "https://rule34video.com/contents/videos_screenshots/4225000/4225474/preview.jpg"
site = "rule34video.com"
desc = "Flourite - kallenz\nWise - SegsUltimate\nSFX - LeHornySFX3D | OpenNSFWSP\nVA - chiyo1000nights | OpenNSFWSP"
