id = "1314843633010348042"
name = "Honkai Star Rail[NSFW]"
guildId = "1314839006717935696"
guildName = "Invrs ✦ NSFW"
backedUpAt = "2026-03-08T13:44:48.645Z"
contents = ["forum: forum-march", "forum: forum-ruan-mei", "forum: forum-topaz", "forum: forum-black-swan", "forum: forum-bronya", "forum: forum-fire-fly", "forum: forum-acheron", "forum: forum-lingsha", "forum: forum-herta", "forum: forum-feixiao", "forum: forum-kafka", "forum: forum-cipher", "forum: forum-saber", "forum: forum-hysilens", "forum: forum-cerydra", "forum: forum-evernight", "forum: forum-cyrene", "forum: forum-yaoguang"]

[stats]
totalForums = 18
totalChannels = 0
totalThreads = 126
totalMessages = 134
