id = "1396831510887141501"
name = "Bartender Burnice Full [Puuguy]"
archived = true
locked = false
createdAt = "2025-07-21T12:29:44.070Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1396831510887141501"
author = "korieuko"
content = "https://rule34video.com/video/3943029/bartender-burnice-full-puuguy/"
createdAt = "2025-07-21T12:29:44.070Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3943000/3943029/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3943029/bartender-burnice-full-puuguy/"
title = "Bartender Burnice Full [Puuguy]"
image = "https://rule34video.com/contents/videos_screenshots/3943000/3943029/preview.jpg"
site = "rule34video.com"
desc = "source\nhttps://x.com/Puuguy/status/1946264681494327747\n\nanimation by puuguy, please support link below\nhttps://t.co/VkwKTmZCm9\n\ncheck my profile for some peak reuploads\n\nAudio:\n@Evilaudio1\n\nVoice:\n@Rosemarilovesu\n\nBurnice&male:\n@DaB_neko\n\nMy note: No creampie :(\n\nany missing or incorrect tags? suggest a tag below or dm me with video link"
