id = "1375453358567063622"
name = "Best Morning with Burnice[RedRain3D] [edited] [4k 60fps]"
archived = true
locked = false
createdAt = "2025-05-23T12:40:35.370Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375453358567063622"
author = "korieuko"
content = "https://rule34video.com/video/3842157/best-morning-with-burnice-redrain3d-edited-4k-60fps/"
createdAt = "2025-05-23T12:40:35.370Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3842000/3842157/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3842157/best-morning-with-burnice-redrain3d-edited-4k-60fps/"
title = "Best Morning with Burnice[RedRain3D] [edited] [4k 60fps]"
image = "https://rule34video.com/contents/videos_screenshots/3842000/3842157/preview.jpg"
site = "rule34video.com"
desc = "Models by: DaB_neko\n\nBurnice VA by: Misuzugon\n\nSFX by: ImJustThatKinky\n\nhttps://x.com/RedRain3D\n\nhttps://www.patreon.com/redrain3d"
