id = "1462032335267692640"
name = "Burnice in trouble"
archived = true
locked = false
createdAt = "2026-01-17T10:34:31.975Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1462032335267692640"
author = "korieuko"
content = "https://rule34video.com/video/4202961/burnice-in-trouble/"
createdAt = "2026-01-17T10:34:31.975Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4202000/4202961/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4202961/burnice-in-trouble/"
title = "Burnice in trouble"
image = "https://rule34video.com/contents/videos_screenshots/4202000/4202961/preview.jpg"
site = "rule34video.com"
desc = "seems like burnice had her share of fun! if you liked it consider following me on X! i will do my best to improve with every animation :D https://x.com/Zairo3D"
