id = "1467177503507615907"
name = "Burnice on fire - Full"
archived = true
locked = false
createdAt = "2026-01-31T15:19:35.676Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1467177503507615907"
author = "korieuko"
content = "https://rule34video.com/video/4220594/burnice-on-fire-full2/"
createdAt = "2026-01-31T15:19:35.676Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4220000/4220594/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4220594/burnice-on-fire-full2/"
title = "Burnice on fire - Full"
image = "https://rule34video.com/contents/videos_screenshots/4220000/4220594/preview.jpg"
site = "rule34video.com"
desc = "Burnice has to put out the fire.\nMore exclusives animations on my patreon!\npatreon.com/Vast3D\n\nAnimation: @Vastt3D\nModels: @DaB_neko\nSFX Pack: @OpenNSFWSP\nVA: @Misuzugon\nBG: @XiaoLambo"
