id = "1375442396258635866"
name = "Burnice! (No Male) [TwiistedLewds]"
archived = true
locked = false
createdAt = "2025-05-23T11:57:01.752Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375442396258635866"
author = "korieuko"
content = "https://rule34video.com/video/3848585/burnice-no-male-twiistedlewds/"
createdAt = "2025-05-23T11:57:01.752Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3848000/3848585/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3848585/burnice-no-male-twiistedlewds/"
title = "Burnice! (No Male) [TwiistedLewds]"
image = "https://rule34video.com/contents/videos_screenshots/3848000/3848585/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/TwiistedLewds\nx.com/TwiistedLewds"
