id = "1417433286833082428"
name = "Burnice, Sons of Calydon's defeat [Subbed]"
archived = true
locked = false
createdAt = "2025-09-16T08:53:50.218Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1417433286833082428"
author = "korieuko"
content = "https://rule34video.com/video/4030385/burnice-sons-of-calydon-s-defeat-subbed2/"
createdAt = "2025-09-16T08:53:50.218Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4030000/4030385/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4030385/burnice-sons-of-calydon-s-defeat-subbed2/"
title = "Burnice, Sons of Calydon's defeat [Subbed]"
image = "https://rule34video.com/contents/videos_screenshots/4030000/4030385/preview.jpg"
site = "rule34video.com"
desc = "Burnice from Tir_AL with subtitles, for ambience enjoyers\n\nSupport the artist:\n\nhttps://www.patreon.com/tir_al (Vote for Iuno :'v)\nhttps://x.com/tir_al_"
