id = "1406985848024600650"
name = "Burnice - Riding"
archived = true
locked = false
createdAt = "2025-08-18T12:59:26.702Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406985848024600650"
author = "korieuko"
content = "https://rule34video.com/video/3967270/burnice-riding/"
createdAt = "2025-08-18T12:59:26.702Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3967000/3967270/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3967270/burnice-riding/"
title = "Burnice - Riding"
image = "https://rule34video.com/contents/videos_screenshots/3967000/3967270/preview.jpg"
site = "rule34video.com"
desc = "No Watermark + Nude: https://www.patreon.com/c/EcchiWaffle\n\nAnimation - LazyProcrastinator\nNicole VA - @Misuzugon\nAudio - Me"
