id = "1401378528124997702"
name = "No snacks Burnice, you're next on the menu ( Dubbed )"
archived = true
locked = false
createdAt = "2025-08-03T01:37:57.459Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1401378528124997702"
author = "korieuko"
content = "https://rule34video.com/video/3961722/no-snacks-burnice-you-re-next-on-the-menu-dubbed/"
createdAt = "2025-08-03T01:37:57.459Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3961000/3961722/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3961722/no-snacks-burnice-you-re-next-on-the-menu-dubbed/"
title = "No snacks Burnice, you're next on the menu ( Dubbed )"
image = "https://rule34video.com/contents/videos_screenshots/3961000/3961722/preview.jpg"
site = "rule34video.com"
desc = "Animation : \nTwiistedLewds\n \nBurnice VA : \nnsfw_sonia_va\n \nMale VA / SFX Edit : \nMephistoJonesVA\n \nSFX Packs : \nOpenNSFWSP\n \nModels by : \nDaB_neko"
