id = "1375455391735091253"
name = "Sons of Calydon Incident [BurryFuzz]"
archived = true
locked = false
createdAt = "2025-05-23T12:48:40.115Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375455391735091253"
author = "korieuko"
content = "https://rule34video.com/video/3801957/burnice-lucy-x-ethereal-burryfuzz/"
createdAt = "2025-05-23T12:48:40.115Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3801000/3801957/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3801957/burnice-lucy-x-ethereal-burryfuzz/"
title = "Sons of Calydon Incident [BurryFuzz]"
image = "https://rule34video.com/contents/videos_screenshots/3801000/3801957/preview.jpg"
site = "rule34video.com"
desc = "Created by\nsubscribestar.adult/burryfuzz\nx.com/BFuzzR18\n\nBurnice VA: RubyRed\nLucy VA: LecheryAmore"
