id = "1349625684338937946"
name = "Stuffing The Cat Girl"
archived = true
locked = false
createdAt = "2025-03-13T06:10:37.979Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1349625684338937946"
author = "korieuko"
content = "https://rule34video.com/video/3571581/stuffing-the-cat-girl/"
createdAt = "2025-03-13T06:10:37.979Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3571000/3571581/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3571581/stuffing-the-cat-girl/"
title = "&#34;Stuffing The Cat Girl&#34;"
image = "https://rule34video.com/contents/videos_screenshots/3571000/3571581/preview.jpg"
site = "rule34video.com"
desc = "Nekomiya decided to test her limits with a monster.\n\nNekomata: @SuccuAiniVoice\n\nFarbauti: @Shiroo_VA\n\nEditor: @EleetApricot\n\nAnimation: @rouge_nine\n\nSFX Pack: @OpenNSFWSP"
