id = "1372129639836815480"
name = "(4K) Citlali (Part 2) [AidenHet]"
archived = true
locked = false
createdAt = "2025-05-14T08:33:19.073Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1372129639836815480"
author = "korieuko"
content = "https://rule34video.com/video/3830693/4k-citlali-part-2-aidenhet/"
createdAt = "2025-05-14T08:33:19.073Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3830000/3830693/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3830693/4k-citlali-part-2-aidenhet/"
title = "(4K) Citlali (Part 2) [AidenHet]"
image = "https://rule34video.com/contents/videos_screenshots/3830000/3830693/preview.jpg"
site = "rule34video.com"
desc = ""
