id = "1448930734193508483"
name = "[Jibrish] Citlali Drunken"
archived = true
locked = false
createdAt = "2025-12-12T06:53:26.863Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1448930734193508483"
author = "korieuko"
content = "https://rule34video.com/video/3730837/jibrish-citlali-drunken2/"
createdAt = "2025-12-12T06:53:26.863Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3730000/3730837/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3730837/jibrish-citlali-drunken2/"
title = "[Jibrish] Citlali Drunken"
image = "https://rule34video.com/contents/videos_screenshots/3730000/3730837/preview.jpg"
site = "rule34video.com"
desc = ""
