id = "1399627137077477417"
name = "Citlali [BlueWingsP]"
archived = true
locked = false
createdAt = "2025-07-29T05:38:33.294Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1399627137077477417"
author = "korieuko"
content = "https://rule34video.com/video/3874057/citlali-bluewingsp/"
createdAt = "2025-07-29T05:38:33.294Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3874000/3874057/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3874057/citlali-bluewingsp/"
title = "Citlali [BlueWingsP]"
image = "https://rule34video.com/contents/videos_screenshots/3874000/3874057/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/BlueWingsP/status/1915085325312938206"
