id = "1406599044595318857"
name = "Citlali [NeetoLoops]"
archived = true
locked = false
createdAt = "2025-08-17T11:22:25.578Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406599044595318857"
author = "korieuko"
content = "https://rule34video.com/video/3963170/citlali-neetoloops/"
createdAt = "2025-08-17T11:22:25.578Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3963000/3963170/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3963170/citlali-neetoloops/"
title = "Citlali [NeetoLoops]"
image = "https://rule34video.com/contents/videos_screenshots/3963000/3963170/preview.jpg"
site = "rule34video.com"
desc = ""
