id = "1406598500698820669"
name = "Drunken Citlali Part 4 [Kiramekuhoshi]"
archived = true
locked = false
createdAt = "2025-08-17T11:20:15.903Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406598500698820669"
author = "korieuko"
content = "https://rule34video.com/video/3976200/drunken-citlali-part-4-kiramekuhoshi/"
createdAt = "2025-08-17T11:20:15.903Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3976000/3976200/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3976200/drunken-citlali-part-4-kiramekuhoshi/"
title = "Drunken Citlali Part 4 [Kiramekuhoshi]"
image = "https://rule34video.com/contents/videos_screenshots/3976000/3976200/preview.jpg"
site = "rule34video.com"
desc = "For 4K and semen version, go visit: https://kiramekuhoshi.fanbox.cc/"
