id = "1398958247280377880"
name = "Reading before bed with Citlali"
archived = true
locked = false
createdAt = "2025-07-27T09:20:37.539Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1398958247280377880"
author = "korieuko"
content = "https://rule34video.com/video/3951037/reading-before-bed-with-citlali/"
createdAt = "2025-07-27T09:20:37.539Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
