id = "1385583548081246368"
name = "Rough sex with drunk Citlali (alt.ver.) [Kiramekuhoshi]"
archived = true
locked = false
createdAt = "2025-06-20T11:34:20.760Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1385583548081246368"
author = "korieuko"
content = "https://rule34video.com/video/3893329/rough-sex-with-drunk-citlali-alt-ver-kiramekuhoshi/"
createdAt = "2025-06-20T11:34:20.760Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3893000/3893329/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3893329/rough-sex-with-drunk-citlali-alt-ver-kiramekuhoshi/"
title = "Rough sex with drunk Citlali (alt.ver.) [Kiramekuhoshi]"
image = "https://rule34video.com/contents/videos_screenshots/3893000/3893329/preview.jpg"
site = "rule34video.com"
desc = "https://kiramekuhoshi.fanbox.cc/"
