id = "1459401205267562547"
name = "(4K60) Ye Shunguang [HoyoCinema]"
archived = true
locked = false
createdAt = "2026-01-10T04:19:21.699Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1459401205267562547"
author = "korieuko"
content = "https://rule34video.com/video/4188395/4k60-ye-shunguang-hoyocinema/"
createdAt = "2026-01-10T04:19:21.699Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4188000/4188395/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4188395/4k60-ye-shunguang-hoyocinema/"
title = "(4K60) Ye Shunguang [HoyoCinema]"
image = "https://rule34video.com/contents/videos_screenshots/4188000/4188395/preview.jpg"
site = "rule34video.com"
desc = "I think my ears have been blessed (and fucked)"
