id = "1480057876012859446"
name = "[Tir_AL] ye shuguang"
archived = false
locked = false
createdAt = "2026-03-08T04:21:35.787Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480057876012859446"
author = "korieuko"
content = "https://rule34video.com/video/4272277/tir-al-ye-shuguang/"
createdAt = "2026-03-08T04:21:35.787Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4272000/4272277/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4272277/tir-al-ye-shuguang/"
title = "[Tir_AL] ye shuguang"
image = "https://rule34video.com/contents/videos_screenshots/4272000/4272277/preview.jpg"
site = "rule34video.com"
desc = ""
