id = "1480057610878193675"
name = "Ye Shunguang threesome"
archived = false
locked = false
createdAt = "2026-03-08T04:20:32.574Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480057610878193675"
author = "korieuko"
content = "https://rule34video.com/video/4276701/ye-shunguang-threesome/"
createdAt = "2026-03-08T04:20:32.574Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4276000/4276701/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4276701/ye-shunguang-threesome/"
title = "Ye Shunguang threesome"
image = "https://rule34video.com/contents/videos_screenshots/4276000/4276701/preview.jpg"
site = "rule34video.com"
desc = "nude+coom version on my patreon page"
