id = "1462032232053997609"
name = "Ye Shunguang Footjob"
archived = true
locked = false
createdAt = "2026-01-17T10:34:07.367Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1462032232053997609"
author = "korieuko"
content = "https://rule34video.com/video/4202313/ye-shunguang-footjob/"
createdAt = "2026-01-17T10:34:07.367Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4202000/4202313/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4202313/ye-shunguang-footjob/"
title = "Ye Shunguang Footjob"
image = "https://rule34video.com/contents/videos_screenshots/4202000/4202313/preview.jpg"
site = "rule34video.com"
desc = "&#34;Xiao'Guang? Pfft. She would be far too shy to cater to your peculiar desires~ Allow me...&#34;\n\nAnimation: Saucifer3D \nScript, Voice & Mix: LecheryAmoreVA \nMale Model: Dab_neko\nYe Shunguang Model: HairyHarzo\nSFX: @OpenNSFW"
