id = "1480057689513001181"
name = "Ye Shunguang [horizontalslope]"
archived = false
locked = false
createdAt = "2026-03-08T04:20:51.322Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480057689513001181"
author = "korieuko"
content = "https://rule34video.com/video/4275781/ye-shunguang-horizontalslope/"
createdAt = "2026-03-08T04:20:51.322Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4275000/4275781/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4275781/ye-shunguang-horizontalslope/"
title = "Ye Shunguang [horizontalslope]"
image = "https://rule34video.com/contents/videos_screenshots/4275000/4275781/preview.jpg"
site = "rule34video.com"
desc = ""
