id = "1480057796647977033"
name = "Ye Shunguang (Nude) [horizontalslope]"
archived = false
locked = false
createdAt = "2026-03-08T04:21:16.865Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480057796647977033"
author = "korieuko"
content = "https://rule34video.com/video/4275785/ye-shunguang-nude-horizontalslope/"
createdAt = "2026-03-08T04:21:16.865Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4275000/4275785/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4275785/ye-shunguang-nude-horizontalslope/"
title = "Ye Shunguang (Nude) [horizontalslope]"
image = "https://rule34video.com/contents/videos_screenshots/4275000/4275785/preview.jpg"
site = "rule34video.com"
desc = ""
