id = "1397136617940189194"
name = "Eula [vicineko]"
archived = true
locked = false
createdAt = "2025-07-22T08:42:07.260Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1397136617940189194"
author = "korieuko"
content = "https://rule34video.com/video/3062613/eula-vicineko/"
createdAt = "2025-07-22T08:42:07.260Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3062000/3062613/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3062613/eula-vicineko/"
title = "Eula [vicineko]"
image = "https://rule34video.com/contents/videos_screenshots/3062000/3062613/preview.jpg"
site = "rule34video.com"
desc = "Genshin Impact Parody"
