id = "1430575916345462964"
name = "Eula [SeventyFive3D]"
archived = true
locked = false
createdAt = "2025-10-22T15:17:57.272Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1430575916345462964"
author = "korieuko"
content = "https://rule34video.com/video/4079359/eula-seventyfive3d/"
createdAt = "2025-10-22T15:17:57.272Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4079000/4079359/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4079359/eula-seventyfive3d/"
title = "Eula [SeventyFive3D]"
image = "https://rule34video.com/contents/videos_screenshots/4079000/4079359/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/SeventyFive3D/status/1972822785174237459"
