id = "1473713122861781186"
name = "Aether x Nefer [SFX]"
archived = false
locked = false
createdAt = "2026-02-18T16:09:48.756Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1473713122861781186"
author = "korieuko"
content = "https://rule34video.com/video/4250390/aether-x-nefer-sfx/"
createdAt = "2026-02-18T16:09:48.756Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4250000/4250390/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4250390/aether-x-nefer-sfx/"
title = "Aether x Nefer [SFX]"
image = "https://rule34video.com/contents/videos_screenshots/4250000/4250390/preview.jpg"
site = "rule34video.com"
desc = "This is a sound edit all credit goes to animator KekeAnimation"
