id = "1463024640313000007"
name = "Fantasy about Nefer"
archived = true
locked = false
createdAt = "2026-01-20T04:17:35.934Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1463024640313000007"
author = "korieuko"
content = "https://rule34video.com/video/4204473/fantasy-about-nefer2/"
createdAt = "2026-01-20T04:17:35.934Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4204000/4204473/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4204473/fantasy-about-nefer2/"
title = "Fantasy about Nefer"
image = "https://rule34video.com/contents/videos_screenshots/4204000/4204473/preview.jpg"
site = "rule34video.com"
desc = "Follow me: https://x.com/giddora34\nScenes koikatsu: http://patreon.com/GIDDORA"
