id = "1433839947730653365"
name = "Nefer segs [MGCPer]"
archived = true
locked = false
createdAt = "2025-10-31T15:28:02.997Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1433839947730653365"
author = "korieuko"
content = "https://rule34video.com/video/4098291/nefer-segs-mgcper/"
createdAt = "2025-10-31T15:28:02.997Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4098000/4098291/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4098291/nefer-segs-mgcper/"
title = "Nefer segs [MGCPer]"
image = "https://rule34video.com/contents/videos_screenshots/4098000/4098291/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/MGCPer/status/1983233755989872701\n\nTags: nefer (genshin impact)"
