id = "1461394417826005023"
name = "Nefer secret services [Lewdoanim0]"
archived = true
locked = false
createdAt = "2026-01-15T16:19:40.605Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1461394417826005023"
author = "korieuko"
content = "https://rule34video.com/video/4193863/nefer-secret-services-lewdoanim0/"
createdAt = "2026-01-15T16:19:40.605Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4193000/4193863/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4193863/nefer-secret-services-lewdoanim0/"
title = "Nefer secret services [Lewdoanim0]"
image = "https://rule34video.com/contents/videos_screenshots/4193000/4193863/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Lewdoanim0/status/2001067833577402849/mediaViewer?currentTweet=2001067833577402849&currentTweetUser=Lewdoanim0"
