id = "1474739121472929842"
name = "Secrets of Yelan and Nefer [DiositoRei]"
archived = false
locked = false
createdAt = "2026-02-21T12:06:45.887Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1474739121472929842"
author = "korieuko"
content = "https://rule34video.com/video/4252646/secrets-of-yelan-and-nefer-diositorei/"
createdAt = "2026-02-21T12:06:45.887Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4252000/4252646/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4252646/secrets-of-yelan-and-nefer-diositorei/"
title = "Secrets of Yelan and Nefer [DiositoRei]"
image = "https://rule34video.com/contents/videos_screenshots/4252000/4252646/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/DiositoRei/status/2014948783411581336\n\nnefer (genshin impact) tag when"
