id = "1472259518410002502"
name = "[chekibrek] Yelan"
archived = false
locked = false
createdAt = "2026-02-14T15:53:42.448Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1472259518410002502"
author = "korieuko"
content = "https://rule34video.com/video/4233410/chekibrek-yelan/"
createdAt = "2026-02-14T15:53:42.448Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4233000/4233410/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4233410/chekibrek-yelan/"
title = "[chekibrek] Yelan"
image = "https://rule34video.com/contents/videos_screenshots/4233000/4233410/preview.jpg"
site = "rule34video.com"
desc = ""
