id = "1314980184125870131"
name = "[Kizuma] Yelan – Full Animation!!"
archived = true
locked = false
createdAt = "2024-12-07T15:41:47.046Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314980184125870131"
author = "korieuko"
content = "https://avbebe.com/archives/188948"
createdAt = "2024-12-07T15:41:47.046Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2023/12/Kizuma-Yelan-Full-Animation.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/188948"
title = "[Kizuma] Yelan – Full Animation!!"
image = "https://avbebe.com/wp-content/uploads/2023/12/Kizuma-Yelan-Full-Animation.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "#1 #2 《原神》夜蘭 《原神》夜蘭"
