id = "1389230130886610954"
name = "[Kusotaro] Yelan fucked while Sleep [English]"
archived = true
locked = false
createdAt = "2025-06-30T13:04:33.851Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389230130886610954"
author = "korieuko"
content = "https://rule34video.com/video/3904841/kusotaro-yelan-fucked-while-sleep-english/"
createdAt = "2025-06-30T13:04:33.851Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3904000/3904841/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3904841/kusotaro-yelan-fucked-while-sleep-english/"
title = "[Kusotaro] Yelan fucked while Sleep [English]"
image = "https://rule34video.com/contents/videos_screenshots/3904000/3904841/preview.jpg"
site = "rule34video.com"
desc = "I still don't know Japanese...\n\nartist: https://bouncingtits.fanbox.cc/"
