id = "1391321840642687116"
name = "A Ganbang Crossover with Hilichurls [AssDepik]"
archived = true
locked = false
createdAt = "2025-07-06T07:36:16.319Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391321840642687116"
author = "korieuko"
content = "https://rule34video.com/video/3324229/a-ganbang-crossover-with-hilichurls-assdepik/"
createdAt = "2025-07-06T07:36:16.319Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3324000/3324229/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3324229/a-ganbang-crossover-with-hilichurls-assdepik/"
title = "A Ganbang Crossover with Hilichurls [AssDepik]"
image = "https://rule34video.com/contents/videos_screenshots/3324000/3324229/preview.jpg"
site = "rule34video.com"
desc = ""
