id = "1314890012072087593"
name = "Yelan getting fucked roughly"
archived = true
locked = false
createdAt = "2024-12-07T09:43:28.353Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314890012072087593"
author = "korieuko"
content = "https://rule34video.com/video/3534921/yelan-genshin-impact-getting-fucked-roughly/"
createdAt = "2024-12-07T09:43:28.353Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3534000/3534921/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3534921/yelan-genshin-impact-getting-fucked-roughly/"
title = "Yelan (Genshin impact) getting fucked roughly"
image = "https://rule34video.com/contents/videos_screenshots/3534000/3534921/preview.jpg"
site = "rule34video.com"
desc = ""
