id = "1314892033063780373"
name = "Yelan NSFW"
archived = true
locked = false
createdAt = "2024-12-07T09:51:30.195Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314892033063780373"
author = "korieuko"
content = "https://www.pixiv.net/en/artworks/120351900#manga"
createdAt = "2024-12-07T09:51:30.195Z"
pinned = false
attachments = ""
thumbnail = "https://s.pximg.net/www/images/pixiv_logo.png"

[[messages.linkPreviews]]
url = "https://www.pixiv.net/en/artworks/120351900"
title = "[R-18]Yelan"
image = "https://s.pximg.net/www/images/pixiv_logo.png"
site = "pixiv"
desc = "Additional Illusts\n   Patreon: https://www.patreon.com/IULOW\nFANZA様で同人誌予約受付中です！\nhttps://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_391125/\nX: https://x.com/xaiuEROu"
