id = "1391321756622393435"
name = "Yelan Animation (Full) [AssDepik]"
archived = true
locked = false
createdAt = "2025-07-06T07:35:56.287Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391321756622393435"
author = "korieuko"
content = "https://rule34video.com/video/3698477/yelan-animation-full-assdepik/"
createdAt = "2025-07-06T07:35:56.287Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3698000/3698477/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3698477/yelan-animation-full-assdepik/"
title = "Yelan Animation (Full) [AssDepik]"
image = "https://rule34video.com/contents/videos_screenshots/3698000/3698477/preview.jpg"
site = "rule34video.com"
desc = "Artist: AssDepik\n\nYelan VA: @chiyo1000nights\nSound: @OpenNSFWSP\nModels: @DaB_neko"
