id = "1423658321705046138"
name = "Yelan VS Hilichurls"
archived = true
locked = false
createdAt = "2025-10-03T13:09:54.187Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1423658321705046138"
author = "korieuko"
content = "https://rule34video.com/video/4055994/yelan-vs-hilichurls/"
createdAt = "2025-10-03T13:09:54.187Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4055000/4055994/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4055994/yelan-vs-hilichurls/"
title = "Yelan VS Hilichurls"
image = "https://rule34video.com/contents/videos_screenshots/4055000/4055994/preview.jpg"
site = "rule34video.com"
desc = "Male sound"
