id = "1394118825640726569"
name = "Yelan [AssDepik]"
archived = true
locked = false
createdAt = "2025-07-14T00:50:29.508Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394118825640726569"
author = "korieuko"
content = "https://rule34video.com/video/3927797/yelan-assdepik/"
createdAt = "2025-07-14T00:50:29.508Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3927000/3927797/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3927797/yelan-assdepik/"
title = "Yelan [AssDepik]"
image = "https://rule34video.com/contents/videos_screenshots/3927000/3927797/preview.jpg"
site = "rule34video.com"
desc = ""
