id = "1365216027662880838"
name = "Yelan [Kizumashiro]"
archived = true
locked = false
createdAt = "2025-04-25T06:41:05.482Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1365216027662880838"
author = "korieuko"
content = "https://rule34video.com/video/3151974/yelan-kizumashiro/"
createdAt = "2025-04-25T06:41:05.482Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3151000/3151974/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3151974/yelan-kizumashiro/"
title = "Yelan [Kizumashiro]"
image = "https://rule34video.com/contents/videos_screenshots/3151000/3151974/preview.jpg"
site = "rule34video.com"
desc = ""
