id = "1389230957667684432"
name = "Yelan, Hilichurl"
archived = true
locked = false
createdAt = "2025-06-30T13:07:50.971Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389230957667684432"
author = "korieuko"
content = "https://rule34video.com/video/3101962/yelan-hilichurl/"
createdAt = "2025-06-30T13:07:50.971Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3101000/3101962/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3101962/yelan-hilichurl/"
title = "Yelan, Hilichurl"
image = "https://rule34video.com/contents/videos_screenshots/3101000/3101962/preview.jpg"
site = "rule34video.com"
desc = "final release,hope you like it\nFollow me on twitter ! @AssDepik_"
