id = "1382977984276992110"
name = "Yelan sex [Full] (by SeventyFive3D)"
archived = true
locked = false
createdAt = "2025-06-13T07:00:45.940Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382977984276992110"
author = "korieuko"
content = "https://rule34video.com/video/3881157/yelan-sex-full-by-seventyfive3d/"
createdAt = "2025-06-13T07:00:45.940Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
