id = "1408114130669404172"
name = "[Sodeno19][4K] Skirk - Full Animation"
archived = true
locked = false
createdAt = "2025-08-21T15:42:50.247Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1408114130669404172"
author = "korieuko"
content = "https://rule34video.com/video/3987905/sodeno19-4k-skirk-full-animation/"
createdAt = "2025-08-21T15:42:50.247Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3987000/3987905/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3987905/sodeno19-4k-skirk-full-animation/"
title = "[Sodeno19][4K] Skirk - Full Animation"
image = "https://rule34video.com/contents/videos_screenshots/3987000/3987905/preview.jpg"
site = "rule34video.com"
desc = "https://twitter.com/sodeno191\n\nhttps://www.patreon.com/sodeno19\n\nhttps://subscribestar.adult/sodeno19"
