id = "1391324334659993680"
name = "Shirk x Futa Changli and Futa Cantarella | Crossover"
archived = true
locked = false
createdAt = "2025-07-06T07:46:10.939Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391324334659993680"
author = "korieuko"
content = "https://rule34video.com/video/3917885/shirk-x-futa-changli-and-futa-cantarella-crossover/"
createdAt = "2025-07-06T07:46:10.939Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3917000/3917885/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3917885/shirk-x-futa-changli-and-futa-cantarella-crossover/"
title = "Shirk x Futa Changli and Futa Cantarella | Crossover"
image = "https://rule34video.com/contents/videos_screenshots/3917000/3917885/preview.jpg"
site = "rule34video.com"
desc = "Artists:R A V I E L(@asta_99)"
