id = "1442537339762118759"
name = "Skirk boobjob"
archived = true
locked = false
createdAt = "2025-11-24T15:28:22.847Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442537339762118759"
author = "korieuko"
content = "https://rule34video.com/video/4119158/skirk-boobjob/"
createdAt = "2025-11-24T15:28:22.847Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4119000/4119158/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4119158/skirk-boobjob/"
title = "Skirk boobjob"
image = "https://rule34video.com/contents/videos_screenshots/4119000/4119158/preview.jpg"
site = "rule34video.com"
desc = ""
