id = "1372130073179848755"
name = "Skirk's Lessons"
archived = true
locked = false
createdAt = "2025-05-14T08:35:02.390Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1372130073179848755"
author = "korieuko"
content = "https://iporntv.net/download/83620959/xvideos"
createdAt = "2025-05-14T08:35:02.390Z"
pinned = false
attachments = ""
thumbnail = "https://cdn.iporntv.net/videos/thumbs169lll/96/f7/55/96f755f42b7239bc8becdba77c41b732/96f755f42b7239bc8becdba77c41b732.3.jpg"

[[messages.linkPreviews]]
url = "https://iporntv.net/download/83620959/xvideos"
title = "Skirk's lessons"
image = "https://cdn.iporntv.net/videos/thumbs169lll/96/f7/55/96f755f42b7239bc8becdba77c41b732/96f755f42b7239bc8becdba77c41b732.3.jpg"
site = "iporntv.net"
desc = "Watch free Skirk's lessons xxx mobile porn videos and download them right on your Smartphone, Tablet or Desktop. iPorntv - The Porn Tv for you!"
