id = "1397249344549290004"
name = "Skirk2"
archived = true
locked = false
createdAt = "2025-07-22T16:10:03.378Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1397249344549290004"
author = "korieuko"
content = "https://rule34video.com/video/3943753/skirk2/"
createdAt = "2025-07-22T16:10:03.378Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3943000/3943753/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3943753/skirk2/"
title = "Skirk"
image = "https://rule34video.com/contents/videos_screenshots/3943000/3943753/preview.jpg"
site = "rule34video.com"
desc = "https://www.iwara.tv/profile/stpotato2000/"

[[messages]]
id = "1411580176160002081"
author = "korieuko"
content = "good"
createdAt = "2025-08-31T05:15:39.888Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
