id = "1314900250670137385"
name = "[トプ]コロンビーナ Live 2D (2"
archived = true
locked = false
createdAt = "2024-12-07T10:24:09.425Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314900250670137385"
author = "korieuko"
content = "https://avbebe.com/archives/197979"
createdAt = "2024-12-07T10:24:09.425Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/01/%E3%82%B3%E3%83%AD%E3%83%B3%E3%83%93%E3%83%BC%E3%83%8A-Live-2D-2.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/197979"
title = "[トプ]コロンビーナ Live 2D (2)"
image = "https://avbebe.com/wp-content/uploads/2024/01/%E3%82%B3%E3%83%AD%E3%83%B3%E3%83%93%E3%83%BC%E3%83%8A-Live-2D-2.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "虎克 虎克 哥倫比婭 哥倫比婭 哥伦比娅"
