id = "1472260160985628785"
name = "Columbina x Vishap [BurryFuzz]"
archived = false
locked = false
createdAt = "2026-02-14T15:56:15.650Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1472260160985628785"
author = "korieuko"
content = "https://rule34video.com/video/4238406/columbina-x-vishap-burryfuzz/"
createdAt = "2026-02-14T15:56:15.650Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4238000/4238406/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4238406/columbina-x-vishap-burryfuzz/"
title = "Columbina x Vishap [BurryFuzz]"
image = "https://rule34video.com/contents/videos_screenshots/4238000/4238406/preview.jpg"
site = "rule34video.com"
desc = "Created by\nsubscribestar.adult/burryfuzz\nx.com/BFuzzR18"
