id = "1468939539711262832"
name = "Bad Students Lynae (Sound Version) - Lazyrice3D"
archived = true
locked = false
createdAt = "2026-02-05T12:01:17.844Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468939539711262832"
author = "korieuko"
content = "https://rule34video.com/video/4227954/bad-students-lynae-sound-version-lazyrice3d/"
createdAt = "2026-02-05T12:01:17.844Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4227000/4227954/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4227954/bad-students-lynae-sound-version-lazyrice3d/"
title = "Bad Students Lynae (Sound Version) - Lazyrice3D"
image = "https://rule34video.com/contents/videos_screenshots/4227000/4227954/preview.jpg"
site = "rule34video.com"
desc = ""
