id = "1477671591532957868"
name = "Lynae [Neneg]"
archived = false
locked = false
createdAt = "2026-03-01T14:19:21.232Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1477671591532957868"
author = "korieuko"
content = "https://rule34video.com/video/4263686/lynae-neneg/"
createdAt = "2026-03-01T14:19:21.232Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4263000/4263686/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4263686/lynae-neneg/"
title = "Lynae [Neneg]"
image = "https://rule34video.com/contents/videos_screenshots/4263000/4263686/preview.jpg"
site = "rule34video.com"
desc = "https://neneg.fanbox.cc/posts — official author page \nArtist: https://twitter.com/real_haku89\nVA: https://twitter.com/mskmiro316\n\nPosting only high quality content."
