id = "1476247741318561866"
name = "Lynae Throat Training"
archived = false
locked = false
createdAt = "2026-02-25T16:01:28.887Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1476247741318561866"
author = "korieuko"
content = "https://rule34video.com/video/4260150/lynae-throat-training/"
createdAt = "2026-02-25T16:01:28.887Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4260000/4260150/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4260150/lynae-throat-training/"
title = "Lynae Throat Training"
image = "https://rule34video.com/contents/videos_screenshots/4260000/4260150/preview.jpg"
site = "rule34video.com"
desc = "Twitter - @DUALBLADESS\nSupport my works & stuff: https://dualbladess.carrd.co/"
