id = "1455485606435229766"
name = "RDreamer Lynae FULL"
archived = true
locked = false
createdAt = "2025-12-30T09:00:10.189Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1455485606435229766"
author = "korieuko"
content = "https://rule34video.com/video/4174667/rdreamer-lynae-full/"
createdAt = "2025-12-30T09:00:10.189Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4174000/4174667/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4174667/rdreamer-lynae-full/"
title = "RDreamer Lynae FULL"
image = "https://rule34video.com/contents/videos_screenshots/4174000/4174667/preview.jpg"
site = "rule34video.com"
desc = ""
