id = "1448553728167903323"
name = "Zhu yuan (Lazyprocrastinator)"
archived = true
locked = false
createdAt = "2025-12-11T05:55:21.622Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1448553728167903323"
author = "korieuko"
content = "https://rule34video.com/video/4144683/zhu-yuan-lazyprocrastinator/"
createdAt = "2025-12-11T05:55:21.622Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4144000/4144683/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4144683/zhu-yuan-lazyprocrastinator/"
title = "Zhu yuan (Lazyprocrastinator)"
image = "https://rule34video.com/contents/videos_screenshots/4144000/4144683/preview.jpg"
site = "rule34video.com"
desc = ""
