id = "1314891204638408775"
name = "Camellya x ray"
archived = true
locked = false
createdAt = "2024-12-07T09:48:12.683Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1314891204638408775"
author = "korieuko"
content = "https://rule34video.com/video/3570789/camellya-x-ray-aung15/"
createdAt = "2024-12-07T09:48:12.683Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3570000/3570789/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3570789/camellya-x-ray-aung15/"
title = "Camellya (X-ray) [Aung15]"
image = "https://rule34video.com/contents/videos_screenshots/3570000/3570789/preview.jpg"
site = "rule34video.com"
desc = ""

[[messages]]
id = "1314891261995520072"
author = "korieuko"
content = "Camellya x ray"
createdAt = "2024-12-07T09:48:26.358Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
