id = "1314846935336882176"
name = "Yuluer [Camellya]"
archived = true
locked = false
createdAt = "2024-12-07T06:52:18.059Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314846935336882176"
author = "korieuko"
content = "https://avbebe.com/archives/267222"
createdAt = "2024-12-07T06:52:18.059Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/12/Yuluer-%E6%A4%BF%E9%B3%B4%E6%BD%AE.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/267222"
title = "[Yuluer] ツバキ"
image = "https://avbebe.com/wp-content/uploads/2024/12/Yuluer-%E6%A4%BF%E9%B3%B4%E6%BD%AE.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
