id = "1375453726785015970"
name = "Keqing [delightss]"
archived = true
locked = false
createdAt = "2025-05-23T12:42:03.160Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375453726785015970"
author = "korieuko"
content = "https://rule34video.com/video/3550919/keqing-thighjob-delightss/"
createdAt = "2025-05-23T12:42:03.160Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3550000/3550919/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3550919/keqing-thighjob-delightss/"
title = "Keqing [delightss]"
image = "https://rule34video.com/contents/videos_screenshots/3550000/3550919/preview.jpg"
site = "rule34video.com"
desc = "https://www.patreon.com/delightss\n\nhttps://x.com/delights2s\n\nhttps://www.pixiv.net/en/users/99694713\n\nSupport the original creators!"
