id = "1394118223007449088"
name = "Keqing x mitachurl"
archived = true
locked = false
createdAt = "2025-07-14T00:48:05.829Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394118223007449088"
author = "korieuko"
content = "https://rule34video.com/video/3929129/keqing-x-mitachurl/"
createdAt = "2025-07-14T00:48:05.829Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3929000/3929129/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3929129/keqing-x-mitachurl/"
title = "Keqing x mitachurl"
image = "https://rule34video.com/contents/videos_screenshots/3929000/3929129/preview.jpg"
site = "rule34video.com"
desc = ""
