id = "1382976426877386762"
name = "[4K] Xilonen BJ Bang [Bubukuin]"
archived = true
locked = false
createdAt = "2025-06-13T06:54:34.627Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1382976426877386762"
author = "korieuko"
content = "https://rule34video.com/video/3794149/4k-xilonen-bj-bang-bubukuin/"
createdAt = "2025-06-13T06:54:34.627Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3794000/3794149/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3794149/4k-xilonen-bj-bang-bubukuin/"
title = "[4K] Xilonen BJ Bang [Bubukuin]"
image = "https://rule34video.com/contents/videos_screenshots/3794000/3794149/preview.jpg"
site = "rule34video.com"
desc = ""

[[messages]]
id = "1411580420193259543"
author = "korieuko"
content = "good"
createdAt = "2025-08-31T05:16:38.070Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
