id = "1468231173942673693"
name = "Genshin Impact Yummy Xilonen 4K"
archived = true
locked = false
createdAt = "2026-02-03T13:06:30.284Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468231173942673693"
author = "korieuko"
content = "https://rule34video.com/video/4217862/genshin-impact-yummy-xilonen-4k/"
createdAt = "2026-02-03T13:06:30.284Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4217000/4217862/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4217862/genshin-impact-yummy-xilonen-4k/"
title = "Genshin Impact Yummy Xilonen 4K"
image = "https://rule34video.com/contents/videos_screenshots/4217000/4217862/preview.jpg"
site = "rule34video.com"
desc = "Xilonen rewards Aether with anything he wishes for after performing mouth to mouth resuscitation on her. The two are more than just life savers and friends. Xilonen and Aether fall in love with each other instantly, have some alone time in a private place, and fulfill their desires."
