id = "1382976724261928981"
name = "Xilonen x Futa Dehya"
archived = true
locked = false
createdAt = "2025-06-13T06:55:45.529Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382976724261928981"
author = "korieuko"
content = "https://rule34video.com/video/3657179/xilonen-x-futa-dehya/"
createdAt = "2025-06-13T06:55:45.529Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3657000/3657179/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3657179/xilonen-x-futa-dehya/"
title = "Xilonen x Futa Dehya"
image = "https://rule34video.com/contents/videos_screenshots/3657000/3657179/preview.jpg"
site = "rule34video.com"
desc = ""
