id = "1406598276085583892"
name = "Xilonen Crossed Legs (sound update)"
archived = true
locked = false
createdAt = "2025-08-17T11:19:22.351Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406598276085583892"
author = "korieuko"
content = "https://rule34video.com/video/3977902/xilonen-crossed-legs-sound-update/"
createdAt = "2025-08-17T11:19:22.351Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3977000/3977902/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3977902/xilonen-crossed-legs-sound-update/"
title = "Xilonen Crossed Legs (sound update)"
image = "https://rule34video.com/contents/videos_screenshots/3977000/3977902/preview.jpg"
site = "rule34video.com"
desc = "I did the audio mixing"
