id = "1382976588689313934"
name = "Xilonen [Lewdoanim]"
archived = true
locked = false
createdAt = "2025-06-13T06:55:13.206Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1382976588689313934"
author = "korieuko"
content = "https://rule34video.com/video/3665255/xilonen-lewdoanim/"
createdAt = "2025-06-13T06:55:13.206Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3665000/3665255/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3665255/xilonen-lewdoanim/"
title = "Xilonen [Lewdoanim]"
image = "https://rule34video.com/contents/videos_screenshots/3665000/3665255/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/Lewdoanim\nx.com/Lewdoanim0\n\nVA: hoshinomeririri"

[[messages]]
id = "1411580437167345708"
author = "korieuko"
content = "good"
createdAt = "2025-08-31T05:16:42.117Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
