id = "1421381959484969041"
name = "Xilonen"
archived = true
locked = false
createdAt = "2025-09-27T06:24:27.141Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1421381959484969041"
author = "korieuko"
content = "https://rule34video.com/video/4043390/xilonen2/"
createdAt = "2025-09-27T06:24:27.141Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4043000/4043390/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4043390/xilonen2/"
title = "Xilonen"
image = "https://rule34video.com/contents/videos_screenshots/4043000/4043390/preview.jpg"
site = "rule34video.com"
desc = ""
