id = "1369524870752370709"
name = "[4K] Ganyu's Daily Milk [Mellewd]"
archived = true
locked = false
createdAt = "2025-05-07T04:02:53.729Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1369524870752370709"
author = "korieuko"
content = "https://rule34video.com/video/3114172/4k-ganyu-s-daily-milk-mellewd/"
createdAt = "2025-05-07T04:02:53.729Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3114000/3114172/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3114172/4k-ganyu-s-daily-milk-mellewd/"
title = "[4K] Ganyu's Daily Milk [Mellewd]"
image = "https://rule34video.com/contents/videos_screenshots/3114000/3114172/preview.jpg"
site = "rule34video.com"
desc = "https://twitter.com/mellewd_\nhttps://www.patreon.com/Mellewd"
