id = "1446528236568842260"
name = "Ganyu riding [Hook_001]"
archived = true
locked = false
createdAt = "2025-12-05T15:46:46.793Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1446528236568842260"
author = "korieuko"
content = "https://rule34video.com/video/4134811/ganyu-riding-hook-001/"
createdAt = "2025-12-05T15:46:46.793Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4134000/4134811/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4134811/ganyu-riding-hook-001/"
title = "Ganyu riding [Hook_001]"
image = "https://rule34video.com/contents/videos_screenshots/4134000/4134811/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Hook_001/status/198516439131530903\n\nArtist is: Hook_001"
