id = "1461353066648567999"
name = "Ganyu Churld [Lunove]"
archived = true
locked = false
createdAt = "2026-01-15T13:35:21.716Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1461353066648567999"
author = "korieuko"
content = "https://rule34video.com/video/4193983/ganyu-churld-lunove/"
createdAt = "2026-01-15T13:35:21.716Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4193000/4193983/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4193983/ganyu-churld-lunove/"
title = "Ganyu Churld [Lunove]"
image = "https://rule34video.com/contents/videos_screenshots/4193000/4193983/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Lunove3D/status/1948326039689495010"
