id = "1314846650233258077"
name = "Wuthering waves[NSFW]"
guildId = "1314839006717935696"
guildName = "Invrs ✦ NSFW"
backedUpAt = "2026-03-08T13:16:06.560Z"
contents = ["forum: forum-camellya", "forum: forum-zhezhi", "forum: forum-yinlin", "forum: forum-shorekeeper", "forum: forum-changli", "forum: forum-jinshi", "forum: forum-zani", "forum: forum-phoebe", "forum: forum-carlotta", "forum: forum-cantarella", "forum: forum-phrolova", "forum: forum-cart-fleur", "forum: forum-ciaccona", "forum: forum-luno", "forum: forum-augusta", "forum: forum-lupa", "forum: forum-frover", "forum: forum-sanhua", "forum: forum-galbrena", "forum: forum-chisa", "forum: forum-lynae", "forum: forum-moryne", "forum: forum-aemeath"]

[stats]
totalForums = 23
totalChannels = 0
totalThreads = 258
totalMessages = 265
