id = "1375501163658608700"
name = "【CN SUB】2024.12 The Herta"
archived = true
locked = false
createdAt = "2025-05-23T15:50:32.992Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375501163658608700"
author = "korieuko"
content = "https://rule34video.com/video/3848857/cn-sub-2024-12-the-herta/"
createdAt = "2025-05-23T15:50:32.992Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3848000/3848857/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3848857/cn-sub-2024-12-the-herta/"
title = "【CN SUB】2024.12 The Herta"
image = "https://rule34video.com/contents/videos_screenshots/3848000/3848857/preview.jpg"
site = "rule34video.com"
desc = ""
