id = "1322517804083318795"
name = "[Sex only]TheHerta#1"
archived = true
locked = false
createdAt = "2024-12-28T10:53:35.686Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1322517804083318795"
author = "korieuko"
content = "https://rule34video.com/video/3635120/sex-only-theherta-1/"
createdAt = "2024-12-28T10:53:35.686Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3635000/3635120/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3635120/sex-only-theherta-1/"
title = "[Sex only]TheHerta#1"
image = "https://rule34video.com/contents/videos_screenshots/3635000/3635120/preview.jpg"
site = "rule34video.com"
desc = "大黑塔#1"
