id = "1382977007142567986"
name = "Apologies from The Herta"
archived = true
locked = false
createdAt = "2025-06-13T06:56:52.973Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382977007142567986"
author = "korieuko"
content = "https://rule34video.com/video/3716213/apologies-from-the-herta/"
createdAt = "2025-06-13T06:56:52.973Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3716000/3716213/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3716213/apologies-from-the-herta/"
title = "Apologies from The Herta"
image = "https://rule34video.com/contents/videos_screenshots/3716000/3716213/preview.jpg"
site = "rule34video.com"
desc = ""
