id = "1430576327504691231"
name = "Herta [Potato2000]"
archived = true
locked = false
createdAt = "2025-10-22T15:19:35.300Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1430576327504691231"
author = "korieuko"
content = "https://rule34video.com/video/4067126/herta-potato2000/"
createdAt = "2025-10-22T15:19:35.300Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4067000/4067126/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4067126/herta-potato2000/"
title = "Herta [Potato2000]"
image = "https://rule34video.com/contents/videos_screenshots/4067000/4067126/preview.jpg"
site = "rule34video.com"
desc = ""
