id = "1452858527566790718"
name = "Herta shares her genius skills"
archived = true
locked = false
createdAt = "2025-12-23T03:01:05.778Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1452858527566790718"
author = "korieuko"
content = "https://rule34video.com/video/4157964/herta-shares-her-genius-skills/"
createdAt = "2025-12-23T03:01:05.778Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4157000/4157964/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4157964/herta-shares-her-genius-skills/"
title = "Herta shares her genius skills"
image = "https://rule34video.com/contents/videos_screenshots/4157000/4157964/preview.jpg"
site = "rule34video.com"
desc = "Animation: x.com/Mellewd3D\npatreon.com/Mellewd\nhttp://mellewd.fanbox.cc\n\nVA&SFX: x.com/SquishSuccubus"
