id = "1408114010594869520"
name = "The Herta [Umler]"
archived = true
locked = false
createdAt = "2025-08-21T15:42:21.619Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1408114010594869520"
author = "korieuko"
content = "https://rule34video.com/video/3984017/the-herta-umler/"
createdAt = "2025-08-21T15:42:21.619Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
