id = "1396158034169954424"
name = "The Herta and Caelus"
archived = true
locked = false
createdAt = "2025-07-19T15:53:34.708Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1396158034169954424"
author = "korieuko"
content = "https://rule34video.com/video/3915501/the-herta-and-caelus/"
createdAt = "2025-07-19T15:53:34.708Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3915000/3915501/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3915501/the-herta-and-caelus/"
title = "The Herta and Caelus"
image = "https://rule34video.com/contents/videos_screenshots/3915000/3915501/preview.jpg"
site = "rule34video.com"
desc = ""
