id = "1383830302580805683"
name = "The Herta gangbang [kiramekuhoshi]"
archived = true
locked = false
createdAt = "2025-06-15T15:27:34.459Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1383830302580805683"
author = "korieuko"
content = "https://rule34video.com/video/3768201/the-herta-gangbang-kiramekuhoshi/"
createdAt = "2025-06-15T15:27:34.459Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3768000/3768201/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3768201/the-herta-gangbang-kiramekuhoshi/"
title = "The Herta gangbang [kiramekuhoshi]"
image = "https://rule34video.com/contents/videos_screenshots/3768000/3768201/preview.jpg"
site = "rule34video.com"
desc = "artist : kiramekuhoshi"
