id = "1361158851902308525"
name = "The Herta - Missionary [Rinjo18]"
archived = true
locked = false
createdAt = "2025-04-14T01:59:19.402Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1361158851902308525"
author = "korieuko"
content = "https://rule34video.com/video/3783389/the-herta-missionary-rinjo18/"
createdAt = "2025-04-14T01:59:19.402Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3783000/3783389/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3783389/the-herta-missionary-rinjo18/"
title = "The Herta - Missionary [Rinjo18]"
image = "https://rule34video.com/contents/videos_screenshots/3783000/3783389/preview.jpg"
site = "rule34video.com"
desc = "Artist:https://www.patreon.com/rinjo_18\nVA, (@SquishSuccubus)"
