id = "1449081788541436085"
name = "The Herta: 'Hi!, Cum for a Test~'"
archived = true
locked = false
createdAt = "2025-12-12T16:53:41.026Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1449081788541436085"
author = "korieuko"
content = "https://rule34video.com/video/4150175/the-herta-hi-cum-for-a-test/"
createdAt = "2025-12-12T16:53:41.026Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4150000/4150175/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4150175/the-herta-hi-cum-for-a-test/"
title = "The Herta: 'Hi!, Cum for a Test~'"
image = "https://rule34video.com/contents/videos_screenshots/4150000/4150175/preview.jpg"
site = "rule34video.com"
desc = "[\n…so you rush into her office, locking the door behind you.\nShe’s rambling about some typo — but you’re far too busy stripping her bare.\n\n“I meant Come for a test, not Cum— ah!”\n\nFrom there, you make sure she’s thoroughly filled with the ‘test results’ she asked for…\n…maybe even overflowing~\n]\n\nSupport me on:\npatreon.com..."
