id = "1396158112313901208"
name = "The Herta (fufuNSFW)"
archived = true
locked = false
createdAt = "2025-07-19T15:53:53.339Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1396158112313901208"
author = "korieuko"
content = "https://rule34video.com/video/3846357/the-herta-fufunsfw2/"
createdAt = "2025-07-19T15:53:53.339Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3846000/3846357/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3846357/the-herta-fufunsfw2/"
title = "The Herta (fufuNSFW)"
image = "https://rule34video.com/contents/videos_screenshots/3846000/3846357/preview.jpg"
site = "rule34video.com"
desc = "Animation by fufuNSFW\nhttps://x.com/fufunsfw"
