id = "1414584034423476407"
name = "Galbrena_Wuthering waves [6aminoac9]"
archived = true
locked = false
createdAt = "2025-09-08T12:11:55.507Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1414584034423476407"
author = "korieuko"
content = "https://rule34video.com/video/4016781/galbrena-wuthering-waves-6aminoac9/"
createdAt = "2025-09-08T12:11:55.507Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4016000/4016781/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4016781/galbrena-wuthering-waves-6aminoac9/"
title = "Galbrena_Wuthering waves [6aminoac9]"
image = "https://rule34video.com/contents/videos_screenshots/4016000/4016781/preview.jpg"
site = "rule34video.com"
desc = "Galbrena_Wuthering waves [6aminoac9]\n\n:||"
