id = "1324694297257185310"
name = "002【Genshin Impact】mavuika"
archived = true
locked = false
createdAt = "2025-01-03T11:02:12.096Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1324694297257185310"
author = "korieuko"
content = "https://rule34video.com/video/3514074/002-genshin-impact-mavuika-sex-sounded/"
createdAt = "2025-01-03T11:02:12.096Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3514000/3514074/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3514074/002-genshin-impact-mavuika-sex-sounded/"
title = "002【Genshin Impact】mavuika sex[sounded]"
image = "https://rule34video.com/contents/videos_screenshots/3514000/3514074/preview.jpg"
site = "rule34video.com"
desc = "Scene by hongcha\nThis video made by Acidrain\nWorks: https://www.iwara.tv/profile/nikonikoni002\nSupport creator: https://acidrain002.fanbox.cc/"

[[messages]]
id = "1375457597154656288"
author = "korieuko"
content = "Good"
createdAt = "2025-05-23T12:57:25.928Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
