id = "1324693710117802055"
name = "006【Genshin Impact】mavuika sex-2 [音声付]"
archived = true
locked = false
createdAt = "2025-01-03T10:59:52.111Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1324693710117802055"
author = "korieuko"
content = "https://rule34video.com/video/3515277/006-genshin-impact-mavuika-sex-2/"
createdAt = "2025-01-03T10:59:52.111Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3515000/3515277/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3515277/006-genshin-impact-mavuika-sex-2/"
title = "006【Genshin Impact】mavuika sex-2 [音声付]"
image = "https://rule34video.com/contents/videos_screenshots/3515000/3515277/preview.jpg"
site = "rule34video.com"
desc = "Scene by hongcha\nThis video made by Acidrain\nWorks: https://www.iwara.tv/profile/nikonikoni002\nSupport creator: https://acidrain002.fanbox.cc/"

[[messages]]
id = "1375456705160282184"
author = "korieuko"
content = "Hella good"
createdAt = "2025-05-23T12:53:53.260Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
