id = "1326887332720148532"
name = "(No music)Mavuika sex ritual (Lynlynop)"
archived = true
locked = false
createdAt = "2025-01-09T12:16:32.495Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1326887332720148532"
author = "korieuko"
content = "https://rule34video.com/video/3648959/no-music-mavuika-sex-ritual-lynlynop/"
createdAt = "2025-01-09T12:16:32.495Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3648000/3648959/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3648959/no-music-mavuika-sex-ritual-lynlynop/"
title = "(No music)Mavuika sex ritual (Lynlynop)"
image = "https://rule34video.com/contents/videos_screenshots/3648000/3648959/preview.jpg"
site = "rule34video.com"
desc = ""
