id = "1365215930652688446"
name = "Hot Archon"
archived = true
locked = false
createdAt = "2025-04-25T06:40:42.353Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1365215930652688446"
author = "korieuko"
content = "https://rule34video.com/video/3806965/hot-archon/"
createdAt = "2025-04-25T06:40:42.353Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3806000/3806965/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3806965/hot-archon/"
title = "Hot Archon"
image = "https://rule34video.com/contents/videos_screenshots/3806000/3806965/preview.jpg"
site = "rule34video.com"
desc = "https://patreon.com/Kotero\n\nFollow me : https://twitter.com/KOTEERO"
