id = "1389230445580779710"
name = "Mauvika dominates Aether....but in a good way ( Dubbed )"
archived = true
locked = false
createdAt = "2025-06-30T13:05:48.880Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389230445580779710"
author = "korieuko"
content = "https://rule34video.com/video/3888489/mauvika-dominates-aether-but-in-a-good-way-dubbed/"
createdAt = "2025-06-30T13:05:48.880Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3888000/3888489/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3888489/mauvika-dominates-aether-but-in-a-good-way-dubbed/"
title = "Mauvika dominates Aether....but in a good way ( Dubbed )"
image = "https://rule34video.com/contents/videos_screenshots/3888000/3888489/preview.jpg"
site = "rule34video.com"
desc = "he can dominate me uhhh I mean Aether any time\n\nAnimation : \nTwiistedLewds\n \nMauvika VA : \nnsfw_sonia_va\n \nAether VA / SFX Edit : \nMephistoJonesVA\n \nSFX Packs : \nOpenNSFWSP"
