id = "1468227742855336109"
name = "Mavuika R18G (Tir_Al)"
archived = true
locked = false
createdAt = "2026-02-03T12:52:52.249Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1468227742855336109"
author = "korieuko"
content = "https://rule34video.com/video/4222974/mavuika-r18g-tir-al/"
createdAt = "2026-02-03T12:52:52.249Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4222000/4222974/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4222974/mavuika-r18g-tir-al/"
title = "Mavuika R18G (Tir_Al)"
image = "https://rule34video.com/contents/videos_screenshots/4222000/4222974/preview.jpg"
site = "rule34video.com"
desc = ""

[[messages]]
id = "1468231013099507829"
author = "korieuko"
content = "deed"
createdAt = "2026-02-03T13:05:51.936Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
