id = "1375456612524753007"
name = "Mavuika × Furina & Raiden Shogun"
archived = true
locked = false
createdAt = "2025-05-23T12:53:31.174Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375456612524753007"
author = "korieuko"
content = "https://rule34video.com/video/3848829/mavuika-furina-raiden-shogun/"
createdAt = "2025-05-23T12:53:31.174Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3848000/3848829/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3848829/mavuika-furina-raiden-shogun/"
title = "Mavuika × Furina & Raiden Shogun"
image = "https://rule34video.com/contents/videos_screenshots/3848000/3848829/preview.jpg"
site = "rule34video.com"
desc = ""
