id = "1317520725111734292"
name = "Mavuika × Raiden by ArcSX"
archived = true
locked = false
createdAt = "2024-12-14T15:56:59.218Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1317520725111734292"
author = "korieuko"
content = "https://rule34video.com/video/3600858/mavuika-raiden-by-arcsx/"
createdAt = "2024-12-14T15:56:59.218Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
