id = "1393203011072823388"
name = "Mavuika anal sex [Seventyfive]"
archived = true
locked = false
createdAt = "2025-07-11T12:11:22.300Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1393203011072823388"
author = "korieuko"
content = "https://rule34video.com/video/3927325/mavuika-anal-sex-seventyfive/"
createdAt = "2025-07-11T12:11:22.300Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3927000/3927325/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3927325/mavuika-anal-sex-seventyfive/"
title = "Mavuika anal sex [Seventyfive]"
image = "https://rule34video.com/contents/videos_screenshots/3927000/3927325/preview.jpg"
site = "rule34video.com"
desc = "Support for more videos like this https://www.patreon.com/c/SeventyFive"
