id = "1392891877585588247"
name = "Mavuika Cowgirl"
archived = true
locked = false
createdAt = "2025-07-10T15:35:02.296Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1392891877585588247"
author = "korieuko"
content = "https://rule34video.com/video/3923877/mavuika-cowgirl/"
createdAt = "2025-07-10T15:35:02.296Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3923000/3923877/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3923877/mavuika-cowgirl/"
title = "Mavuika Cowgirl"
image = "https://rule34video.com/contents/videos_screenshots/3923000/3923877/preview.jpg"
site = "rule34video.com"
desc = ""
