id = "1457732962266120243"
name = "Mualani!!"
archived = true
locked = false
createdAt = "2026-01-05T13:50:21.573Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1457732962266120243"
author = "korieuko"
content = "https://rule34video.com/video/4183776/mualani4/"
createdAt = "2026-01-05T13:50:21.573Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4183000/4183776/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4183776/mualani4/"
title = "Mualani!!"
image = "https://rule34video.com/contents/videos_screenshots/4183000/4183776/preview.jpg"
site = "rule34video.com"
desc = "Original render: 2025-05-24\n\nMualani and Traveler by DaB_neko\nEnvironment by KitsuneVixen\nSound by OpenNSFW\nVoice by KitsuneVixen (OpenNSFW)"
