id = "1411548558045351976"
name = "Mualani and Bennett having fun"
archived = true
locked = false
createdAt = "2025-08-31T03:10:01.542Z"
autoArchiveDuration = 4320
messageCount = 3
appliedTags = []

[[messages]]
id = "1411548558045351976"
author = "korieuko"
content = "https://rule34video.com/video/4001741/mualani-and-bennett-having-fun/"
createdAt = "2025-08-31T03:10:01.542Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4001000/4001741/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4001741/mualani-and-bennett-having-fun/"
title = "Mualani and Bennett having fun"
image = "https://rule34video.com/contents/videos_screenshots/4001000/4001741/preview.jpg"
site = "rule34video.com"
desc = ""

[[messages]]
id = "1411548691025756211"
author = "korieuko"
content = "good"
createdAt = "2025-08-31T03:10:33.247Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []

[[messages]]
id = "1411548758856171694"
author = "korieuko"
content = "smooth"
createdAt = "2025-08-31T03:10:49.419Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
