id = "1382975942091083776"
name = "Mualani Riding"
archived = true
locked = false
createdAt = "2025-06-13T06:52:39.045Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1382975942091083776"
author = "korieuko"
content = "https://rule34video.com/video/3877221/mualani-riding/"
createdAt = "2025-06-13T06:52:39.045Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3877000/3877221/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3877221/mualani-riding/"
title = "Mualani Riding"
image = "https://rule34video.com/contents/videos_screenshots/3877000/3877221/preview.jpg"
site = "rule34video.com"
desc = "Patreon: https://www.patreon.com/c/EcchiWaffle\n\nAnimation - TwiistedLewds\nMualani - Misuzugon\nAudio - EcchiWaffle"

[[messages]]
id = "1411548716065751185"
author = "korieuko"
content = "good"
createdAt = "2025-08-31T03:10:39.217Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
