id = "1381978945552912504"
name = "Ningguang genshin impactを視聴"
archived = true
locked = false
createdAt = "2025-06-10T12:50:56.547Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1381978945552912504"
author = "korieuko"
content = "https://jp.spankbang.com/86ehr/video/ningguang+genshin+impact"
createdAt = "2025-06-10T12:50:56.547Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
