id = "1388026288622800946"
name = "Ningguang quarters [CGPeach]"
archived = true
locked = false
createdAt = "2025-06-27T05:20:55.489Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388026288622800946"
author = "korieuko"
content = "https://rule34video.com/video/3794925/ningguang-quarters-cgpeach/"
createdAt = "2025-06-27T05:20:55.489Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3794000/3794925/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3794925/ningguang-quarters-cgpeach/"
title = "Ningguang quarters [CGPeach]"
image = "https://rule34video.com/contents/videos_screenshots/3794000/3794925/preview.jpg"
site = "rule34video.com"
desc = ""
