id = "1371468219927498762"
name = "070 Carlotta sex [sound] 【wuwa】"
archived = true
locked = false
createdAt = "2025-05-12T12:45:04.278Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371468219927498762"
author = "korieuko"
content = "https://rule34video.com/video/3646493/070-carlotta-sex-sound-wuwa/"
createdAt = "2025-05-12T12:45:04.278Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3646000/3646493/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3646493/070-carlotta-sex-sound-wuwa/"
title = "070 Carlotta  sex [sound] 【wuwa】"
image = "https://rule34video.com/contents/videos_screenshots/3646000/3646493/preview.jpg"
site = "rule34video.com"
desc = "Full version ( 10:35 ) here:\n\nhttps://www.fanbox.cc/@acidrain002/posts/9161642\n\nScene by hongcha & imsayaa34 & ToTheMoon & yurabe & yuukis & harada\nThis video made by Acidrain\nWorks: https://www.iwara.tv/profile/nikonikoni002\nMore & Longer videos & Support creator: https://acidrain002.fanbox.cc"
