id = "1412100959370481828"
name = "1st Animation: Carlotta Montelli - Splashing Summer"
archived = true
locked = false
createdAt = "2025-09-01T15:45:04.281Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1412100959370481828"
author = "korieuko"
content = "https://rule34video.com/video/4000757/1st-animation-carlotta-montelli-splashing-summer/"
createdAt = "2025-09-01T15:45:04.281Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4000000/4000757/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4000757/1st-animation-carlotta-montelli-splashing-summer/"
title = "1st Animation:  Carlotta Montelli - Splashing Summer"
image = "https://rule34video.com/contents/videos_screenshots/4000000/4000757/preview.jpg"
site = "rule34video.com"
desc = "Souce: https://x.com/Oblivionis_art/status/1959744766817821125\n\nCreator: Oblivionis_art (X)\nScene: Giddora34\nCard: Rurri"
