id = "1400836171889774592"
name = "[Aung15] Carlota"
archived = true
locked = false
createdAt = "2025-08-01T13:42:49.656Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1400836171889774592"
author = "korieuko"
content = "https://rule34video.com/video/3960142/aung15-carlota/"
createdAt = "2025-08-01T13:42:49.656Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3960000/3960142/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3960142/aung15-carlota/"
title = "[Aung15] Carlota"
image = "https://rule34video.com/contents/videos_screenshots/3960000/3960142/preview.jpg"
site = "rule34video.com"
desc = ""
