id = "1358005705180712970"
name = "■【Carlotta】0114．ClothedA Sound Ver"
archived = true
locked = false
createdAt = "2025-04-05T09:09:50.641Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1358005705180712970"
author = "korieuko"
content = "https://rule34video.com/video/3768441/carlotta-0114-clotheda-sound-ver/"
createdAt = "2025-04-05T09:09:50.641Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3768000/3768441/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3768441/carlotta-0114-clotheda-sound-ver/"
title = "■【Carlotta】0114．ClothedA Sound Ver"
image = "https://rule34video.com/contents/videos_screenshots/3768000/3768441/preview.jpg"
site = "rule34video.com"
desc = "■【珂莱塔】0114．着衣A Sound Ver"
