id = "1397785959243976724"
name = "柯莱塔 carlotta NTR 02"
archived = true
locked = false
createdAt = "2025-07-24T03:42:22.291Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1397785959243976724"
author = "korieuko"
content = "https://www.iwara.tv/video/97vx62KKEx9a5D/carlotta-ntr-02"
createdAt = "2025-07-24T03:42:22.291Z"
pinned = false
attachments = "https://cdn.discordapp.com/attachments/1397785959243976724/1397785959545835571/thumbnail-06.jpg?ex=69ae419e&is=69acf01e&hm=b69a5d7fabeee733966316e065f83170c37197e67a6ec61a157cf71600dac574&"
thumbnail = ""

[[messages.linkPreviews]]
url = "https://www.iwara.tv/video/97vx62KKEx9a5D/carlotta-ntr-02"
title = "Iwara"
image = ""
site = "www.iwara.tv"
desc = "Iwara"
