id = "1342748920329015317"
name = "[Chopsticker] Carlotta x Rover"
archived = true
locked = false
createdAt = "2025-02-22T06:44:49.675Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1342748920329015317"
author = "korieuko"
content = "https://rule34video.com/video/3654059/chopsticker-carlotta-x-rover/"
createdAt = "2025-02-22T06:44:49.675Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3654000/3654059/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3654059/chopsticker-carlotta-x-rover/"
title = "[Chopsticker] Carlotta x Rover"
image = "https://rule34video.com/contents/videos_screenshots/3654000/3654059/preview.jpg"
site = "rule34video.com"
desc = ""
