id = "1378267021573357618"
name = "[Imsayaa34] Carlotta [4K] (Sound) - White Version"
archived = true
locked = false
createdAt = "2025-05-31T07:01:04.906Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1378267021573357618"
author = "korieuko"
content = "https://rule34video.com/video/3858997/imsayaa34-carlotta-4k-sound-white-version/"
createdAt = "2025-05-31T07:01:04.906Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
