id = "1379440598481899631"
name = "[koro22] Carlotta"
archived = true
locked = false
createdAt = "2025-06-03T12:44:27.445Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1379440598481899631"
author = "korieuko"
content = "https://rule34video.com/video/3863337/koro22-carlotta/"
createdAt = "2025-06-03T12:44:27.445Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3863000/3863337/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3863337/koro22-carlotta/"
title = "[koro22] Carlotta"
image = "https://rule34video.com/contents/videos_screenshots/3863000/3863337/preview.jpg"
site = "rule34video.com"
desc = "Creator: koro22"
