id = "1468978338499399805"
name = "[Oblivionis Art] Carlotta got completely addicted to him…"
archived = true
locked = false
createdAt = "2026-02-05T14:35:28.196Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468978338499399805"
author = "korieuko"
content = "https://rule34video.com/video/4229482/oblivionis-art-carlotta-got-completely-addicted-to-him/"
createdAt = "2026-02-05T14:35:28.196Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4229000/4229482/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4229482/oblivionis-art-carlotta-got-completely-addicted-to-him/"
title = "[Oblivionis Art] Carlotta got completely addicted to him…"
image = "https://rule34video.com/contents/videos_screenshots/4229000/4229482/preview.jpg"
site = "rule34video.com"
desc = "Souce: https://x.com/Oblivionis_art\nSend suggestions via DM (It's free for now)"
