id = "1383829868164284458"
name = "[Shinaosumata] Carlotta Compilation"
archived = true
locked = false
createdAt = "2025-06-15T15:25:50.886Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1383829868164284458"
author = "korieuko"
content = "https://rule34video.com/video/3884225/shinaosumata-carlotta-compilation/"
createdAt = "2025-06-15T15:25:50.886Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3884000/3884225/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3884225/shinaosumata-carlotta-compilation/"
title = "[Shinaosumata] Carlotta Compilation"
image = "https://rule34video.com/contents/videos_screenshots/3884000/3884225/preview.jpg"
site = "rule34video.com"
desc = ""
