id = "1353332271096004619"
name = "[WW] Carlotta Ojou-sama"
archived = true
locked = false
createdAt = "2025-03-23T11:39:17.127Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1353332271096004619"
author = "korieuko"
content = "https://rule34video.com/video/3741821/ww-carlotta-ojou-sama/"
createdAt = "2025-03-23T11:39:17.127Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3741000/3741821/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3741821/ww-carlotta-ojou-sama/"
title = "[WW] Carlotta Ojou-sama"
image = "https://rule34video.com/contents/videos_screenshots/3741000/3741821/preview.jpg"
site = "rule34video.com"
desc = "patreon.com/FlappyD\nfdfd.fanbox.cc\n\nScene by TotheMoon"
