id = "1371467942042013846"
name = "A bounty reward with Carlotta"
archived = true
locked = false
createdAt = "2025-05-12T12:43:58.025Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371467942042013846"
author = "korieuko"
content = "https://rule34video.com/video/3768437/a-bounty-reward-with-carlotta/"
createdAt = "2025-05-12T12:43:58.025Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3768000/3768437/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3768437/a-bounty-reward-with-carlotta/"
title = "A bounty reward with Carlotta"
image = "https://rule34video.com/contents/videos_screenshots/3768000/3768437/preview.jpg"
site = "rule34video.com"
desc = ""
