id = "1377547579855999048"
name = "Carlotta Mating Press [Heel]"
archived = true
locked = false
createdAt = "2025-05-29T07:22:16.634Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377547579855999048"
author = "korieuko"
content = "https://rule34video.com/video/3857653/carlotta-mating-press-heel/"
createdAt = "2025-05-29T07:22:16.634Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3857000/3857653/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3857653/carlotta-mating-press-heel/"
title = "Carlotta Mating Press [Heel]"
image = "https://rule34video.com/contents/videos_screenshots/3857000/3857653/preview.jpg"
site = "rule34video.com"
desc = "https://realize.fanbox.cc/\n\n**Please support the artist !! **"
