id = "1404845018618925158"
name = "Carlotta 3"
archived = true
locked = false
createdAt = "2025-08-12T15:12:33.197Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404845018618925158"
author = "korieuko"
content = "https://rule34video.com/video/3965554/carlotta2/"
createdAt = "2025-08-12T15:12:33.197Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
