id = "1371467829244596244"
name = "Carlotta 4k Sound (BlackVer)"
archived = true
locked = false
createdAt = "2025-05-12T12:43:31.132Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371467829244596244"
author = "korieuko"
content = "https://rule34video.com/video/3775285/carlotta-4k-sound-blackver/"
createdAt = "2025-05-12T12:43:31.132Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3775000/3775285/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3775285/carlotta-4k-sound-blackver/"
title = "Carlotta 4k Sound (BlackVer)"
image = "https://rule34video.com/contents/videos_screenshots/3775000/3775285/preview.jpg"
site = "rule34video.com"
desc = ""
