id = "1361159599088210070"
name = "Carlotta pov"
archived = true
locked = false
createdAt = "2025-04-14T02:02:17.545Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1361159599088210070"
author = "korieuko"
content = "https://rule34video.com/video/3775661/carlotta-pov/"
createdAt = "2025-04-14T02:02:17.545Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3775000/3775661/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3775661/carlotta-pov/"
title = "Carlotta pov"
image = "https://rule34video.com/contents/videos_screenshots/3775000/3775661/preview.jpg"
site = "rule34video.com"
desc = "Carlotta pov"
