id = "1342749978665291849"
name = "Carlotta sex"
archived = true
locked = false
createdAt = "2025-02-22T06:49:02.002Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1342749978665291849"
author = "korieuko"
content = "https://rule34video.com/video/3651185/carlotta-sex/"
createdAt = "2025-02-22T06:49:02.002Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3651000/3651185/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3651185/carlotta-sex/"
title = "Carlotta sex"
image = "https://rule34video.com/contents/videos_screenshots/3651000/3651185/preview.jpg"
site = "rule34video.com"
desc = ""
