id = "1396158611910295573"
name = "Montelli Summer (Swimsuit) [HorizontalSlope]"
archived = true
locked = false
createdAt = "2025-07-19T15:55:52.452Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1396158611910295573"
author = "korieuko"
content = "https://rule34video.com/video/3941261/montelli-summer-swimsuit-horizontalslope/"
createdAt = "2025-07-19T15:55:52.452Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3941000/3941261/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3941261/montelli-summer-swimsuit-horizontalslope/"
title = "Montelli Summer (Swimsuit) [HorizontalSlope]"
image = "https://rule34video.com/contents/videos_screenshots/3941000/3941261/preview.jpg"
site = "rule34video.com"
desc = "Carlotta VA: @chloeangelVA\nMale model: @dab_neko @heliosprimes\nSFX Pack: @OpenNSFWSP @LehornySfx3d | @RaptorAudioSfx"

[[messages]]
id = "1412101045944979511"
author = "korieuko"
content = "hella good"
createdAt = "2025-09-01T15:45:24.922Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
