id = "1429127277416812717"
name = "RDreamer Carlotta PT2 FULL"
archived = true
locked = false
createdAt = "2025-10-18T15:21:34.837Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1429127277416812717"
author = "korieuko"
content = "https://rule34video.com/video/4068986/rdreamer-carlotta-pt2-full/"
createdAt = "2025-10-18T15:21:34.837Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4068000/4068986/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4068986/rdreamer-carlotta-pt2-full/"
title = "RDreamer Carlotta PT2 FULL"
image = "https://rule34video.com/contents/videos_screenshots/4068000/4068986/preview.jpg"
site = "rule34video.com"
desc = ""
