id = "1417113085285502986"
name = "Cerydra [Akt]"
archived = true
locked = false
createdAt = "2025-09-15T11:41:28.220Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1417113085285502986"
author = "korieuko"
content = "https://rule34video.com/video/4026685/cerydra-akt/"
createdAt = "2025-09-15T11:41:28.220Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4026000/4026685/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4026685/cerydra-akt/"
title = "Cerydra [Akt]"
image = "https://rule34video.com/contents/videos_screenshots/4026000/4026685/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://akt.fanbox.cc\nhttps://www.patreon.com/c/akt_shop\nhttps://ganknow.com/animationakt"
