id = "1416314145476968560"
name = "Fucked on Live"
archived = true
locked = false
createdAt = "2025-09-13T06:46:46.126Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1416314145476968560"
author = "korieuko"
content = "https://rule34video.com/video/4026609/fucked-on-live/"
createdAt = "2025-09-13T06:46:46.126Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4026000/4026609/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4026609/fucked-on-live/"
title = "Fucked on Live"
image = "https://rule34video.com/contents/videos_screenshots/4026000/4026609/preview.jpg"
site = "rule34video.com"
desc = ""
