id = "1476248600991240264"
name = "Chen Qianyu_Arknights EndField [Aung15]"
archived = false
locked = false
createdAt = "2026-02-25T16:04:53.849Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1476248600991240264"
author = "korieuko"
content = "https://rule34video.com/video/4258746/chen-qianyu-arknights-endfield-aung15/"
createdAt = "2026-02-25T16:04:53.849Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4258000/4258746/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4258746/chen-qianyu-arknights-endfield-aung15/"
title = "Chen Qianyu_Arknights EndField [Aung15]"
image = "https://rule34video.com/contents/videos_screenshots/4258000/4258746/preview.jpg"
site = "rule34video.com"
desc = "Chen Qianyu_Arknights EndField [Aung15]\n\n:||"
