id = "1314856955654705153"
name = "[YESUI] Ayaka 2K60FPS 動画"
archived = true
locked = false
createdAt = "2024-12-07T07:32:07.089Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314856955654705153"
author = "korieuko"
content = "https://avbebe.com/archives/252980"
createdAt = "2024-12-07T07:32:07.089Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/09/YESUI-Ayaka-2K60FPS-%E5%8B%95%E7%94%BB.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/252980"
title = "[YESUI] Ayaka 2K60FPS 動画"
image = "https://avbebe.com/wp-content/uploads/2024/09/YESUI-Ayaka-2K60FPS-%E5%8B%95%E7%94%BB.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
