id = "1314889758287204372"
name = "Kamisato Ayaka"
archived = true
locked = false
createdAt = "2024-12-07T09:42:27.846Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314889758287204372"
author = "korieuko"
content = "https://rule34video.com/video/3146153/kamisato-ayaka-x-ray/"
createdAt = "2024-12-07T09:42:27.846Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3146000/3146153/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3146153/kamisato-ayaka-x-ray/"
title = "Kamisato Ayaka X-ray"
image = "https://rule34video.com/contents/videos_screenshots/3146000/3146153/preview.jpg"
site = "rule34video.com"
desc = ""
