id = "1320055323184205884"
name = "NTR Kamisato Ayaka×Hilichurl「jibrish」"
archived = true
locked = false
createdAt = "2024-12-21T15:48:34.489Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1320055323184205884"
author = "korieuko"
content = "https://rule34video.com/video/3620097/ntr-kamisato-ayaka-hilichurl-jibrish/"
createdAt = "2024-12-21T15:48:34.489Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3620000/3620097/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3620097/ntr-kamisato-ayaka-hilichurl-jibrish/"
title = "NTR Kamisato Ayaka×Hilichurl「jibrish」"
image = "https://rule34video.com/contents/videos_screenshots/3620000/3620097/preview.jpg"
site = "rule34video.com"
desc = ""
