id = "1375454641273307166"
name = "[GX][2501] 扳机 Trigger [Akt]"
archived = true
locked = false
createdAt = "2025-05-23T12:45:41.191Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375454641273307166"
author = "korieuko"
content = "https://rule34video.com/video/3830649/gx-2501-trigger-akt/"
createdAt = "2025-05-23T12:45:41.191Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
