id = "1442537869649510442"
name = "Trigger tests the new barrel"
archived = true
locked = false
createdAt = "2025-11-24T15:30:29.182Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442537869649510442"
author = "korieuko"
content = "https://rule34video.com/video/4118410/trigger-tests-the-new-barrel/"
createdAt = "2025-11-24T15:30:29.182Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4118000/4118410/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4118410/trigger-tests-the-new-barrel/"
title = "Trigger tests the new barrel"
image = "https://rule34video.com/contents/videos_screenshots/4118000/4118410/preview.jpg"
site = "rule34video.com"
desc = "Trigger - @HairyHarzo\nWise - @HeliosPrimes"
