id = "1412101549123047497"
name = "Trigger-training [HoyoCinema][4k 60fps]"
archived = true
locked = false
createdAt = "2025-09-01T15:47:24.889Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1412101549123047497"
author = "korieuko"
content = "https://rule34video.com/video/4006129/trigger-training-hoyocinema-4k-60fps/"
createdAt = "2025-09-01T15:47:24.889Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4006000/4006129/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4006129/trigger-training-hoyocinema-4k-60fps/"
title = "Trigger-training [HoyoCinema][4k 60fps]"
image = "https://rule34video.com/contents/videos_screenshots/4006000/4006129/preview.jpg"
site = "rule34video.com"
desc = "Map: Never_yapph\n\nModels: WaffleNSFW/DaB_neko\n\nVA pack: HellicaVA/Trigger \n\nSFX pack: OpenNSFWSP\n\nhttps://x.com/HoyoCinema\n\nhttps://hoyocinema.newgrounds.com/\n\nhttps://www.patreon.com/HoyoCinema\n\nhttps://www.iwara.tv/profile/hoyocinema\n\nhttps://www.pixiv.net/en/users/70828813"
