id = "1375443701202948236"
name = "Trigger x Wise (Full Release)[TwiistedLewds] [4k 60fps]"
archived = true
locked = false
createdAt = "2025-05-23T12:02:12.875Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375443701202948236"
author = "korieuko"
content = "https://rule34video.com/video/3845353/trigger-full-release-twiistedlewds-4k-60fps/"
createdAt = "2025-05-23T12:02:12.875Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3845000/3845353/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3845353/trigger-full-release-twiistedlewds-4k-60fps/"
title = "Trigger x Wise (Full Release)[TwiistedLewds] [4k 60fps]"
image = "https://rule34video.com/contents/videos_screenshots/3845000/3845353/preview.jpg"
site = "rule34video.com"
desc = "VA - nsfw_sonia_va/Trigger\n\nSFX - RayTracingVA_18\n\nModels - \n@WaffleNSFW/DaB_neko\n\nhttps://x.com/TwiistedLewds\n\nhttps://www.patreon.com/TwiistedLewds"
