id = "1366080604436693042"
name = "Trigger ZZZ"
archived = true
locked = false
createdAt = "2025-04-27T15:56:36.648Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1366080604436693042"
author = "korieuko"
content = "https://rule34video.com/video/3800417/trigger-zzz/"
createdAt = "2025-04-27T15:56:36.648Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3800000/3800417/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3800417/trigger-zzz/"
title = "Trigger ZZZ"
image = "https://rule34video.com/contents/videos_screenshots/3800000/3800417/preview.jpg"
site = "rule34video.com"
desc = ""
