id = "1375453517124337664"
name = "Trigger getting Filled"
archived = true
locked = false
createdAt = "2025-05-23T12:41:13.173Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1375453517124337664"
author = "korieuko"
content = "https://rule34video.com/video/3841425/trigger-getting-filled/"
createdAt = "2025-05-23T12:41:13.173Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3841000/3841425/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3841425/trigger-getting-filled/"
title = "Trigger getting Filled"
image = "https://rule34video.com/contents/videos_screenshots/3841000/3841425/preview.jpg"
site = "rule34video.com"
desc = "Creator: https://www.patreon.com/delightss"

[[messages]]
id = "1375453546152988782"
author = "korieuko"
content = "Hella good"
createdAt = "2025-05-23T12:41:20.094Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
