id = "1322519029990297620"
name = "[01]【changli】0701 Clothed Sound Ver"
archived = true
locked = false
createdAt = "2024-12-28T10:58:27.965Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1322519029990297620"
author = "korieuko"
content = "https://rule34video.com/video/3528690/01-changli-0701-clothed-sound-ver/"
createdAt = "2024-12-28T10:58:27.965Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3528000/3528690/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3528690/01-changli-0701-clothed-sound-ver/"
title = "[01]【changli】0701 Clothed Sound Ver"
image = "https://rule34video.com/contents/videos_screenshots/3528000/3528690/preview.jpg"
site = "rule34video.com"
desc = "2024.07"
