id = "1371869414982418586"
name = "[AKT] Changli"
archived = true
locked = false
createdAt = "2025-05-13T15:19:16.633Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371869414982418586"
author = "korieuko"
content = "https://rule34video.com/video/3833377/akt-changli/"
createdAt = "2025-05-13T15:19:16.633Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3833000/3833377/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3833377/akt-changli/"
title = "[AKT] Changli"
image = "https://rule34video.com/contents/videos_screenshots/3833000/3833377/preview.jpg"
site = "rule34video.com"
desc = ""
