id = "1314894656261324853"
name = "[Tir_AL] 2024. 09. Changli"
archived = true
locked = false
createdAt = "2024-12-07T10:01:55.614Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314894656261324853"
author = "korieuko"
content = "https://avbebe.com/archives/256456"
createdAt = "2024-12-07T10:01:55.614Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/10/Tir_AL-%E9%95%B7%E9%9B%A2%E9%B3%B4%E6%BD%AE.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/256456"
title = "[Tir_AL] 2024. 09. Changli"
image = "https://avbebe.com/wp-content/uploads/2024/10/Tir_AL-%E9%95%B7%E9%9B%A2%E9%B3%B4%E6%BD%AE.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
