id = "1323972073680277567"
name = "【Waero】changli sex"
archived = true
locked = false
createdAt = "2025-01-01T11:12:20.577Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1323972073680277567"
author = "korieuko"
content = "https://rule34video.com/video/3582987/changle-sex/"
createdAt = "2025-01-01T11:12:20.577Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3582000/3582987/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3582987/changle-sex/"
title = "【Waero】changli sex"
image = "https://rule34video.com/contents/videos_screenshots/3582000/3582987/preview.jpg"
site = "rule34video.com"
desc = "Wuthering Waves\nchangle sex\nart waero\nHMV make rityuel"
