id = "1377547056268316682"
name = "Butt Slapping Changli Doggy [mw9]"
archived = true
locked = false
createdAt = "2025-05-29T07:20:11.801Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377547056268316682"
author = "korieuko"
content = "https://rule34video.com/video/3857257/butt-slapping-changli-doggy-mw9/"
createdAt = "2025-05-29T07:20:11.801Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3857000/3857257/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3857257/butt-slapping-changli-doggy-mw9/"
title = "Butt Slapping Changli Doggy [mw9]"
image = "https://rule34video.com/contents/videos_screenshots/3857000/3857257/preview.jpg"
site = "rule34video.com"
desc = "Animation: https://x.com/mw9_tw"
