id = "1314893698957578272"
name = "Changli footjob"
archived = true
locked = false
createdAt = "2024-12-07T09:58:07.375Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314893698957578272"
author = "korieuko"
content = "https://avbebe.com/archives/238394"
createdAt = "2024-12-07T09:58:07.375Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/07/FootJob02-%E9%B3%B4%E6%BD%AE-Changli%E9%95%B7%E9%9B%A2.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/238394"
title = "[Lanzfh] FootJob02 鳴潮 Changli(長離)"
image = "https://avbebe.com/wp-content/uploads/2024/07/FootJob02-%E9%B3%B4%E6%BD%AE-Changli%E9%95%B7%E9%9B%A2.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe Avbebe Please"
