id = "1406296327196901386"
name = "Changli makelove with Scaramouche"
archived = true
locked = false
createdAt = "2025-08-16T15:19:32.126Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406296327196901386"
author = "korieuko"
content = "https://rule34video.com/video/3981745/changli-makelove-with-scaramouche/"
createdAt = "2025-08-16T15:19:32.126Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3981000/3981745/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3981745/changli-makelove-with-scaramouche/"
title = "Changli makelove with Scaramouche"
image = "https://rule34video.com/contents/videos_screenshots/3981000/3981745/preview.jpg"
site = "rule34video.com"
desc = "if you want to watch more videos\nhttps://t.me/sanbingfuren"
