id = "1392540819273285652"
name = "Chang Li vs BBC「Mslewd」"
archived = true
locked = false
createdAt = "2025-07-09T16:20:03.472Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1392540819273285652"
author = "korieuko"
content = "https://rule34video.com/video/3757681/chang-li-vs-bbc-mslewd/"
createdAt = "2025-07-09T16:20:03.472Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
