id = "1382978151185121371"
name = "Changli gets fucked"
archived = true
locked = false
createdAt = "2025-06-13T07:01:25.734Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382978151185121371"
author = "korieuko"
content = "https://rule34video.com/video/3741421/changli-gets-fucked/"
createdAt = "2025-06-13T07:01:25.734Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
