id = "1398960972726665307"
name = "Fractsidus Mission to capture Changli"
archived = true
locked = false
createdAt = "2025-07-27T09:31:27.336Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1398960972726665307"
author = "korieuko"
content = "https://rule34video.com/video/3951777/fractsidus-mission-to-capture-changli/"
createdAt = "2025-07-27T09:31:27.336Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3951000/3951777/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3951777/fractsidus-mission-to-capture-changli/"
title = "Fractsidus Mission to capture Changli"
image = "https://rule34video.com/contents/videos_screenshots/3951000/3951777/preview.jpg"
site = "rule34video.com"
desc = "All angles\n\nChangli from Tir_Al with subtitles, for ambience enjoyers\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"
