id = "1468939120649703434"
name = "Wuwa Changli Loop (Sound Version) - Lazyrice3D"
archived = true
locked = false
createdAt = "2026-02-05T11:59:37.932Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468939120649703434"
author = "korieuko"
content = "https://rule34video.com/video/4227946/wuwa-changli-loop-sound-version-lazyrice3d/"
createdAt = "2026-02-05T11:59:37.932Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4227000/4227946/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4227946/wuwa-changli-loop-sound-version-lazyrice3d/"
title = "Wuwa Changli Loop (Sound Version) - Lazyrice3D"
image = "https://rule34video.com/contents/videos_screenshots/4227000/4227946/preview.jpg"
site = "rule34video.com"
desc = ""
