id = "1406606099443875891"
name = "[DLC][2404] Bronya [Akt]"
archived = true
locked = false
createdAt = "2025-08-17T11:50:27.585Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406606099443875891"
author = "korieuko"
content = "https://rule34video.com/video/3532017/dlc-2404-bronya-akt/"
createdAt = "2025-08-17T11:50:27.585Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
