id = "1314873235799543809"
name = "[海鲜粥(SFcongee)] 大鴨鴨和艦長的辦公室Play [中文字幕]"
archived = true
locked = false
createdAt = "2024-12-07T08:36:48.578Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314873235799543809"
author = "korieuko"
content = "https://avbebe.com/archives/249749"
createdAt = "2024-12-07T08:36:48.578Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/09/%E6%B5%B7%E9%B2%9C%E7%B2%A5SFcongee-%E5%A4%A7%E9%B4%A8%E9%B4%A8%E5%92%8C%E8%89%A6%E9%95%B7%E7%9A%84%E8%BE%A6%E5%85%AC%E5%AE%A4Play-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/249749"
title = "[海鲜粥(SFcongee)] 大鴨鴨和艦長的辦公室Play [中文字幕]"
image = "https://avbebe.com/wp-content/uploads/2024/09/%E6%B5%B7%E9%B2%9C%E7%B2%A5SFcongee-%E5%A4%A7%E9%B4%A8%E9%B4%A8%E5%92%8C%E8%89%A6%E9%95%B7%E7%9A%84%E8%BE%A6%E5%85%AC%E5%AE%A4Play-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
