id = "1375454031081635870"
name = "Bronya x Cocolia [Delightss]"
archived = true
locked = false
createdAt = "2025-05-23T12:43:15.710Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375454031081635870"
author = "korieuko"
content = "https://rule34video.com/video/3514581/bronya-x-cocolia-delightss/"
createdAt = "2025-05-23T12:43:15.710Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3514000/3514581/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3514581/bronya-x-cocolia-delightss/"
title = "Bronya x Cocolia [Delightss]"
image = "https://rule34video.com/contents/videos_screenshots/3514000/3514581/preview.jpg"
site = "rule34video.com"
desc = "https://www.patreon.com/delightss\n\nhttps://x.com/delights2s\n\nhttps://www.pixiv.net/en/users/99694713\n\nSupport the original creators!"
