id = "1406605846275952650"
name = "Worker's Privillege"
archived = true
locked = false
createdAt = "2025-08-17T11:49:27.225Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406605846275952650"
author = "korieuko"
content = "https://rule34video.com/video/3111357/worker-s-privillege/"
createdAt = "2025-08-17T11:49:27.225Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3111000/3111357/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3111357/worker-s-privillege/"
title = "Worker's Privillege"
image = "https://rule34video.com/contents/videos_screenshots/3111000/3111357/preview.jpg"
site = "rule34video.com"
desc = ""
