id = "1417112853780889650"
name = "[Erio] Hysilens"
archived = true
locked = false
createdAt = "2025-09-15T11:40:33.025Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1417112853780889650"
author = "korieuko"
content = "https://rule34video.com/video/4029545/erio-hysilens/"
createdAt = "2025-09-15T11:40:33.025Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4029000/4029545/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4029545/erio-hysilens/"
title = "[Erio] Hysilens"
image = "https://rule34video.com/contents/videos_screenshots/4029000/4029545/preview.jpg"
site = "rule34video.com"
desc = ""
