id = "1419664888913203241"
name = "Hysilens [Akt]"
archived = true
locked = false
createdAt = "2025-09-22T12:41:25.615Z"
autoArchiveDuration = 4320
messageCount = 3
appliedTags = []

[[messages]]
id = "1419664888913203241"
author = "korieuko"
content = "https://rule34video.com/video/4022977/hysilens-akt/"
createdAt = "2025-09-22T12:41:25.615Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4022000/4022977/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4022977/hysilens-akt/"
title = "Hysilens [Akt]"
image = "https://rule34video.com/contents/videos_screenshots/4022000/4022977/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://akt.fanbox.cc\nhttps://www.patreon.com/c/akt_shop\nhttps://ganknow.com/animationakt"

[[messages]]
id = "1419664912531062826"
author = "korieuko"
content = "good"
createdAt = "2025-09-22T12:41:31.246Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []

[[messages]]
id = "1419722029703102484"
author = "korieuko"
content = "3rd"
createdAt = "2025-09-22T16:28:29.041Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
