id = "1314898743765762099"
name = "[AlphaG] Capture Shenhe[中文字幕]"
archived = true
locked = false
createdAt = "2024-12-07T10:18:10.151Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314898743765762099"
author = "korieuko"
content = "https://avbebe.com/archives/264200"
createdAt = "2024-12-07T10:18:10.151Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
