id = "1315180079730655232"
name = "[rinjo_18] Shenhe Full"
archived = true
locked = false
createdAt = "2024-12-08T04:56:05.872Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1315180079730655232"
author = "korieuko"
content = "https://avbebe.com/archives/190603"
createdAt = "2024-12-08T04:56:05.872Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2023/12/%E3%80%8A%E5%8E%9F%E7%A5%9E%E3%80%8B%E7%94%B3%E9%B6%B4.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/190603"
title = "[rinjo_18] Shenhe  Full"
image = "https://avbebe.com/wp-content/uploads/2023/12/%E3%80%8A%E5%8E%9F%E7%A5%9E%E3%80%8B%E7%94%B3%E9%B6%B4.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "#1 #2 《原神》申鶴 《原神》申鶴"
