id = "1376121808566091846"
name = "Chillin' time with Shenhe"
archived = true
locked = false
createdAt = "2025-05-25T08:56:46.269Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376121808566091846"
author = "korieuko"
content = "https://rule34video.com/video/3663707/chillin-time-with-shenhe/"
createdAt = "2025-05-25T08:56:46.269Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
