id = "1376122424596107274"
name = "Gangbang"
archived = true
locked = false
createdAt = "2025-05-25T08:59:13.142Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376122424596107274"
author = "korieuko"
content = "https://rule34video.com/video/3562941/gangbang4/"
createdAt = "2025-05-25T08:59:13.142Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3562000/3562941/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3562941/gangbang4/"
title = "Gangbang"
image = "https://rule34video.com/contents/videos_screenshots/3562000/3562941/preview.jpg"
site = "rule34video.com"
desc = ""
