id = "1342749293228064778"
name = "GI Shenhe x Xianyun (Chopsticker)"
archived = true
locked = false
createdAt = "2025-02-22T06:46:18.581Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1342749293228064778"
author = "korieuko"
content = "https://rule34video.com/video/3344054/gi-shenhe-x-xianyun-chopsticker/"
createdAt = "2025-02-22T06:46:18.581Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3344000/3344054/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3344054/gi-shenhe-x-xianyun-chopsticker/"
title = "GI Shenhe x Xianyun (Chopsticker)"
image = "https://rule34video.com/contents/videos_screenshots/3344000/3344054/preview.jpg"
site = "rule34video.com"
desc = ""
