id = "1387256512703107093"
name = "Shenhe giving a receiving love"
archived = true
locked = false
createdAt = "2025-06-25T02:22:06.608Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1387256512703107093"
author = "korieuko"
content = "https://rule34video.com/video/3899533/shenhe-giving-a-receiving-love/"
createdAt = "2025-06-25T02:22:06.608Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3899000/3899533/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3899533/shenhe-giving-a-receiving-love/"
title = "Shenhe giving a receiving love"
image = "https://rule34video.com/contents/videos_screenshots/3899000/3899533/preview.jpg"
site = "rule34video.com"
desc = ""
