id = "1389230263304982548"
name = "ShenHe (Full) [Genshin]"
archived = true
locked = false
createdAt = "2025-06-30T13:05:05.422Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389230263304982548"
author = "korieuko"
content = "https://rule34video.com/video/3904573/shenhe-full-genshin/"
createdAt = "2025-06-30T13:05:05.422Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
