id = "1394119533446303784"
name = "Shenhe x Hilichurl Side Fuck [Tir_Al]"
archived = true
locked = false
createdAt = "2025-07-14T00:53:18.262Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394119533446303784"
author = "korieuko"
content = "https://rule34video.com/video/3420285/shenhe-x-hilichurl-side-fuck-tir-al/"
createdAt = "2025-07-14T00:53:18.262Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3420000/3420285/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3420285/shenhe-x-hilichurl-side-fuck-tir-al/"
title = "Shenhe x Hilichurl Side Fuck [Tir_Al]"
image = "https://rule34video.com/contents/videos_screenshots/3420000/3420285/preview.jpg"
site = "rule34video.com"
desc = "one scene trimmed version"
