id = "1376121953387282573"
name = "Shenhe Amazon Position [LazyRice3D]"
archived = true
locked = false
createdAt = "2025-05-25T08:57:20.797Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376121953387282573"
author = "korieuko"
content = "https://rule34video.com/video/3573735/shenhe-amazon-position-lazyrice3d/"
createdAt = "2025-05-25T08:57:20.797Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3573000/3573735/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3573735/shenhe-amazon-position-lazyrice3d/"
title = "Shenhe Amazon Position [LazyRice3D]"
image = "https://rule34video.com/contents/videos_screenshots/3573000/3573735/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/lazyrice3d/status/1846845036652384442"
