id = "1375454178930851951"
name = "Shenhe [Delightss]"
archived = true
locked = false
createdAt = "2025-05-23T12:43:50.960Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1375454178930851951"
author = "korieuko"
content = "https://rule34video.com/video/3398158/shenhe-delightss/"
createdAt = "2025-05-23T12:43:50.960Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3398000/3398158/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3398158/shenhe-delightss/"
title = "Shenhe [Delightss]"
image = "https://rule34video.com/contents/videos_screenshots/3398000/3398158/preview.jpg"
site = "rule34video.com"
desc = "https://twitter.com/delights2s\n\nhttps://linktr.ee/delightss"

[[messages]]
id = "1375454213802430485"
author = "korieuko"
content = "Hella good"
createdAt = "2025-05-23T12:43:59.274Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
