id = "1345742783608127599"
name = "Shenhe Sleep Sex [Berg-Yb]"
archived = true
locked = false
createdAt = "2025-03-02T13:01:22.304Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1345742783608127599"
author = "korieuko"
content = "https://rule34video.com/video/3698081/shenhe-sleep-sex-berg-yb/"
createdAt = "2025-03-02T13:01:22.304Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3698000/3698081/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3698081/shenhe-sleep-sex-berg-yb/"
title = "Shenhe Sleep Sex [Berg-Yb]"
image = "https://rule34video.com/contents/videos_screenshots/3698000/3698081/preview.jpg"
site = "rule34video.com"
desc = ""
