id = "1383475676891451404"
name = "Shenhe x Hilichurls clothed 4k「JygreAnimation」"
archived = true
locked = false
createdAt = "2025-06-14T15:58:25.106Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1383475676891451404"
author = "korieuko"
content = "https://rule34video.com/video/3293304/shenhe-x-hilichurls-clothed-4k-jygreanimation/"
createdAt = "2025-06-14T15:58:25.106Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3293000/3293304/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3293304/shenhe-x-hilichurls-clothed-4k-jygreanimation/"
title = "Shenhe x Hilichurls clothed 4k「JygreAnimation」"
image = "https://rule34video.com/contents/videos_screenshots/3293000/3293304/preview.jpg"
site = "rule34video.com"
desc = ""
