id = "1389230607690895470"
name = "All Assdepik creampie compilation"
archived = true
locked = false
createdAt = "2025-06-30T13:06:27.530Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389230607690895470"
author = "korieuko"
content = "https://rule34video.com/video/3877273/all-assdepik-creampie-compilation/"
createdAt = "2025-06-30T13:06:27.530Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3877000/3877273/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3877273/all-assdepik-creampie-compilation/"
title = "All Assdepik creampie compilation"
image = "https://rule34video.com/contents/videos_screenshots/3877000/3877273/preview.jpg"
site = "rule34video.com"
desc = "Cum cum cum"
