id = "1366080970314350612"
name = "Compilation Hoyoverse 2 : sex, cumshots, futanari... (genshin impact, zzz, hsr)"
archived = true
locked = false
createdAt = "2025-04-27T15:58:03.880Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1366080970314350612"
author = "korieuko"
content = "https://rule34video.com/video/3711333/compilation-hoyoverse-2-sex-cumshots-futanari-genshin-impact-zzz-hsr/"
createdAt = "2025-04-27T15:58:03.880Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3711000/3711333/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3711333/compilation-hoyoverse-2-sex-cumshots-futanari-genshin-impact-zzz-hsr/"
title = "Compilation Hoyoverse 2 : sex, cumshots, futanari... (genshin impac..."
image = "https://rule34video.com/contents/videos_screenshots/3711000/3711333/preview.jpg"
site = "rule34video.com"
desc = "For more compilation follow me, put a like, you can put a message too, i put a lot of creators in the description and some of these are not on the video, its normal because i have three videos prepared and i will put them in the three videos because they appear in at least one video.\n\n\nFollow these creators : \n\nvicineko, theobrobine, nagoonimati..."
