id = "1376407364202266665"
name = "Genshin Impact Raiden Shogun X Hilichurls Compilation"
archived = true
locked = false
createdAt = "2025-05-26T03:51:28.038Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376407364202266665"
author = "korieuko"
content = "https://rule34video.com/video/3845521/genshin-impact-raiden-shogun-x-hilichurls-compilation/"
createdAt = "2025-05-26T03:51:28.038Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3845000/3845521/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3845521/genshin-impact-raiden-shogun-x-hilichurls-compilation/"
title = "Genshin Impact Raiden Shogun X Hilichurls Compilation"
image = "https://rule34video.com/contents/videos_screenshots/3845000/3845521/preview.jpg"
site = "rule34video.com"
desc = "Artists name: Sodeno19, Conjur3me, RedRainSFM, inari, mintycat MagicalMysticVA, Jibrish, Koro22, mig15bis, Dragk, AlphaG, Tir_Al, Ubermation, Makoda.\r\n\r\nRaiden enjoys her training to much (:"
