id = "1371881990344675511"
name = "Keqing Compilation 1"
archived = true
locked = false
createdAt = "2025-05-13T16:09:14.833Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371881990344675511"
author = "korieuko"
content = "https://rule34video.com/video/3831725/keqing-compilation-1/"
createdAt = "2025-05-13T16:09:14.833Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3831000/3831725/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3831725/keqing-compilation-1/"
title = "Keqing Compilation 1"
image = "https://rule34video.com/contents/videos_screenshots/3831000/3831725/preview.jpg"
site = "rule34video.com"
desc = ""
