id = "1376120316027211816"
name = "Navia compilation r34"
archived = true
locked = false
createdAt = "2025-05-25T08:50:50.420Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376120316027211816"
author = "korieuko"
content = "https://rule34video.com/video/3846241/navia-compilation-r34-porn/"
createdAt = "2025-05-25T08:50:50.420Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3846000/3846241/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3846241/navia-compilation-r34-porn/"
title = "Navia compilation r34 porn"
image = "https://rule34video.com/contents/videos_screenshots/3846000/3846241/preview.jpg"
site = "rule34video.com"
desc = "A huge r34 compilation on navia from genshin impact"
