id = "1376121045257420932"
name = "Navia Genshin Impact"
archived = true
locked = false
createdAt = "2025-05-25T08:53:44.282Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376121045257420932"
author = "korieuko"
content = "https://rule34video.com/video/3524382/navia-genshin-impact2/"
createdAt = "2025-05-25T08:53:44.282Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3524000/3524382/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3524382/navia-genshin-impact2/"
title = "Navia Genshin Impact"
image = "https://rule34video.com/contents/videos_screenshots/3524000/3524382/preview.jpg"
site = "rule34video.com"
desc = ""
