id = "1422484890179604570"
name = "Xianyun Genshin fuck comp"
archived = true
locked = false
createdAt = "2025-09-30T07:27:06.310Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1422484890179604570"
author = "korieuko"
content = "https://rule34video.com/video/4052410/xianyun-genshin-fuck-comp/"
createdAt = "2025-09-30T07:27:06.310Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4052000/4052410/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4052410/xianyun-genshin-fuck-comp/"
title = "Xianyun Genshin fuck comp"
image = "https://rule34video.com/contents/videos_screenshots/4052000/4052410/preview.jpg"
site = "rule34video.com"
desc = ""
