id = "1314850398166585436"
name = "[Yuluer] トパーズ"
archived = true
locked = false
createdAt = "2024-12-07T07:06:03.662Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314850398166585436"
author = "korieuko"
content = "https://avbebe.com/archives/234618"
createdAt = "2024-12-07T07:06:03.662Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/07/%E3%83%88%E3%83%91%E3%83%BC%E3%82%BA.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/234618"
title = "[Yuluer] トパーズ"
image = "https://avbebe.com/wp-content/uploads/2024/07/%E3%83%88%E3%83%91%E3%83%BC%E3%82%BA.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwis (下載"
