id = "1394341330079060089"
name = "Topaz's Unpaid Debt"
archived = true
locked = false
createdAt = "2025-07-14T15:34:38.700Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394341330079060089"
author = "korieuko"
content = "https://rule34video.com/video/3665855/topaz-s-unpaid-debt/"
createdAt = "2025-07-14T15:34:38.700Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3665000/3665855/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3665855/topaz-s-unpaid-debt/"
title = "Topaz's Unpaid Debt"
image = "https://rule34video.com/contents/videos_screenshots/3665000/3665855/preview.jpg"
site = "rule34video.com"
desc = "All angles\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"
