id = "1421123624651329566"
name = "[TezAnimates] Lupa Animation Audio ver."
archived = true
locked = false
createdAt = "2025-09-26T13:17:55.317Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = ["1390664773993238588"]

[[messages]]
id = "1421123624651329566"
author = "korieuko"
content = "https://rule34video.com/video/4045414/tezanimates-lupa-animation-audio-ver/"
createdAt = "2025-09-26T13:17:55.317Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4045000/4045414/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4045414/tezanimates-lupa-animation-audio-ver/"
title = "[TezAnimates] Lupa Animation Audio ver."
image = "https://rule34video.com/contents/videos_screenshots/4045000/4045414/preview.jpg"
site = "rule34video.com"
desc = "4K 60fps version available in my patreon.\n\n[Patreon] https://www.patreon.com/c/tezanimates"
