id = "1385218890631741481"
name = "Lupa Doggy 2 ()Wutehringw waves [RDeamer]"
archived = true
locked = false
createdAt = "2025-06-19T11:25:19.649Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1385218890631741481"
author = "korieuko"
content = "https://rule34video.com/video/3889301/lupa-doggy-2-wutehringw-waves-realize/"
createdAt = "2025-06-19T11:25:19.649Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3889000/3889301/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3889301/lupa-doggy-2-wutehringw-waves-realize/"
title = "Lupa Doggy 2 ()Wutehringw waves [RDeamer]"
image = "https://rule34video.com/contents/videos_screenshots/3889000/3889301/preview.jpg"
site = "rule34video.com"
desc = "https://rdreamer.fanbox.cc/\n\n\n**Please Support the artist !! **"
