id = "1398550038782808096"
name = "Lupa Wuthering Waves animation[Velnier][4k 60fps]"
archived = true
locked = false
createdAt = "2025-07-26T06:18:33.049Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1398550038782808096"
author = "korieuko"
content = "https://rule34video.com/video/3950733/lupa-wuthering-waves-animation-velnier-4k-60fps/"
createdAt = "2025-07-26T06:18:33.049Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3950000/3950733/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3950733/lupa-wuthering-waves-animation-velnier-4k-60fps/"
title = "Lupa Wuthering Waves animation[Velnier][4k 60fps]"
image = "https://rule34video.com/contents/videos_screenshots/3950000/3950733/preview.jpg"
site = "rule34video.com"
desc = "Audio - Evilaudio1\n\nVoice - DelaliciousVA\n\nModels - HeliosPrimes & DaB_neko\n\nhttps://x.com/Velnier\n\nhttps://www.patreon.com/Velnier\n\nhttps://velnier.fanbox.cc/"
