id = "1390664854972399647"
name = "Lupa x Rover (wuthering waves)"
archived = true
locked = false
createdAt = "2025-07-04T12:05:38.729Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = ["1390664773993238588"]

[[messages]]
id = "1390664854972399647"
author = "korieuko"
content = "https://rule34video.com/video/3914493/lupa-x-rover-wuthering-waves2/"
createdAt = "2025-07-04T12:05:38.729Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3914000/3914493/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3914493/lupa-x-rover-wuthering-waves2/"
title = "Lupa x Rover (wuthering waves)"
image = "https://rule34video.com/contents/videos_screenshots/3914000/3914493/preview.jpg"
site = "rule34video.com"
desc = "When the hunt ends, the real tension begins.\nUnderneath the moonlight and adrenaline, Lupa takes the lead — primal, confident, unstoppable.\nRover isn’t just her partner in battle… he’s her prey tonight.\n\nFluid motion, raw desire, and the kind of connection that goes beyond words."
