id = "1392413121020297226"
name = "Lupa x Rover [FULL]"
archived = true
locked = false
createdAt = "2025-07-09T07:52:37.836Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1392413121020297226"
author = "korieuko"
content = "https://rule34video.com/video/3920721/lupa-x-rover-full/"
createdAt = "2025-07-09T07:52:37.836Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3920000/3920721/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3920721/lupa-x-rover-full/"
title = "Lupa x Rover [FULL]"
image = "https://rule34video.com/contents/videos_screenshots/3920000/3920721/preview.jpg"
site = "rule34video.com"
desc = ""
