id = "1391322416583675924"
name = "Lupa sex video (WuWa) 露帕 BDSM"
archived = true
locked = false
createdAt = "2025-07-06T07:38:33.634Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391322416583675924"
author = "korieuko"
content = "https://rule34video.com/video/3915781/lupa-sex-video-wuwa-bdsm/"
createdAt = "2025-07-06T07:38:33.634Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3915000/3915781/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3915781/lupa-sex-video-wuwa-bdsm/"
title = "Lupa sex video (WuWa) 露帕 BDSM"
image = "https://rule34video.com/contents/videos_screenshots/3915000/3915781/preview.jpg"
site = "rule34video.com"
desc = "Full version ( 08:47 ) here:\n\nhttps://www.fanbox.cc/@acidrain002/posts/10168368\n\nScene by hongcha & imsayaa34 & ToTheMoon & yurabe & yuukis & harada\nThis video made by Acidrain\nMore & Longer videos & Support creator: https://acidrain002.fanbox.cc"
