id = "1371531116254593075"
name = "Futa zani x Phoebe"
archived = true
locked = false
createdAt = "2025-05-12T16:54:59.931Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371531116254593075"
author = "korieuko"
content = "https://rule34video.com/video/3834241/futa-zani-x-phoebe/"
createdAt = "2025-05-12T16:54:59.931Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3834000/3834241/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3834241/futa-zani-x-phoebe/"
title = "futa zani x Phoebe"
image = "https://rule34video.com/contents/videos_screenshots/3834000/3834241/preview.jpg"
site = "rule34video.com"
desc = "https://www.pixiv.net/users/104994673"
