id = "1391362963746590805"
name = "Phoebe (X-ray) [Aung15]"
archived = true
locked = false
createdAt = "2025-07-06T10:19:40.831Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391362963746590805"
author = "korieuko"
content = "https://rule34video.com/video/3750801/phoebe-x-ray-aung15/"
createdAt = "2025-07-06T10:19:40.831Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3750000/3750801/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3750801/phoebe-x-ray-aung15/"
title = "Phoebe (X-ray) [Aung15]"
image = "https://rule34video.com/contents/videos_screenshots/3750000/3750801/preview.jpg"
site = "rule34video.com"
desc = "https://aung154.fanbox.cc/\nhttps://www.patreon.com/Aung15"
