id = "1432994813501771786"
name = "Phoebe Request 4"
archived = true
locked = false
createdAt = "2025-10-29T07:29:47.295Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1432994813501771786"
author = "korieuko"
content = "https://rule34video.com/video/4093224/phoebe-request-4/"
createdAt = "2025-10-29T07:29:47.295Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4093000/4093224/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4093224/phoebe-request-4/"
title = "Phoebe Request 4"
image = "https://rule34video.com/contents/videos_screenshots/4093000/4093224/preview.jpg"
site = "rule34video.com"
desc = "This one was missing from the prior phoebe upload so here it is."
