id = "1342747192003264552"
name = "Phoebe gangbang 煌めく星 kiramekuhoshi"
archived = true
locked = false
createdAt = "2025-02-22T06:37:57.610Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1342747192003264552"
author = "korieuko"
content = "https://rule34video.com/video/3701981/phoebe-gangbang-kiramekuhoshi/"
createdAt = "2025-02-22T06:37:57.610Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3701000/3701981/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3701981/phoebe-gangbang-kiramekuhoshi/"
title = "Phoebe gangbang 煌めく星 kiramekuhoshi"
image = "https://rule34video.com/contents/videos_screenshots/3701000/3701981/preview.jpg"
site = "rule34video.com"
desc = "artist : kiramekunohoshi\nKiramekunoshi\nhttps://sfl.gl/l7IRT23L\nHolomon X\nhttps://sfl.gl/cze0dwJ"
