id = "1392853198699630693"
name = "Phoebe Footjob (Sound)"
archived = true
locked = false
createdAt = "2025-07-10T13:01:20.531Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1392853198699630693"
author = "korieuko"
content = "https://rule34video.com/video/3924849/phoebe-footjob-sound/"
createdAt = "2025-07-10T13:01:20.531Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3924000/3924849/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3924849/phoebe-footjob-sound/"
title = "Phoebe Footjob (Sound)"
image = "https://rule34video.com/contents/videos_screenshots/3924000/3924849/preview.jpg"
site = "rule34video.com"
desc = "4k60fps & 1080p60fps version on my patreon↓\n\nwww.patreon.com/TY98\n\nVA: Misuzugon\nSFX: OpenNSFWSP\n \nScene by Kodoki"
