id = "1366079774656692387"
name = "[Chopsticker] Bunny Belle x Jane"
archived = true
locked = false
createdAt = "2025-04-27T15:53:18.813Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1366079774656692387"
author = "korieuko"
content = "https://rule34video.com/video/3613317/chopsticker-bunny-belle-x-jane/"
createdAt = "2025-04-27T15:53:18.813Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3613000/3613317/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3613317/chopsticker-bunny-belle-x-jane/"
title = "[Chopsticker] Bunny Belle x Jane"
image = "https://rule34video.com/contents/videos_screenshots/3613000/3613317/preview.jpg"
site = "rule34video.com"
desc = ""
