id = "1387460399695270038"
name = "[RougeNine] Belle, Caesar, & Burnice sex"
archived = true
locked = false
createdAt = "2025-06-25T15:52:17.055Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1387460399695270038"
author = "korieuko"
content = "https://rule34video.com/video/3901953/rougenine-belle-caesar-burnice-sex/"
createdAt = "2025-06-25T15:52:17.055Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
