id = "1317519651176972360"
name = "Belle Doggystyle [Imsayaa34]"
archived = true
locked = false
createdAt = "2024-12-14T15:52:43.172Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1317519651176972360"
author = "korieuko"
content = "https://rule34video.com/video/3614301/belle-doggystyle-imsayaa34/"
createdAt = "2024-12-14T15:52:43.172Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3614000/3614301/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3614301/belle-doggystyle-imsayaa34/"
title = "Belle Doggystyle [Imsayaa34]"
image = "https://rule34video.com/contents/videos_screenshots/3614000/3614301/preview.jpg"
site = "rule34video.com"
desc = ""
