id = "1478418977100136478"
name = "Belle-part2 (SeventyFives)"
archived = false
locked = false
createdAt = "2026-03-03T15:49:11.837Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1478418977100136478"
author = "korieuko"
content = "https://rule34video.com/video/4269038/belle-part2-seventyfives/"
createdAt = "2026-03-03T15:49:11.837Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4269000/4269038/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4269038/belle-part2-seventyfives/"
title = "belle-part2  (SeventyFives)"
image = "https://rule34video.com/contents/videos_screenshots/4269000/4269038/preview.jpg"
site = "rule34video.com"
desc = "CREDITS : SeventyFives3d\nhttps://patreon.com/SeventyFive\nhttps://x.com/SeventyFive3D"
