id = "1425141332640403548"
name = "Belle's dinner"
archived = true
locked = false
createdAt = "2025-10-07T15:22:51.547Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1425141332640403548"
author = "korieuko"
content = "https://rule34video.com/video/4063394/belle-s-dinner2/"
createdAt = "2025-10-07T15:22:51.547Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4063000/4063394/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4063394/belle-s-dinner2/"
title = "Belle's dinner"
image = "https://rule34video.com/contents/videos_screenshots/4063000/4063394/preview.jpg"
site = "rule34video.com"
desc = "X: @Pov_Loverr\n\nModels by: @HeliosPrimes\nMap by: @LamboXiao"
