id = "1442537758257188885"
name = "Belle x Wise - Pure Bonds [TwiistedLewds]"
archived = true
locked = false
createdAt = "2025-11-24T15:30:02.624Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442537758257188885"
author = "korieuko"
content = "https://rule34video.com/video/4118514/belle-x-wise-pure-bonds-twiistedlewds/"
createdAt = "2025-11-24T15:30:02.624Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4118000/4118514/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4118514/belle-x-wise-pure-bonds-twiistedlewds/"
title = "Belle x Wise - Pure Bonds [TwiistedLewds]"
image = "https://rule34video.com/contents/videos_screenshots/4118000/4118514/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/TwiistedLewds\nx.com/TwiistedLewds"
