id = "1375442871276273785"
name = "Belle_Zenless Zone Zero [Saucifer3D]"
archived = true
locked = false
createdAt = "2025-05-23T11:58:55.005Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375442871276273785"
author = "korieuko"
content = "https://rule34video.com/video/3846765/belle-zenless-zone-zero-saucifer3d/"
createdAt = "2025-05-23T11:58:55.005Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3846000/3846765/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3846765/belle-zenless-zone-zero-saucifer3d/"
title = "Belle_Zenless Zone Zero [Saucifer3D]"
image = "https://rule34video.com/contents/videos_screenshots/3846000/3846765/preview.jpg"
site = "rule34video.com"
desc = ":||"
