id = "1388025567655366727"
name = "Started with Miyabi and ended with my sister (ZZZ) cumshot"
archived = true
locked = false
createdAt = "2025-06-27T05:18:03.597Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388025567655366727"
author = "korieuko"
content = "https://rule34video.com/video/3812553/started-with-miyabi-and-ended-with-my-sister-zzz-cumshot/"
createdAt = "2025-06-27T05:18:03.597Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3812000/3812553/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3812553/started-with-miyabi-and-ended-with-my-sister-zzz-cumshot/"
title = "Started with Miyabi and ended with my sister (ZZZ) cumshot"
image = "https://rule34video.com/contents/videos_screenshots/3812000/3812553/preview.jpg"
site = "rule34video.com"
desc = "You can support and speed up my work by subscribing\nto Patreon, this is important to me so that I can\ncreate high-quality videos for you!\n\nSubscribe: https://www.patreon.com/ToonLeak\nhttps://subscribestar.adult/toonleak\n\nFollow: https://twitter.com/toonleak"
