id = "1480056273339809882"
name = "Wise helps Belle"
archived = false
locked = false
createdAt = "2026-03-08T04:15:13.680Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480056273339809882"
author = "korieuko"
content = "https://rule34video.com/video/4277365/wise-helps-belle/"
createdAt = "2026-03-08T04:15:13.680Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4277000/4277365/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4277365/wise-helps-belle/"
title = "Wise helps Belle"
image = "https://rule34video.com/contents/videos_screenshots/4277000/4277365/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/NDK7_3DNSFW"
