id = "1389228702566711297"
name = "Wrong Drink ( ZZZ )"
archived = true
locked = false
createdAt = "2025-06-30T12:58:53.313Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389228702566711297"
author = "korieuko"
content = "https://rule34video.com/video/3907605/wrong-drink-zzz/"
createdAt = "2025-06-30T12:58:53.313Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3907000/3907605/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3907605/wrong-drink-zzz/"
title = "Wrong Drink ( ZZZ )"
image = "https://rule34video.com/contents/videos_screenshots/3907000/3907605/preview.jpg"
site = "rule34video.com"
desc = "You can support and speed up my work by subscribing\nto Patreon, this is important to me so that I can\ncreate high-quality videos for you!\n\nSubscribe: https://www.patreon.com/ToonLeak\nhttps://subscribestar.adult/toonleak\n\nFollow: https://twitter.com/toonleak"
