id = "1468940579449864436"
name = "zzz belle paizuri sound ver lazyrice3d"
archived = true
locked = false
createdAt = "2026-02-05T12:05:25.737Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468940579449864436"
author = "korieuko"
content = "https://rule34video.com/video/4230102/zzz-belle-paizuri-sound-version-lazyrice3d/"
createdAt = "2026-02-05T12:05:25.737Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4230000/4230102/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4230102/zzz-belle-paizuri-sound-version-lazyrice3d/"
title = "ZZZ Belle Paizuri (Sound Version) - Lazyrice3D"
image = "https://rule34video.com/contents/videos_screenshots/4230000/4230102/preview.jpg"
site = "rule34video.com"
desc = ""
