id = "1314853426051682304"
name = "[Seru] Black Swan Demons"
archived = true
locked = false
createdAt = "2024-12-07T07:18:05.566Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314853426051682304"
author = "korieuko"
content = "https://avbebe.com/archives/220316"
createdAt = "2024-12-07T07:18:05.566Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
