id = "1314897103306362910"
name = "AlphaG] Capture Black Swan[中文字幕]"
archived = true
locked = false
createdAt = "2024-12-07T10:11:39.035Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314897103306362910"
author = "korieuko"
content = "https://avbebe.com/archives/237225"
createdAt = "2024-12-07T10:11:39.035Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/07/Capture-Black-Swan%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/237225"
title = "[AlphaG] Capture Black Swan[中文字幕]"
image = "https://avbebe.com/wp-content/uploads/2024/07/Capture-Black-Swan%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish(下載"
