id = "1323972296515391581"
name = "Black swan blowjob"
archived = true
locked = false
createdAt = "2025-01-01T11:13:13.705Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1323972296515391581"
author = "korieuko"
content = "https://rule34video.com/video/3476208/black-swan-blowjob/"
createdAt = "2025-01-01T11:13:13.705Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3476000/3476208/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3476208/black-swan-blowjob/"
title = "Black Swan blowjob"
image = "https://rule34video.com/contents/videos_screenshots/3476000/3476208/preview.jpg"
site = "rule34video.com"
desc = "Yeahhh"
