id = "1391407630064422932"
name = "[Rosen] Shorekeeper X Rover"
archived = true
locked = false
createdAt = "2025-07-06T13:17:10.111Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407630064422932"
author = "korieuko"
content = "https://rule34video.com/video/3610491/rosen-shorekeeper-x-rover/"
createdAt = "2025-07-06T13:17:10.111Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3610000/3610491/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3610491/rosen-shorekeeper-x-rover/"
title = "[Rosen] Shorekeeper X Rover"
image = "https://rule34video.com/contents/videos_screenshots/3610000/3610491/preview.jpg"
site = "rule34video.com"
desc = "https://www.patreon.com/RosenVier"
