id = "1391407749136515082"
name = "■【TheShorekeeper】1006 completely naked Sound Ver"
archived = true
locked = false
createdAt = "2025-07-06T13:17:38.500Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407749136515082"
author = "korieuko"
content = "https://rule34video.com/video/3586377/theshorekeeper-1006-completely-naked-sound-ver/"
createdAt = "2025-07-06T13:17:38.500Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
