id = "1391407168523206687"
name = "[WW] Shorekeeper x Rover"
archived = true
locked = false
createdAt = "2025-07-06T13:15:20.071Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407168523206687"
author = "korieuko"
content = "https://rule34video.com/video/3801133/ww-shorekeeper-x-rover/"
createdAt = "2025-07-06T13:15:20.071Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
