id = "1391407042673119233"
name = "Big ass Mommy Strikes Back"
archived = true
locked = false
createdAt = "2025-07-06T13:14:50.066Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407042673119233"
author = "korieuko"
content = "https://rule34video.com/video/3876597/big-ass-mommy-strikes-back/"
createdAt = "2025-07-06T13:14:50.066Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
