id = "1391407858800787528"
name = "Insect & Tentacle"
archived = true
locked = false
createdAt = "2025-07-06T13:18:04.646Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407858800787528"
author = "korieuko"
content = "https://rule34video.com/video/3570672/insect-tentacle/"
createdAt = "2025-07-06T13:18:04.646Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3570000/3570672/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3570672/insect-tentacle/"
title = "Insect & Tentacle"
image = "https://rule34video.com/contents/videos_screenshots/3570000/3570672/preview.jpg"
site = "rule34video.com"
desc = "Artist: Y4Fritt\nY4Fritt In iwara: https://www.iwara.tv/profile/1litchi\n\nI do not own any video uploaded, all rights to their authors\nMy twitter:\nhttps://x.com/ZarKurx?s=09"
