id = "1429128898054066268"
name = "RDreamer The Shorekeeper PT2 FULL"
archived = true
locked = false
createdAt = "2025-10-18T15:28:01.227Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1429128898054066268"
author = "korieuko"
content = "https://rule34video.com/video/4077459/rdreamer-the-shorekeeper-pt2-full/"
createdAt = "2025-10-18T15:28:01.227Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4077000/4077459/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4077459/rdreamer-the-shorekeeper-pt2-full/"
title = "RDreamer The Shorekeeper PT2 FULL"
image = "https://rule34video.com/contents/videos_screenshots/4077000/4077459/preview.jpg"
site = "rule34video.com"
desc = ""
