id = "1404844675071868958"
name = "Rover fucks Shorekeeper"
archived = true
locked = false
createdAt = "2025-08-12T15:11:11.289Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404844675071868958"
author = "korieuko"
content = "https://rule34video.com/video/3963346/rover-fucks-shorekeeper/"
createdAt = "2025-08-12T15:11:11.289Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3963000/3963346/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3963346/rover-fucks-shorekeeper/"
title = "Rover fucks Shorekeeper"
image = "https://rule34video.com/contents/videos_screenshots/3963000/3963346/preview.jpg"
site = "rule34video.com"
desc = "This animation started as a render commission but I decided to turn it into a loop.\nIt's 12 seconds long, features moaning, rustling sheets, plaps and some color editing.\n\nUnmarked Version:\nhttps://www.patreon.com/posts/br33ding-early-135178308\n\nCredits:\nShorekeeper: @DaB_neko\nRover: @HeliosPrimes\nVoice: @Misuzugon\nEnvironment: 5th-Dimension"
