id = "1391407250471522324"
name = "ShoreKeeper Sex Ashore"
archived = true
locked = false
createdAt = "2025-07-06T13:15:39.609Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407250471522324"
author = "korieuko"
content = "https://rule34video.com/video/3740229/shorekeeper-sex-ashore/"
createdAt = "2025-07-06T13:15:39.609Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3740000/3740229/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3740229/shorekeeper-sex-ashore/"
title = "ShoreKeeper Sex Ashore"
image = "https://rule34video.com/contents/videos_screenshots/3740000/3740229/preview.jpg"
site = "rule34video.com"
desc = "Artist: ENE\n\nhttps://www.iwara.tv/profile/user3856646\n\nI do not own any video uploaded, all rights to their authors"
