id = "1410427829262352454"
name = "Shorekeeper Footjob"
archived = true
locked = false
createdAt = "2025-08-28T00:56:38.978Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1410427829262352454"
author = "korieuko"
content = "https://rule34video.com/video/3997913/shorekeeper-footjob/"
createdAt = "2025-08-28T00:56:38.978Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3997000/3997913/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3997913/shorekeeper-footjob/"
title = "Shorekeeper Footjob"
image = "https://rule34video.com/contents/videos_screenshots/3997000/3997913/preview.jpg"
site = "rule34video.com"
desc = ""
