id = "1391407432902901850"
name = "Shorekeeper_bondage training"
archived = true
locked = false
createdAt = "2025-07-06T13:16:23.104Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391407432902901850"
author = "korieuko"
content = "https://rule34video.com/video/3688881/shorekeeper-bondage-training/"
createdAt = "2025-07-06T13:16:23.104Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
