id = "1371869957863903273"
name = "Shorekeeper [Akt]"
archived = true
locked = false
createdAt = "2025-05-13T15:21:26.066Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371869957863903273"
author = "korieuko"
content = "https://rule34video.com/video/3822977/shorekeeper-akt/"
createdAt = "2025-05-13T15:21:26.066Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3822000/3822977/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3822977/shorekeeper-akt/"
title = "Shorekeeper [Akt]"
image = "https://rule34video.com/contents/videos_screenshots/3822000/3822977/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://akt.fanbox.cc\nhttps://www.patreon.com/c/akt_shop\nhttps://ganknow.com/animationakt"
