id = "1372129530512408576"
name = "Two Hilichurls for Shorekeeper"
archived = true
locked = false
createdAt = "2025-05-14T08:32:53.008Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1372129530512408576"
author = "korieuko"
content = "https://rule34video.com/video/3835193/two-hilichurls-for-shorekeeper/"
createdAt = "2025-05-14T08:32:53.008Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3835000/3835193/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3835193/two-hilichurls-for-shorekeeper/"
title = "Two Hilichurls for Shorekeeper"
image = "https://rule34video.com/contents/videos_screenshots/3835000/3835193/preview.jpg"
site = "rule34video.com"
desc = ""
