id = "1314904092971237457"
name = "リル] 24.11.01 霊砂"
archived = true
locked = false
createdAt = "2024-12-07T10:39:25.501Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314904092971237457"
author = "korieuko"
content = "https://avbebe.com/archives/179442"
createdAt = "2024-12-07T10:39:25.501Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
