id = "1337381894064574464"
name = "2K Yinlin was defeated 「Tir_Al」"
archived = true
locked = false
createdAt = "2025-02-07T11:18:10.899Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1337381894064574464"
author = "korieuko"
content = "https://rule34video.com/video/3681073/2k-yinlin-was-defeated-tir-al/"
createdAt = "2025-02-07T11:18:10.899Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3681000/3681073/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3681073/2k-yinlin-was-defeated-tir-al/"
title = "2K Yinlin was defeated 「Tir_Al」"
image = "https://rule34video.com/contents/videos_screenshots/3681000/3681073/preview.jpg"
site = "rule34video.com"
desc = "I spliced ​​the two parts together."

[[messages]]
id = "1371871463203799225"
author = "korieuko"
content = "Well animated."
createdAt = "2025-05-13T15:27:24.967Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
