id = "1398286653340258344"
name = "Yinlin's Scouting Mission gone wrong [Full]"
archived = true
locked = false
createdAt = "2025-07-25T12:51:57.066Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1398286653340258344"
author = "korieuko"
content = "https://rule34video.com/video/3949121/yinlin-s-scouting-mission-gone-wrong/"
createdAt = "2025-07-25T12:51:57.066Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3949000/3949121/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3949121/yinlin-s-scouting-mission-gone-wrong/"
title = "Yinlin's Scouting Mission gone wrong"
image = "https://rule34video.com/contents/videos_screenshots/3949000/3949121/preview.jpg"
site = "rule34video.com"
desc = "All angles\r\n\r\nYinlin from Tir_Al with subtitles, for ambience enjoyers\r\n\r\nhttps://www.patreon.com/tir_al\r\nhttps://x.com/tir_al_"
