id = "1314896340186300448"
name = "Yinlin's dog x naked"
archived = true
locked = false
createdAt = "2024-12-07T10:08:37.093Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314896340186300448"
author = "korieuko"
content = "https://avbebe.com/archives/241426"
createdAt = "2024-12-07T10:08:37.093Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
