id = "1388430894968213565"
name = "Strinova - Flavia sex party"
archived = true
locked = false
createdAt = "2025-06-28T08:08:41.159Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388430894968213565"
author = "korieuko"
content = "https://rule34video.com/video/3857965/flavia-sex-party-strinova/"
createdAt = "2025-06-28T08:08:41.159Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3857000/3857965/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3857965/flavia-sex-party-strinova/"
title = "Strinova - Flavia sex party"
image = "https://rule34video.com/contents/videos_screenshots/3857000/3857965/preview.jpg"
site = "rule34video.com"
desc = "Sorry for bad quality, idk why this website can't upload high quality because it said video already uploaded? \n\nyou can download the original quality source here:\nhttps://www.iwara.tv/video/ybozekFiOzYHZE/strinova\n\n( remember to make account first so you can download the original)"
