id = "1413180675112304640"
name = "Strinova - Flavia maid skin"
archived = true
locked = false
createdAt = "2025-09-04T15:15:28.574Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413180675112304640"
author = "korieuko"
content = "https://rule34video.com/video/3971475/strinova-flavia-maid-skin/"
createdAt = "2025-09-04T15:15:28.574Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3971000/3971475/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3971475/strinova-flavia-maid-skin/"
title = "Strinova - Flavia maid skin"
image = "https://rule34video.com/contents/videos_screenshots/3971000/3971475/preview.jpg"
site = "rule34video.com"
desc = "Note: I don't own/claimed this video, I just re uploaded.\n\nPlease follow & support the artist below\nArtist Name: 达ling丶\nLink original:\nhttps://www.iwara.tv/video/0pN6kQGewr43ky/25"
