id = "1346350186137518091"
name = "[Rinhee] Ako (Turkce ceviri)"
archived = true
locked = false
createdAt = "2025-03-04T05:14:58.352Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1346350186137518091"
author = "korieuko"
content = "https://rule34video.com/video/3725593/rinhee-ako-turkce-ceviri/"
createdAt = "2025-03-04T05:14:58.352Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3725000/3725593/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3725593/rinhee-ako-turkce-ceviri/"
title = "[Rinhee] Ako (Turkce ceviri)"
image = "https://rule34video.com/contents/videos_screenshots/3725000/3725593/preview.jpg"
site = "rule34video.com"
desc = "ai ile cevrilmistir"
