id = "1389964135143309392"
name = "[AidenHet] Yanagi Temptation"
archived = true
locked = false
createdAt = "2025-07-02T13:41:14.103Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389964135143309392"
author = "korieuko"
content = "https://rule34video.com/video/3911097/aidenhet-yanagi-temptation/"
createdAt = "2025-07-02T13:41:14.103Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3911000/3911097/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3911097/aidenhet-yanagi-temptation/"
title = "[AidenHet] Yanagi Temptation"
image = "https://rule34video.com/contents/videos_screenshots/3911000/3911097/preview.jpg"
site = "rule34video.com"
desc = ""
