id = "1323971789596004415"
name = "【Tsukishiro Yanagi】11.17 half"
archived = true
locked = false
createdAt = "2025-01-01T11:11:12.846Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1323971789596004415"
author = "korieuko"
content = "https://rule34video.com/video/3630237/tsukishiro-yanagi-11-17-half-undressinga-sound-ver/"
createdAt = "2025-01-01T11:11:12.846Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3630000/3630237/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3630237/tsukishiro-yanagi-11-17-half-undressinga-sound-ver/"
title = "■【Tsukishiro Yanagi】11.17 half undressingA Sound Ver"
image = "https://rule34video.com/contents/videos_screenshots/3630000/3630237/preview.jpg"
site = "rule34video.com"
desc = "■【月城柳】11.17月城柳 半脱A 声音版本Sound Ver"
