id = "1389229137029500928"
name = "Miyabi X Yanagi"
archived = true
locked = false
createdAt = "2025-06-30T13:00:36.897Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389229137029500928"
author = "korieuko"
content = "https://rule34video.com/video/3850137/miyabi-x-yanagi/"
createdAt = "2025-06-30T13:00:36.897Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3850000/3850137/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3850137/miyabi-x-yanagi/"
title = "Miyabi X Yanagi"
image = "https://rule34video.com/contents/videos_screenshots/3850000/3850137/preview.jpg"
site = "rule34video.com"
desc = "4k60fps & 1080p60fps↓\n\nhttp://patreon.com/TY98\n\nVA by geministarsign1 | LecheryAmoreVA\nSFX by OpenNSFW\nscene by hongcha"
