id = "1426231274523070526"
name = "Yanagi overtime (Hoyocinema)"
archived = true
locked = false
createdAt = "2025-10-10T15:33:53.942Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1426231274523070526"
author = "korieuko"
content = "https://rule34video.com/video/4033357/yanagi-overtime-hoyocinema/"
createdAt = "2025-10-10T15:33:53.942Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4033000/4033357/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4033357/yanagi-overtime-hoyocinema/"
title = "Yanagi overtime (Hoyocinema)"
image = "https://rule34video.com/contents/videos_screenshots/4033000/4033357/preview.jpg"
site = "rule34video.com"
desc = "Full version: https://www.patreon.com/HoyoCinema"
