id = "1388902456007856210"
name = "Yanagi Handjob - (Orangedonut33)"
archived = true
locked = false
createdAt = "2025-06-29T15:22:30.072Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388902456007856210"
author = "korieuko"
content = "https://rule34video.com/video/3643400/yanagi-handjob-orangedonut33/"
createdAt = "2025-06-29T15:22:30.072Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3643000/3643400/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3643400/yanagi-handjob-orangedonut33/"
title = "Yanagi Handjob - (Orangedonut33)"
image = "https://rule34video.com/contents/videos_screenshots/3643000/3643400/preview.jpg"
site = "rule34video.com"
desc = "Animation made by Orangedount33. This was not made by me, I do not take any credit.\n\nCheck the artist's other works:\nhttps://x.com/orangedonut33?lang=en\nhttps://www.patreon.com/OrangeDonut"
