id = "1389229298807996486"
name = "Yanagi"
archived = true
locked = false
createdAt = "2025-06-30T13:01:15.468Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389229298807996486"
author = "korieuko"
content = "https://rule34video.com/video/3714221/yanagi/"
createdAt = "2025-06-30T13:01:15.468Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3714000/3714221/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3714221/yanagi/"
title = "Yanagi"
image = "https://rule34video.com/contents/videos_screenshots/3714000/3714221/preview.jpg"
site = "rule34video.com"
desc = "new yanagi video\n4k 60fps ：https://www.patreon.com/c/Kayasami"
