id = "1442861420013158531"
name = "【horizontal】2025.11 Iuno_Bottomless"
archived = true
locked = false
createdAt = "2025-11-25T12:56:09.600Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442861420013158531"
author = "korieuko"
content = "https://rule34video.com/video/4111387/horizontal-2025-11-iuno-bottomless/"
createdAt = "2025-11-25T12:56:09.600Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4111000/4111387/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4111387/horizontal-2025-11-iuno-bottomless/"
title = "【horizontal】2025.11 Iuno_Bottomless"
image = "https://rule34video.com/contents/videos_screenshots/4111000/4111387/preview.jpg"
site = "rule34video.com"
desc = "Iuno_Bottomless.mp4"
