id = "1410623276409159784"
name = "A Day With Iuno"
archived = true
locked = false
createdAt = "2025-08-28T13:53:17.209Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1410623276409159784"
author = "korieuko"
content = "https://rule34video.com/video/3992069/a-day-with-iuno/"
createdAt = "2025-08-28T13:53:17.209Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3992000/3992069/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3992069/a-day-with-iuno/"
title = "A Day With Iuno"
image = "https://rule34video.com/contents/videos_screenshots/3992000/3992069/preview.jpg"
site = "rule34video.com"
desc = "Some scenes extended. All of them upscaled. Arranged for continuity."
