id = "1429129018896027648"
name = "ALT Iuno Wuthering wave [saucifer3d]"
archived = true
locked = false
createdAt = "2025-10-18T15:28:30.038Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1429129018896027648"
author = "korieuko"
content = "https://rule34video.com/video/4067022/alt-iuno-wuthering-wave-saucifer3d/"
createdAt = "2025-10-18T15:28:30.038Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4067000/4067022/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4067022/alt-iuno-wuthering-wave-saucifer3d/"
title = "ALT Iuno Wuthering wave [saucifer3d]"
image = "https://rule34video.com/contents/videos_screenshots/4067000/4067022/preview.jpg"
site = "rule34video.com"
desc = ""
