id = "1385219224770838591"
name = "Iluno Half Naked Ver. (Wuthering waves) [Realize]"
archived = true
locked = false
createdAt = "2025-06-19T11:26:39.314Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1385219224770838591"
author = "korieuko"
content = "https://rule34video.com/video/3889205/iluno-half-naked-ver-wuthering-waves-realize/"
createdAt = "2025-06-19T11:26:39.314Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3889000/3889205/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3889205/iluno-half-naked-ver-wuthering-waves-realize/"
title = "Iluno Half Naked Ver. (Wuthering waves) [Realize]"
image = "https://rule34video.com/contents/videos_screenshots/3889000/3889205/preview.jpg"
site = "rule34video.com"
desc = "https://realize.fanbox.cc/\n\n**Please Support the artist !! **"
