id = "1447073545669840937"
name = "Iuno [Tir_Al]"
archived = true
locked = false
createdAt = "2025-12-07T03:53:38.614Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1447073545669840937"
author = "korieuko"
content = "https://rule34video.com/video/4139799/iuno-tir-al2/"
createdAt = "2025-12-07T03:53:38.614Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4139000/4139799/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4139799/iuno-tir-al2/"
title = "Iuno [Tir_Al]"
image = "https://rule34video.com/contents/videos_screenshots/4139000/4139799/preview.jpg"
site = "rule34video.com"
desc = "Iuno [Tir_Al]"
