id = "1410623184952365179"
name = "Iuno x Doggos"
archived = true
locked = false
createdAt = "2025-08-28T13:52:55.404Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1410623184952365179"
author = "korieuko"
content = "https://rule34video.com/video/3987761/iuno-x-doggos/"
createdAt = "2025-08-28T13:52:55.404Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3987000/3987761/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3987761/iuno-x-doggos/"
title = "Iuno x Doggos"
image = "https://rule34video.com/contents/videos_screenshots/3987000/3987761/preview.jpg"
site = "rule34video.com"
desc = "Artist: lumikiru"
