id = "1447930082286108784"
name = "Iuno's fall to the Dark Tide [720p]"
archived = true
locked = false
createdAt = "2025-12-09T12:37:12.857Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447930082286108784"
author = "korieuko"
content = "https://rule34video.com/video/4142331/iuno-s-fall-to-the-dark-tide-720p2/"
createdAt = "2025-12-09T12:37:12.857Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4142000/4142331/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4142331/iuno-s-fall-to-the-dark-tide-720p2/"
title = "Iuno's fall to the Dark Tide [720p]"
image = "https://rule34video.com/contents/videos_screenshots/4142000/4142331/preview.jpg"
site = "rule34video.com"
desc = "Iuno from Tir_AL with subtitles, for ambience enjoyers\n\nFor 4k and preggers version, go support the artist:\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"
