id = "1396158500731879587"
name = "Iuno sex"
archived = true
locked = false
createdAt = "2025-07-19T15:55:25.945Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1396158500731879587"
author = "korieuko"
content = "https://rule34video.com/video/3940241/iuno-sex/"
createdAt = "2025-07-19T15:55:25.945Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3940000/3940241/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3940241/iuno-sex/"
title = "Iuno sex"
image = "https://rule34video.com/contents/videos_screenshots/3940000/3940241/preview.jpg"
site = "rule34video.com"
desc = ""
