id = "1390122420064620635"
name = "Iuno Sex Part 1 (RD)"
archived = true
locked = false
createdAt = "2025-07-03T00:10:12.169Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1390122420064620635"
author = "korieuko"
content = "https://rule34video.com/video/3912701/iuno-sex-part-1-rd/"
createdAt = "2025-07-03T00:10:12.169Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3912000/3912701/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3912701/iuno-sex-part-1-rd/"
title = "Iuno Sex Part 1 (RD)"
image = "https://rule34video.com/contents/videos_screenshots/3912000/3912701/preview.jpg"
site = "rule34video.com"
desc = ""
