id = "1395754036837486623"
name = "Luno_Wuthering Waves [6aminoac9]"
archived = true
locked = false
createdAt = "2025-07-18T13:08:14.238Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1395754036837486623"
author = "korieuko"
content = "https://rule34video.com/video/3937097/luno-wuthering-waves-6aminoac9/"
createdAt = "2025-07-18T13:08:14.238Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
