id = "1429127659144609973"
name = "[4K] Vivian [Shirukinsfw]"
archived = true
locked = false
createdAt = "2025-10-18T15:23:05.848Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1429127659144609973"
author = "korieuko"
content = "https://rule34video.com/video/4065862/4k-vivian-shirukinsfw/"
createdAt = "2025-10-18T15:23:05.848Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4065000/4065862/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4065862/4k-vivian-shirukinsfw/"
title = "[4K] Vivian [Shirukinsfw]"
image = "https://rule34video.com/contents/videos_screenshots/4065000/4065862/preview.jpg"
site = "rule34video.com"
desc = ""
