id = "1480058383036973240"
name = "Vivian's FeIIatio [Renetan]"
archived = false
locked = false
createdAt = "2026-03-08T04:23:36.671Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480058383036973240"
author = "korieuko"
content = "https://rule34video.com/video/4243110/vivian-s-feiiatio-renetan/"
createdAt = "2026-03-08T04:23:36.671Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4243000/4243110/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4243110/vivian-s-feiiatio-renetan/"
title = "Vivian's FeIIatio [Renetan]"
image = "https://rule34video.com/contents/videos_screenshots/4243000/4243110/preview.jpg"
site = "rule34video.com"
desc = ""
