id = "1430934158288359454"
name = "Vivian – Until You’re Mine (Doggy)"
archived = true
locked = false
createdAt = "2025-10-23T15:01:28.807Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1430934158288359454"
author = "korieuko"
content = "https://rule34video.com/video/4084631/vivian-until-you-re-mine-doggy/"
createdAt = "2025-10-23T15:01:28.807Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
