id = "1480058693197500497"
name = "Vivian_Blowjob"
archived = false
locked = false
createdAt = "2026-03-08T04:24:50.619Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480058693197500497"
author = "korieuko"
content = "https://rule34video.com/video/4119142/vivian-blowjob/"
createdAt = "2026-03-08T04:24:50.619Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4119000/4119142/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4119142/vivian-blowjob/"
title = "Vivian_Blowjob"
image = "https://rule34video.com/contents/videos_screenshots/4119000/4119142/preview.jpg"
site = "rule34video.com"
desc = ""
