id = "1380802998497968139"
name = "Vivian X Wise Missionary"
archived = true
locked = false
createdAt = "2025-06-07T06:58:08.921Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1380802998497968139"
author = "korieuko"
content = "https://rule34video.com/video/3871257/vivian-x-wise-missionary2/"
createdAt = "2025-06-07T06:58:08.921Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
