id = "1384916112411594853"
name = "Vivian X Wise Doggy & Cowgirl"
archived = true
locked = false
createdAt = "2025-06-18T15:22:11.696Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1384916112411594853"
author = "korieuko"
content = "https://rule34video.com/video/3889621/vivian-x-wise-doggy-cowgirl/"
createdAt = "2025-06-18T15:22:11.696Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3889000/3889621/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3889621/vivian-x-wise-doggy-cowgirl/"
title = "Vivian X Wise Doggy & Cowgirl"
image = "https://rule34video.com/contents/videos_screenshots/3889000/3889621/preview.jpg"
site = "rule34video.com"
desc = "No watermark: patreon.com/c/EcchiWaffle\n\nAnimation - kiramekuhoshi\nVivian - Misuzugon (voice pack)\nAudio - EcchiWaffle"
