id = "1442537451934449754"
name = "Vivian (ZZZ)"
archived = true
locked = false
createdAt = "2025-11-24T15:28:49.591Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442537451934449754"
author = "korieuko"
content = "https://rule34video.com/video/4118862/vivian-zzz/"
createdAt = "2025-11-24T15:28:49.591Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4118000/4118862/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4118862/vivian-zzz/"
title = "Vivian (ZZZ)"
image = "https://rule34video.com/contents/videos_screenshots/4118000/4118862/preview.jpg"
site = "rule34video.com"
desc = "full hd, no watermark, no mosaic uncropped\nhttps://patreon.com/thorru\n\nhttps://x.com/thorru_\nhttps://www.pixiv.net/users/68278542"
