id = "1424780082383163455"
name = "Vivian x Wise = Wisevian [Kiramekuhoshi]"
archived = true
locked = false
createdAt = "2025-10-06T15:27:22.774Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1424780082383163455"
author = "korieuko"
content = "https://rule34video.com/video/3891477/vivian-x-wise-wisevian-kiramekuhoshi/"
createdAt = "2025-10-06T15:27:22.774Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3891000/3891477/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3891477/vivian-x-wise-wisevian-kiramekuhoshi/"
title = "Vivian x Wise = Wisevian [Kiramekuhoshi]"
image = "https://rule34video.com/contents/videos_screenshots/3891000/3891477/preview.jpg"
site = "rule34video.com"
desc = "long story short: please add tags to the videos.\nAlso, wanted to re upload cuz some users from the original upload were complaining about the music, like. What the hell it's wrong with ya'll? It's awesome!!! Either enjoy it or bug out into some boring Koikatsu slop if you want.\n\nAs always, hope ya'll enjoy this re upload and remember to support ..."
