id = "1480058211032895519"
name = "Vivian NTS"
archived = false
locked = false
createdAt = "2026-03-08T04:22:55.662Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480058211032895519"
author = "korieuko"
content = "https://rule34video.com/video/4265538/vivian-nts/"
createdAt = "2026-03-08T04:22:55.662Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4265000/4265538/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4265538/vivian-nts/"
title = "Vivian NTS"
image = "https://rule34video.com/contents/videos_screenshots/4265000/4265538/preview.jpg"
site = "rule34video.com"
desc = ""
