id = "1429128114599891016"
name = "Zenless's summer is not OVER yet!"
archived = true
locked = false
createdAt = "2025-10-18T15:24:54.437Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1429128114599891016"
author = "korieuko"
content = "https://rule34video.com/video/4072195/zenless-s-summer-is-not-over-yet/"
createdAt = "2025-10-18T15:24:54.437Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4072000/4072195/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4072195/zenless-s-summer-is-not-over-yet/"
title = "Zenless's summer is not OVER yet!"
image = "https://rule34video.com/contents/videos_screenshots/4072000/4072195/preview.jpg"
site = "rule34video.com"
desc = "Many people have been saying that this video features the GREAT voice actress Miko Desh voicing probably the hottest summer character in the HIT GAME Zenless Zone Zero, featuring SFX from the GREAT collaboration of talent at the @OpenNSFWSP on twitter with SPECTACULAR work for the community.  Some say you might find out more Patreon.com/Inanon, ..."
