id = "1366079880751747172"
name = "[ZZZ] Ellen x Rina"
archived = true
locked = false
createdAt = "2025-04-27T15:53:44.108Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1366079880751747172"
author = "korieuko"
content = "https://rule34video.com/video/3547553/zzz-ellen-x-rina/"
createdAt = "2025-04-27T15:53:44.108Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3547000/3547553/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3547553/zzz-ellen-x-rina/"
title = "[ZZZ] Ellen x Rina"
image = "https://rule34video.com/contents/videos_screenshots/3547000/3547553/preview.jpg"
site = "rule34video.com"
desc = "Artist Chopsticker\nhttps://www.pixiv.net/en/users/21228974\nhttps://www.patreon.com/user?u=45941308\n\nI do not own any video uploaded, all rights to their authors"

[[messages]]
id = "1373281238512828419"
author = "korieuko"
content = "Good sound."
createdAt = "2025-05-17T12:49:21.593Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
