id = "1448552459336290356"
name = "Ellen on the beach"
archived = true
locked = false
createdAt = "2025-12-11T05:50:19.109Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1448552459336290356"
author = "korieuko"
content = "https://rule34video.com/video/4145263/ellen-on-the-beach/"
createdAt = "2025-12-11T05:50:19.109Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4145000/4145263/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4145263/ellen-on-the-beach/"
title = "Ellen on the beach"
image = "https://rule34video.com/contents/videos_screenshots/4145000/4145263/preview.jpg"
site = "rule34video.com"
desc = "Animation by Lemon T\n\nSound edit by me, it's not great but thought it would be better than no sound\n\nSupport the artist : https://www.patreon.com/LemonT"
