id = "1373176186317963354"
name = "Ellen Joe (4K) [VikLodn]"
archived = true
locked = false
createdAt = "2025-05-17T05:51:55.198Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1373176186317963354"
author = "korieuko"
content = "https://rule34video.com/video/3840213/ellen-joe-4k-viklodn/"
createdAt = "2025-05-17T05:51:55.198Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3840000/3840213/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3840213/ellen-joe-4k-viklodn/"
title = "Ellen Joe (4K) [VikLodn]"
image = "https://rule34video.com/contents/videos_screenshots/3840000/3840213/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/VikLodn\nx.com/VikLodn"
