id = "1315180747824431125"
name = "[Rinjo_18] Burnice & Caesar"
archived = true
locked = false
createdAt = "2024-12-08T04:58:45.158Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1315180747824431125"
author = "korieuko"
content = "https://avbebe.com/archives/264056"
createdAt = "2024-12-08T04:58:45.158Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/11/Rinjo_18-Burnice-Caesar.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/264056"
title = "[Rinjo_18] Burnice & Caesar"
image = "https://avbebe.com/wp-content/uploads/2024/11/Rinjo_18-Burnice-Caesar.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe streamwish Av"
