id = "1424052610180186122"
name = "Caesar Missionary [Infected Heart]"
archived = true
locked = false
createdAt = "2025-10-04T15:16:39.885Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1424052610180186122"
author = "korieuko"
content = "https://rule34video.com/video/4059310/caesar-missionary-infected-heart/"
createdAt = "2025-10-04T15:16:39.885Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4059000/4059310/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4059310/caesar-missionary-infected-heart/"
title = "Caesar Missionary [Infected Heart]"
image = "https://rule34video.com/contents/videos_screenshots/4059000/4059310/preview.jpg"
site = "rule34video.com"
desc = "http://linktr.ee/Infected_Heart\nhttps://www.patreon.com/Infected_Heart\nhttps://x.com/heart_infected"
