id = "1452859054895403008"
name = "Cyrene [Yuluer] Full scenes Uncensored"
archived = true
locked = false
createdAt = "2025-12-23T03:03:11.503Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1452859054895403008"
author = "korieuko"
content = "https://rule34video.com/video/4156002/cyrene-yuluer-full-scenes-uncensored/"
createdAt = "2025-12-23T03:03:11.503Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4156000/4156002/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4156002/cyrene-yuluer-full-scenes-uncensored/"
title = "Cyrene [Yuluer] Full scenes Uncensored"
image = "https://rule34video.com/contents/videos_screenshots/4156000/4156002/preview.jpg"
site = "rule34video.com"
desc = "All credits for Yuluer.\nSupport the author here :\nhttps://yuluer.fanbox.cc\n\nCredit to yuluer to give us the best kind of 3D lovey-dovey sex scenes, I love the warm atmospheres of his videos.\nFor thoses who asked for the music, Yulu generally took them from right-free channels, I manage to find the ones in Citlali and Furina videos thanks to Shaz..."
