id = "1468938538438365330"
name = "Laevatain x Mob video (Arknights Endfield) NTR"
archived = true
locked = false
createdAt = "2026-02-05T11:57:19.122Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468938538438365330"
author = "korieuko"
content = "https://rule34video.com/video/4229338/laevatain-x-mob-video-arknights-endfield-ntr/"
createdAt = "2026-02-05T11:57:19.122Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4229000/4229338/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4229338/laevatain-x-mob-video-arknights-endfield-ntr/"
title = "Laevatain x Mob video (Arknights Endfield) NTR"
image = "https://rule34video.com/contents/videos_screenshots/4229000/4229338/preview.jpg"
site = "rule34video.com"
desc = "Full version (10:00) here:\n\nhttps://www.fanbox.cc/@acidrain002/posts/11325892\n\nScene by hongcha & imsayaa34 & ToTheMoon & yurabe & yuukis & harada\nThis video made by Acidrain\nMore & Longer videos & Support creator: https://acidrain002.fanbox.cc"
