id = "1479808581086740512"
name = "Laevatain"
archived = false
locked = false
createdAt = "2026-03-07T11:50:59.245Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1479808581086740512"
author = "korieuko"
content = "https://rule34video.com/video/4275625/laevatain/"
createdAt = "2026-03-07T11:50:59.245Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4275000/4275625/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4275625/laevatain/"
title = "Laevatain"
image = "https://rule34video.com/contents/videos_screenshots/4275000/4275625/preview.jpg"
site = "rule34video.com"
desc = "X : https://x.com/Cokonut_NSFW\nIwara : https://www.iwara.tv/profile/cokonutjellynsfw\nPatreon : https://www.patreon.com/CokonutJelly (Uncensored & Censored)\n\nIf you like my work you can support me here for the 4K, no-watermark, uncensored version."
