id = "1348499264749178960"
name = "Houshou Marine [Mochidora2]"
archived = true
locked = false
createdAt = "2025-03-10T03:34:38.621Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1348499264749178960"
author = "korieuko"
content = "https://rule34video.com/video/3161979/houshou-marine-mochidora2/"
createdAt = "2025-03-10T03:34:38.621Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3161000/3161979/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3161979/houshou-marine-mochidora2/"
title = "Houshou Marine [Mochidora2]"
image = "https://rule34video.com/contents/videos_screenshots/3161000/3161979/preview.jpg"
site = "rule34video.com"
desc = ""
