id = "1396157924878979231"
name = "Kronii [AssDepik]"
archived = true
locked = false
createdAt = "2025-07-19T15:53:08.651Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1396157924878979231"
author = "korieuko"
content = "https://rule34video.com/video/3927765/kronii-assdepik/"
createdAt = "2025-07-19T15:53:08.651Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3927000/3927765/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3927765/kronii-assdepik/"
title = "Kronii [AssDepik]"
image = "https://rule34video.com/contents/videos_screenshots/3927000/3927765/preview.jpg"
site = "rule34video.com"
desc = ""
