id = "1348499544861708348"
name = "Ouro Kronii [BjHj][Nekololisama]"
archived = true
locked = false
createdAt = "2025-03-10T03:35:45.405Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1348499544861708348"
author = "korieuko"
content = "https://rule34video.com/video/3303649/ouro-kronii-bjhj-nekololisama/"
createdAt = "2025-03-10T03:35:45.405Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3303000/3303649/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3303649/ouro-kronii-bjhj-nekololisama/"
title = "Ouro Kronii [BjHj][Nekololisama]"
image = "https://rule34video.com/contents/videos_screenshots/3303000/3303649/preview.jpg"
site = "rule34video.com"
desc = "https://twitter.com/neko__nsfw?lang=de\nhttps://www.patreon.com/NEKO_NSFW"
