id = "1388902068315750643"
name = "(4K60fps) bad kitty [RedRainSFM]"
archived = true
locked = false
createdAt = "2025-06-29T15:20:57.639Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388902068315750643"
author = "korieuko"
content = "https://rule34video.com/video/3907053/4k60fps-bad-kitty-redrainsfm/"
createdAt = "2025-06-29T15:20:57.639Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3907000/3907053/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3907053/4k60fps-bad-kitty-redrainsfm/"
title = "(4K60fps) bad kitty [RedRainSFM]"
image = "https://rule34video.com/contents/videos_screenshots/3907000/3907053/preview.jpg"
site = "rule34video.com"
desc = ""
