id = "1375501386652844183"
name = "[HSR]: Cipher Sex"
archived = true
locked = false
createdAt = "2025-05-23T15:51:26.158Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375501386652844183"
author = "korieuko"
content = "https://rule34video.com/video/3848917/hsr-cipher-sex/"
createdAt = "2025-05-23T15:51:26.158Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3848000/3848917/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3848917/hsr-cipher-sex/"
title = "[HSR]: Cipher Sex"
image = "https://rule34video.com/contents/videos_screenshots/3848000/3848917/preview.jpg"
site = "rule34video.com"
desc = ""
