id = "1459401098929639630"
name = "[Yuluer] Cipher"
archived = true
locked = false
createdAt = "2026-01-10T04:18:56.346Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1459401098929639630"
author = "korieuko"
content = "https://rule34video.com/video/4186839/yuluer-cipher/"
createdAt = "2026-01-10T04:18:56.346Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4186000/4186839/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4186839/yuluer-cipher/"
title = "[Yuluer] Cipher"
image = "https://rule34video.com/contents/videos_screenshots/4186000/4186839/preview.jpg"
site = "rule34video.com"
desc = ""
