id = "1388025888926470145"
name = "Cipher-Honkai: Star Rail"
archived = true
locked = false
createdAt = "2025-06-27T05:19:20.194Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1388025888926470145"
author = "korieuko"
content = "https://rule34video.com/video/3895397/cipher-honkai-star-rail2/"
createdAt = "2025-06-27T05:19:20.194Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3895000/3895397/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3895397/cipher-honkai-star-rail2/"
title = "Cipher-Honkai: Star Rail"
image = "https://rule34video.com/contents/videos_screenshots/3895000/3895397/preview.jpg"
site = "rule34video.com"
desc = "Follow me on Twitter for my latest updates! Twitter-X: https://x.com/CBX_CJW\n\nIf you like my video, please go to FANBOX to sponsor and get the 2K perfect version. Thank you very much. 2K Perfect: https://orange-half-god.fanbox.cc/posts/10083014?utm_campaign=post_page&utm_medium=share&utm_source=twitter"
