id = "1394119153094492221"
name = "Cipher [Tir_Al]"
archived = true
locked = false
createdAt = "2025-07-14T00:51:47.579Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394119153094492221"
author = "korieuko"
content = "https://rule34video.com/video/3916549/cipher-tir-al/"
createdAt = "2025-07-14T00:51:47.579Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3916000/3916549/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3916549/cipher-tir-al/"
title = "Cipher [Tir_Al]"
image = "https://rule34video.com/contents/videos_screenshots/3916000/3916549/preview.jpg"
site = "rule34video.com"
desc = "Cipher by Tir_Al"
