id = "1377545948686843984"
name = "Cipher - RDreamer"
archived = true
locked = false
createdAt = "2025-05-29T07:15:47.733Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377545948686843984"
author = "korieuko"
content = "https://rule34video.com/video/3854349/cipher-rdreamer/"
createdAt = "2025-05-29T07:15:47.733Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3854000/3854349/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3854349/cipher-rdreamer/"
title = "Cipher - RDreamer"
image = "https://rule34video.com/contents/videos_screenshots/3854000/3854349/preview.jpg"
site = "rule34video.com"
desc = ""
