id = "1393625874267635712"
name = "Cipher porn video"
archived = true
locked = false
createdAt = "2025-07-12T16:11:40.742Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1393625874267635712"
author = "korieuko"
content = "https://rule34video.com/video/3928789/cipher-porn-video/"
createdAt = "2025-07-12T16:11:40.742Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3928000/3928789/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3928789/cipher-porn-video/"
title = "Cipher porn video"
image = "https://rule34video.com/contents/videos_screenshots/3928000/3928789/preview.jpg"
site = "rule34video.com"
desc = ""
