id = "1410427740619804732"
name = "Phrolova 2"
archived = true
locked = false
createdAt = "2025-08-28T00:56:17.844Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1410427740619804732"
author = "korieuko"
content = "https://rule34video.com/video/3997757/phrolova-2/"
createdAt = "2025-08-28T00:56:17.844Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3997000/3997757/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3997757/phrolova-2/"
title = "Phrolova 2"
image = "https://rule34video.com/contents/videos_screenshots/3997000/3997757/preview.jpg"
site = "rule34video.com"
desc = ""
