id = "1399626943866863678"
name = "Phrolova FULL by RDreamer"
archived = true
locked = false
createdAt = "2025-07-29T05:37:47.229Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1399626943866863678"
author = "korieuko"
content = "https://rule34video.com/video/3953881/phrolova-full-by-rdreamer/"
createdAt = "2025-07-29T05:37:47.229Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3953000/3953881/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3953881/phrolova-full-by-rdreamer/"
title = "Phrolova FULL by RDreamer"
image = "https://rule34video.com/contents/videos_screenshots/3953000/3953881/preview.jpg"
site = "rule34video.com"
desc = ""
