id = "1314895829525331999"
name = "Navia X Hilichurl"
archived = true
locked = false
createdAt = "2024-12-07T10:06:35.342Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1314895829525331999"
author = "korieuko"
content = "https://avbebe.com/archives/259553"
createdAt = "2024-12-07T10:06:35.342Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []

[[messages]]
id = "1314895922978885672"
author = "korieuko"
content = "Navia X Hilichurl"
createdAt = "2024-12-07T10:06:57.623Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
