id = "1373176339066257409"
name = "Navia x Clorinde Futa 2 sex video (Genshin impact)"
archived = true
locked = false
createdAt = "2025-05-17T05:52:31.616Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1373176339066257409"
author = "korieuko"
content = "https://rule34video.com/video/3837621/navia-x-clorinde-futa-2-sex-video-genshin-impact-x/"
createdAt = "2025-05-17T05:52:31.616Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3837000/3837621/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3837621/navia-x-clorinde-futa-2-sex-video-genshin-impact-x/"
title = "Navia x Clorinde Futa 2 sex video (Genshin impact)"
image = "https://rule34video.com/contents/videos_screenshots/3837000/3837621/preview.jpg"
site = "rule34video.com"
desc = "Scenes by hongcha imsayaa34 ToTheMoon yuukis\n\nPremium version (12:00) here:\n\nhttps://www.fanbox.cc/@acidrain002/posts/9883653"
