id = "1406600213904228406"
name = "Navia (Compiled) [Kirigame_5]"
archived = true
locked = false
createdAt = "2025-08-17T11:27:04.363Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406600213904228406"
author = "korieuko"
content = "https://rule34video.com/video/3952805/navia-compiled-kirigame-5/"
createdAt = "2025-08-17T11:27:04.363Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3952000/3952805/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3952805/navia-compiled-kirigame-5/"
title = "Navia (Compiled) [Kirigame_5]"
image = "https://rule34video.com/contents/videos_screenshots/3952000/3952805/preview.jpg"
site = "rule34video.com"
desc = ""
