id = "1371869528820285470"
name = "Cantarella dream POV"
archived = true
locked = false
createdAt = "2025-05-13T15:19:43.774Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371869528820285470"
author = "korieuko"
content = "https://rule34video.com/video/3832429/cantarella-dream-pov/"
createdAt = "2025-05-13T15:19:43.774Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3832000/3832429/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3832429/cantarella-dream-pov/"
title = "Cantarella dream POV"
image = "https://rule34video.com/contents/videos_screenshots/3832000/3832429/preview.jpg"
site = "rule34video.com"
desc = "Cantarella dream POV"
