id = "1358006179132866560"
name = "Cantarella making herself well acquainted with Rover."
archived = true
locked = false
createdAt = "2025-04-05T09:11:43.640Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1358006179132866560"
author = "korieuko"
content = "https://rule34video.com/video/3765201/cantarella-making-herself-well-acquainted-with-rover/"
createdAt = "2025-04-05T09:11:43.640Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3765000/3765201/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3765201/cantarella-making-herself-well-acquainted-with-rover/"
title = "Cantarella making herself well acquainted with Rover."
image = "https://rule34video.com/contents/videos_screenshots/3765000/3765201/preview.jpg"
site = "rule34video.com"
desc = "1080p No Watermark version available on my Patreon !\n \nCantarella model: @Norinde3D \nMale Rover Model: Me\nVA Pack:  @NekoNyan_VA \nSFX Pack: @OpenNSFWSP \nShaders: @SarlSys"
