id = "1377545031271059456"
name = "Cantarella Riding"
archived = true
locked = false
createdAt = "2025-05-29T07:12:09.004Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377545031271059456"
author = "korieuko"
content = "https://rule34video.com/video/3856177/cantarella-riding/"
createdAt = "2025-05-29T07:12:09.004Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3856000/3856177/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3856177/cantarella-riding/"
title = "Cantarella Riding"
image = "https://rule34video.com/contents/videos_screenshots/3856000/3856177/preview.jpg"
site = "rule34video.com"
desc = "4k60fps & 1080p60fps Full video↓\n\nhttps://www.patreon.com/posts/cantarella-129877431\n\nhttps://www.patreon.com/posts/cantarella-129877400\n\nscene by hongcha"
