id = "1395754257961193482"
name = "Cantarella_Wuthering Waves [6aminoac9]"
archived = true
locked = false
createdAt = "2025-07-18T13:09:06.958Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1395754257961193482"
author = "korieuko"
content = "https://rule34video.com/video/3937105/cantarella-wuthering-waves-6aminoac93/"
createdAt = "2025-07-18T13:09:06.958Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3937000/3937105/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3937105/cantarella-wuthering-waves-6aminoac93/"
title = "Cantarella_Wuthering Waves [6aminoac9]"
image = "https://rule34video.com/contents/videos_screenshots/3937000/3937105/preview.jpg"
site = "rule34video.com"
desc = "Cantarella_Wuthering Waves [6aminoac9]\n\n:{|"
