id = "1358005790107242594"
name = "Cantarella x Rover (Sleeping)"
archived = true
locked = false
createdAt = "2025-04-05T09:10:10.889Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1358005790107242594"
author = "korieuko"
content = "https://rule34video.com/video/3763457/cantarella-x-rover-sleeping/"
createdAt = "2025-04-05T09:10:10.889Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3763000/3763457/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3763457/cantarella-x-rover-sleeping/"
title = "Cantarella x Rover (Sleeping)"
image = "https://rule34video.com/contents/videos_screenshots/3763000/3763457/preview.jpg"
site = "rule34video.com"
desc = "Download 2k video: https://www.patreon.com/iwarasleeping"
