id = "1382976890754695269"
name = "Cantarella X YinLin Futa Sex (sound)"
archived = true
locked = false
createdAt = "2025-06-13T06:56:25.224Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382976890754695269"
author = "korieuko"
content = "https://rule34video.com/video/3877809/cantarella-x-yinlin-futa-sex-sound/"
createdAt = "2025-06-13T06:56:25.224Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3877000/3877809/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3877809/cantarella-x-yinlin-futa-sex-sound/"
title = "Cantarella X YinLin Futa Sex (sound)"
image = "https://rule34video.com/contents/videos_screenshots/3877000/3877809/preview.jpg"
site = "rule34video.com"
desc = "New custom animation finished\n\n4k60fps & 1080p60fps on my Patreon↓\n\npatreon.com/TY98\n\nVA by LecheryAmoreVA | geministarsign1\nSFX by OpenNSFWSP\n\nscene by Hongcha,Nyanify,Saeong \n\nIf you enjoy my work, please consider supporting me✨"
