id = "1387460693695139891"
name = "Carlotta x Cantarella Futa Sex (Sound)"
archived = true
locked = false
createdAt = "2025-06-25T15:53:27.150Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1387460693695139891"
author = "korieuko"
content = "https://rule34video.com/video/3902125/request-carlotta-x-cantarella-futa-sex-sound/"
createdAt = "2025-06-25T15:53:27.150Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3902000/3902125/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3902125/request-carlotta-x-cantarella-futa-sex-sound/"
title = "[Request] Carlotta x Cantarella Futa Sex (Sound)"
image = "https://rule34video.com/contents/videos_screenshots/3902000/3902125/preview.jpg"
site = "rule34video.com"
desc = "4k60fps & 1080p60fps on my Patreon↓\n\nPatreon.com/TY98\n\nVA: LecheryAmoreVA | geministarsign1\nSFX: OpenNSFWSP\n \nscene by Anna Anon, Hongcha, Nyanify\n\nUnlock all my 1080p & 4k animations for just $3 & $5 - no watermark, full access\n\nIf you enjoy my work, please consider supporting me!"
