id = "1377545208094392360"
name = "MokaBensin---- Cantarella [Wuthering Wave]"
archived = true
locked = false
createdAt = "2025-05-29T07:12:51.162Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377545208094392360"
author = "korieuko"
content = "https://rule34video.com/video/3829769/mokabensin-cantarella-wuthering-wave/"
createdAt = "2025-05-29T07:12:51.162Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3829000/3829769/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3829769/mokabensin-cantarella-wuthering-wave/"
title = "MokaBensin---- Cantarella [Wuthering Wave]"
image = "https://rule34video.com/contents/videos_screenshots/3829000/3829769/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://x.com/MokaBensin\nhttps://www.pixiv.net/en/users/106033015\nhttps://www.iwara.tv/profile/mokabenshin"
