id = "1478419086458359988"
name = "[HoyoCinema] Aemeath"
archived = false
locked = false
createdAt = "2026-03-03T15:49:37.910Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1478419086458359988"
author = "korieuko"
content = "https://rule34video.com/video/4265786/hoyocinema-aemeath/"
createdAt = "2026-03-03T15:49:37.910Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4265000/4265786/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4265786/hoyocinema-aemeath/"
title = "[HoyoCinema] Aemeath"
image = "https://rule34video.com/contents/videos_screenshots/4265000/4265786/preview.jpg"
site = "rule34video.com"
desc = ""

[[messages]]
id = "1478419128170713181"
author = "korieuko"
content = "fucking peak af"
createdAt = "2026-03-03T15:49:47.855Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
