id = "1479808790722383962"
name = "Aemeath [Akt]"
archived = false
locked = false
createdAt = "2026-03-07T11:51:49.226Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1479808790722383962"
author = "korieuko"
content = "https://rule34video.com/video/4275549/aemeath-akt/"
createdAt = "2026-03-07T11:51:49.226Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4275000/4275549/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4275549/aemeath-akt/"
title = "Aemeath [Akt]"
image = "https://rule34video.com/contents/videos_screenshots/4275000/4275549/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://akt.fanbox.cc\nhttps://www.patreon.com/c/akt_shop\nhttps://ganknow.com/animationakt"
