id = "1480056145333981254"
name = "RDreamer Aemeath PT2 FULL"
archived = false
locked = false
createdAt = "2026-03-08T04:14:43.161Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480056145333981254"
author = "korieuko"
content = "https://rule34video.com/video/4270978/rdreamer-aemeath-pt2-full/"
createdAt = "2026-03-08T04:14:43.161Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4270000/4270978/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4270978/rdreamer-aemeath-pt2-full/"
title = "RDreamer Aemeath PT2 FULL"
image = "https://rule34video.com/contents/videos_screenshots/4270000/4270978/preview.jpg"
site = "rule34video.com"
desc = ""
