id = "1468944122667597864"
name = "rdreamer aemeath full"
archived = true
locked = false
createdAt = "2026-02-05T12:19:30.506Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1468944122667597864"
author = "korieuko"
content = "https://rule34video.com/video/4229718/rdreamer-aemeath-full/"
createdAt = "2026-02-05T12:19:30.506Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4229000/4229718/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4229718/rdreamer-aemeath-full/"
title = "RDreamer Aemeath FULL"
image = "https://rule34video.com/contents/videos_screenshots/4229000/4229718/preview.jpg"
site = "rule34video.com"
desc = ""
