id = "1382975794128621588"
name = "Breeding mommy Adepti birb Xianyun"
archived = true
locked = false
createdAt = "2025-06-13T06:52:03.768Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1382975794128621588"
author = "korieuko"
content = "https://rule34video.com/video/3600462/breeding-mommy-adepti-birb-xianyun/"
createdAt = "2025-06-13T06:52:03.768Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3600000/3600462/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3600462/breeding-mommy-adepti-birb-xianyun/"
title = "Breeding mommy Adepti birb Xianyun"
image = "https://rule34video.com/contents/videos_screenshots/3600000/3600462/preview.jpg"
site = "rule34video.com"
desc = ""
