id = "1376122122577121290"
name = "Ganyu and Shenhe Bang Xianyun - 1080p Clean - Clothed By infected_heart"
archived = true
locked = false
createdAt = "2025-05-25T08:58:01.135Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1376122122577121290"
author = "korieuko"
content = "https://rule34video.com/video/3572574/ganyu-and-shenhe-bang-xianyun-1080p-clean-clothed-by-infected-heart/"
createdAt = "2025-05-25T08:58:01.135Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3572000/3572574/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3572574/ganyu-and-shenhe-bang-xianyun-1080p-clean-clothed-by-infected-heart/"
title = "Ganyu and Shenhe Bang Xianyun - 1080p Clean - Clothed By infected_h..."
image = "https://rule34video.com/contents/videos_screenshots/3572000/3572574/preview.jpg"
site = "rule34video.com"
desc = ""
