id = "1421528666193789159"
name = "Genshin Impact Xianyun「croove」"
archived = true
locked = false
createdAt = "2025-09-27T16:07:24.746Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1421528666193789159"
author = "korieuko"
content = "https://rule34video.com/video/3276634/genshin-impact-xianyun-croove/"
createdAt = "2025-09-27T16:07:24.746Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3276000/3276634/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3276634/genshin-impact-xianyun-croove/"
title = "Genshin Impact Xianyun「croove」"
image = "https://rule34video.com/contents/videos_screenshots/3276000/3276634/preview.jpg"
site = "rule34video.com"
desc = ""
