id = "1366080183454531644"
name = "GI Xianyun x Yelan (Chopsticker)"
archived = true
locked = false
createdAt = "2025-04-27T15:54:56.278Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1366080183454531644"
author = "korieuko"
content = "https://rule34video.com/video/3344089/gi-xianyun-x-yelan-chopsticker/"
createdAt = "2025-04-27T15:54:56.278Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3344000/3344089/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3344089/gi-xianyun-x-yelan-chopsticker/"
title = "GI Xianyun x Yelan (Chopsticker)"
image = "https://rule34video.com/contents/videos_screenshots/3344000/3344089/preview.jpg"
site = "rule34video.com"
desc = ""
