id = "1395754120681623602"
name = "Aogusita_Wuthering Waves [6aminoac9]"
archived = true
locked = false
createdAt = "2025-07-18T13:08:34.228Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1395754120681623602"
author = "korieuko"
content = "https://rule34video.com/video/3937101/aogusita-wuthering-waves-6aminoac9/"
createdAt = "2025-07-18T13:08:34.228Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3937000/3937101/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3937101/aogusita-wuthering-waves-6aminoac9/"
title = "Aogusita_Wuthering Waves [6aminoac9]"
image = "https://rule34video.com/contents/videos_screenshots/3937000/3937101/preview.jpg"
site = "rule34video.com"
desc = "Aogusita_Wuthering Waves [6aminoac9]\n\n:||"
