id = "1404844564430192742"
name = "Augusta Glory Hole - No sound"
archived = true
locked = false
createdAt = "2025-08-12T15:10:44.910Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404844564430192742"
author = "korieuko"
content = "https://rule34video.com/video/3962562/augusta-glory-hole-no-sound/"
createdAt = "2025-08-12T15:10:44.910Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3962000/3962562/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3962562/augusta-glory-hole-no-sound/"
title = "Augusta Glory Hole - No sound"
image = "https://rule34video.com/contents/videos_screenshots/3962000/3962562/preview.jpg"
site = "rule34video.com"
desc = "Hi, I'm bringing you a new video. I hope you like it. My Fanbox contains files with images and the video if you'd like to download it. I'll leave you a video with audio.\n Remember, the Fanbox is free.\n\nhttps://candacelewd.fanbox.cc"
