id = "1413179868786724955"
name = "Augusta - &#34;The Gladiator's Trial&#34;"
archived = true
locked = false
createdAt = "2025-09-04T15:12:16.331Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413179868786724955"
author = "korieuko"
content = "https://rule34video.com/video/4010725/augusta-the-gladiator-s-trial/"
createdAt = "2025-09-04T15:12:16.331Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4010000/4010725/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4010725/augusta-the-gladiator-s-trial/"
title = "Augusta - &#34;The Gladiator's Trial&#34;"
image = "https://rule34video.com/contents/videos_screenshots/4010000/4010725/preview.jpg"
site = "rule34video.com"
desc = ""
