id = "1442862126384549898"
name = "Augusta and the False Sovereign cock"
archived = true
locked = false
createdAt = "2025-11-25T12:58:58.012Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1442862126384549898"
author = "korieuko"
content = "https://rule34video.com/video/4105178/augusta-and-the-false-sovereign-cock-4k/"
createdAt = "2025-11-25T12:58:58.012Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4105000/4105178/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4105178/augusta-and-the-false-sovereign-cock-4k/"
title = "Augusta and the False Sovereign cock"
image = "https://rule34video.com/contents/videos_screenshots/4105000/4105178/preview.jpg"
site = "rule34video.com"
desc = "Full all variants 4K"
