id = "1412100882237231154"
name = "Augusta X mob sex video (WuWa)"
archived = true
locked = false
createdAt = "2025-09-01T15:44:45.891Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1412100882237231154"
author = "korieuko"
content = "https://rule34video.com/video/4002573/augusta-x-mob-sex-video-wuwa/"
createdAt = "2025-09-01T15:44:45.891Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4002000/4002573/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4002573/augusta-x-mob-sex-video-wuwa/"
title = "Augusta X mob sex video (WuWa)"
image = "https://rule34video.com/contents/videos_screenshots/4002000/4002573/preview.jpg"
site = "rule34video.com"
desc = "Full version (11:09) here:\n\nhttps://www.fanbox.cc/@acidrain002/posts/10469990\n\nScene by hongcha & imsayaa34 & ToTheMoon & yurabe & yuukis & harada\nThis video made by Acidrain\nMore & Longer videos & Support creator: https://acidrain002.fanbox.cc"
