id = "1389416093088616579"
name = "Augusta_ Wuthering Waves [RD]"
archived = true
locked = false
createdAt = "2025-07-01T01:23:30.695Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389416093088616579"
author = "korieuko"
content = "https://rule34video.com/video/3910477/augusta-wuthering-waves-rd/"
createdAt = "2025-07-01T01:23:30.695Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3910000/3910477/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3910477/augusta-wuthering-waves-rd/"
title = "Augusta_ Wuthering Waves [RD]"
image = "https://rule34video.com/contents/videos_screenshots/3910000/3910477/preview.jpg"
site = "rule34video.com"
desc = ":||"
