id = "1415728432058208462"
name = "Augusta Riding"
archived = true
locked = false
createdAt = "2025-09-11T15:59:21.165Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1415728432058208462"
author = "korieuko"
content = "https://rule34video.com/video/4021985/augusta-riding/"
createdAt = "2025-09-11T15:59:21.165Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4021000/4021985/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4021985/augusta-riding/"
title = "Augusta Riding"
image = "https://rule34video.com/contents/videos_screenshots/4021000/4021985/preview.jpg"
site = "rule34video.com"
desc = ""
