id = "1411549726800875661"
name = "RDreamer Augusta PT2 FULL"
archived = true
locked = false
createdAt = "2025-08-31T03:14:40.195Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1411549726800875661"
author = "korieuko"
content = "https://rule34video.com/video/4003889/rdreamer-augusta-pt2-full/"
createdAt = "2025-08-31T03:14:40.195Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4003000/4003889/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4003889/rdreamer-augusta-pt2-full/"
title = "RDreamer Augusta PT2 FULL"
image = "https://rule34video.com/contents/videos_screenshots/4003000/4003889/preview.jpg"
site = "rule34video.com"
desc = ""
