id = "1462030549798359313"
name = "RDreamer Mornye FULL"
archived = true
locked = false
createdAt = "2026-01-17T10:27:26.286Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1462030549798359313"
author = "korieuko"
content = "https://rule34video.com/video/4198089/rdreamer-mornye-full/"
createdAt = "2026-01-17T10:27:26.286Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4198000/4198089/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4198089/rdreamer-mornye-full/"
title = "RDreamer Mornye FULL"
image = "https://rule34video.com/contents/videos_screenshots/4198000/4198089/preview.jpg"
site = "rule34video.com"
desc = "Mornye's model with her transparent legs is so hot!!!"
