id = "1406598633511452672"
name = "Varesa finds a Stray Hilichurl | Delightss"
archived = true
locked = false
createdAt = "2025-08-17T11:20:47.568Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406598633511452672"
author = "korieuko"
content = "https://rule34video.com/video/3975092/hilichurl-find-a-stray-cat/"
createdAt = "2025-08-17T11:20:47.568Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3975000/3975092/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3975092/hilichurl-find-a-stray-cat/"
title = "Varesa finds a Stray Hilichurl | Delightss"
image = "https://rule34video.com/contents/videos_screenshots/3975000/3975092/preview.jpg"
site = "rule34video.com"
desc = ""
