id = "1395760432429404270"
name = "Varesa Mitachurled (4K) [Bubukuin]"
archived = true
locked = false
createdAt = "2025-07-18T13:33:39.066Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1395760432429404270"
author = "korieuko"
content = "https://rule34video.com/video/3794841/varesa-mitachurled-4k-bubukuin/"
createdAt = "2025-07-18T13:33:39.066Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3794000/3794841/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3794841/varesa-mitachurled-4k-bubukuin/"
title = "Varesa Mitachurled (4K) [Bubukuin]"
image = "https://rule34video.com/contents/videos_screenshots/3794000/3794841/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/bubukuin\nx.com/bubukuin\n\nVA: chiyo1000nights"
