id = "1478418868732170395"
name = "Varesa Genshin Impact Animation #30"
archived = false
locked = false
createdAt = "2026-03-03T15:48:46.000Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1478418868732170395"
author = "korieuko"
content = "https://rule34video.com/video/4269850/varesa-genshin-impact-animation-30/"
createdAt = "2026-03-03T15:48:46.000Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
