id = "1395760252133179442"
name = "Varesa Mitachurled (4K/POV) [Bubukuin]"
archived = true
locked = false
createdAt = "2025-07-18T13:32:56.080Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1395760252133179442"
author = "korieuko"
content = "https://rule34video.com/video/3794849/varesa-mitachurled-4k-pov-bubukuin/"
createdAt = "2025-07-18T13:32:56.080Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3794000/3794849/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3794849/varesa-mitachurled-4k-pov-bubukuin/"
title = "Varesa Mitachurled (4K/POV) [Bubukuin]"
image = "https://rule34video.com/contents/videos_screenshots/3794000/3794849/preview.jpg"
site = "rule34video.com"
desc = "Created by\npatreon.com/bubukuin\nx.com/bubukuin\n\nVA: chiyo1000nights"
