id = "1314841655769300992"
name = "[Machi馬吉] 【Live2D Motion Full】💜Acheron Dream💜"
archived = true
locked = false
createdAt = "2024-12-07T06:31:19.312Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314841655769300992"
author = "korieuko"
content = "https://avbebe.com/archives/232125"
createdAt = "2024-12-07T06:31:19.312Z"
pinned = false
attachments = ""
thumbnail = "https://avbebe.com/wp-content/uploads/2024/06/Machi%E9%A6%AC%E5%90%89-%E3%80%90Live2D-Motion-Full%E3%80%91%F0%9F%92%9CAcheron-Dream%F0%9F%92%9C.jpg"

[[messages.linkPreviews]]
url = "https://avbebe.com/archives/232125"
title = "[Machi馬吉] 【Live2D Motion Full】💜Acheron Dream💜"
image = "https://avbebe.com/wp-content/uploads/2024/06/Machi%E9%A6%AC%E5%90%89-%E3%80%90Live2D-Motion-Full%E3%80%91%F0%9F%92%9CAcheron-Dream%F0%9F%92%9C.jpg"
site = "Avbebe 高清H動畫♥最新里番♥成人動畫♥3D動畫♥成人動漫♥A片♥Ecchi"
desc = "Avbebe #1 streamwish"
