id = "1421126145599996034"
name = "Acheron pov JP-voice"
archived = true
locked = false
createdAt = "2025-09-26T13:27:56.358Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1421126145599996034"
author = "korieuko"
content = "https://rule34video.com/video/4046062/acheron-pov-jp-voice/"
createdAt = "2025-09-26T13:27:56.358Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4046000/4046062/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4046062/acheron-pov-jp-voice/"
title = "Acheron pov JP-voice"
image = "https://rule34video.com/contents/videos_screenshots/4046000/4046062/preview.jpg"
site = "rule34video.com"
desc = ""
