id = "1398958442588147752"
name = "Acheron Blackmailed to save the Trailblazer"
archived = true
locked = false
createdAt = "2025-07-27T09:21:24.104Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1398958442588147752"
author = "korieuko"
content = "https://rule34video.com/video/3950565/acheron-blackmailed-to-save-the-trailblazer/"
createdAt = "2025-07-27T09:21:24.104Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3950000/3950565/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3950565/acheron-blackmailed-to-save-the-trailblazer/"
title = "Acheron Blackmailed to save the Trailblazer"
image = "https://rule34video.com/contents/videos_screenshots/3950000/3950565/preview.jpg"
site = "rule34video.com"
desc = "Artist: Tir_Al\n\nAll angles\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"
