id = "1314898472289308703"
name = "AlphaG] Acheron X Mob"
archived = true
locked = false
createdAt = "2024-12-07T10:17:05.426Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314898472289308703"
author = "korieuko"
content = "https://avbebe.com/archives/244584"
createdAt = "2024-12-07T10:17:05.426Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
