id = "1422485630222336102"
name = "[MastaPOV] Arlecchino (Bunny Outfit)"
archived = true
locked = false
createdAt = "2025-09-30T07:30:02.750Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1422485630222336102"
author = "korieuko"
content = "https://rule34video.com/video/3487458/mastapov-arlecchino-bunny-outfit/"
createdAt = "2025-09-30T07:30:02.750Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3487000/3487458/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3487458/mastapov-arlecchino-bunny-outfit/"
title = "[MastaPOV] Arlecchino (Bunny Outfit)"
image = "https://rule34video.com/contents/videos_screenshots/3487000/3487458/preview.jpg"
site = "rule34video.com"
desc = "Artist: Masta POV\n*side note*\nThere are other versions of this animation with different outfits debating if I should upload them as this one took forever to upload.\nIf enough people want it I’ll upload the other outfits"
