id = "1314895232101515274"
name = "[Tir_AL] Arlecchino"
archived = true
locked = false
createdAt = "2024-12-07T10:04:12.905Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314895232101515274"
author = "korieuko"
content = "https://avbebe.com/archives/198535"
createdAt = "2024-12-07T10:04:12.905Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
