id = "1413831150962475231"
name = "[Tir_Al] Arlecchino - 4K"
archived = true
locked = false
createdAt = "2025-09-06T10:20:14.102Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413831150962475231"
author = "korieuko"
content = "https://rule34video.com/video/3287194/tir-al-arlecchino-4k2/"
createdAt = "2025-09-06T10:20:14.102Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3287000/3287194/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3287194/tir-al-arlecchino-4k2/"
title = "[Tir_Al] Arlecchino - 4K"
image = "https://rule34video.com/contents/videos_screenshots/3287000/3287194/preview.jpg"
site = "rule34video.com"
desc = ""
