id = "1358005968683667657"
name = "Arlecchino Fucked by Hilichurl [RougeNine]"
archived = true
locked = false
createdAt = "2025-04-05T09:10:53.465Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1358005968683667657"
author = "korieuko"
content = "https://rule34video.com/video/3771601/arlecchino-fucked-by-hilichurl-rougenine/"
createdAt = "2025-04-05T09:10:53.465Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3771000/3771601/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3771601/arlecchino-fucked-by-hilichurl-rougenine/"
title = "Arlecchino Fucked by Hilichurl [RougeNine]"
image = "https://rule34video.com/contents/videos_screenshots/3771000/3771601/preview.jpg"
site = "rule34video.com"
desc = ""
