id = "1421382382623129702"
name = "Arlecchino Cowgirl [Saucifer3D]"
archived = true
locked = false
createdAt = "2025-09-27T06:26:08.025Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1421382382623129702"
author = "korieuko"
content = "https://rule34video.com/video/3679097/arlecchino-cowgirl-saucifer3d/"
createdAt = "2025-09-27T06:26:08.025Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3679000/3679097/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3679097/arlecchino-cowgirl-saucifer3d/"
title = "Arlecchino Cowgirl [Saucifer3D]"
image = "https://rule34video.com/contents/videos_screenshots/3679000/3679097/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Saucifer3D/status/1723800830858375598"
