id = "1390665680554037389"
name = "Arlecchino x Hilichurls (4K) [Lyusfyuring]"
archived = true
locked = false
createdAt = "2025-07-04T12:08:55.563Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1390665680554037389"
author = "korieuko"
content = "https://rule34video.com/video/3631383/arlecchino-x-hilichurls-4k-lyusfyuring/"
createdAt = "2025-07-04T12:08:55.563Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3631000/3631383/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3631383/arlecchino-x-hilichurls-4k-lyusfyuring/"
title = "Arlecchino x Hilichurls (4K) [Lyusfyuring]"
image = "https://rule34video.com/contents/videos_screenshots/3631000/3631383/preview.jpg"
site = "rule34video.com"
desc = ""
