id = "1448927846260146206"
name = "Arlecchino night session (Public)"
archived = true
locked = false
createdAt = "2025-12-12T06:41:58.326Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1448927846260146206"
author = "korieuko"
content = "https://rule34video.com/video/4145259/arlecchino-night-session-public/"
createdAt = "2025-12-12T06:41:58.326Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4145000/4145259/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4145259/arlecchino-night-session-public/"
title = "Arlecchino night session (Public)"
image = "https://rule34video.com/contents/videos_screenshots/4145000/4145259/preview.jpg"
site = "rule34video.com"
desc = "Full & alt angles: patreon.com/PovLover\n\nx.com/Pov_Loverr"
