id = "1389231262891376772"
name = "Snezhevna X Yelan (1:07)"
archived = true
locked = false
createdAt = "2025-06-30T13:09:03.742Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1389231262891376772"
author = "korieuko"
content = "https://rule34video.com/video/3859513/snezhevna-x-yelan-1-07/"
createdAt = "2025-06-30T13:09:03.742Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3859000/3859513/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3859513/snezhevna-x-yelan-1-07/"
title = "Snezhevna X Yelan (1:07)"
image = "https://rule34video.com/contents/videos_screenshots/3859000/3859513/preview.jpg"
site = "rule34video.com"
desc = "Trying out some stylized touches — hope you like it! ✨\n\n4k60fps &108060fps version on my Patreon\nUnlock all my 1080p animations for just $3 - no watermark, full access\n\nVA by LecheryAmoreVA|geministarsign1\nSFX by OpenNSFWSP\nScene by SkyArcadia,hongcha"
