id = "1418852624576286780"
name = "[RayX] Furina's Punishment"
archived = true
locked = false
createdAt = "2025-09-20T06:53:46.706Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1418852624576286780"
author = "korieuko"
content = "https://rule34video.com/video/3139541/rayx-furina-s-punishment/"
createdAt = "2025-09-20T06:53:46.706Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3139000/3139541/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3139541/rayx-furina-s-punishment/"
title = "[RayX] Furina's Punishment"
image = "https://rule34video.com/contents/videos_screenshots/3139000/3139541/preview.jpg"
site = "rule34video.com"
desc = "Artist: RayX\n\nhttps://twitter.com/monorayxxx\n\nhttps://rayx.fanbox.cc/"
