id = "1443227791909978193"
name = "Beautiful Girl Furina enjoyed BBC"
archived = true
locked = false
createdAt = "2025-11-26T13:11:59.467Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1443227791909978193"
author = "korieuko"
content = "https://rule34video.com/video/4122034/beautiful-girl-furina-enjoyed-bbc/"
createdAt = "2025-11-26T13:11:59.467Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4122000/4122034/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4122034/beautiful-girl-furina-enjoyed-bbc/"
title = "Beautiful Girl Furina enjoyed BBC"
image = "https://rule34video.com/contents/videos_screenshots/4122000/4122034/preview.jpg"
site = "rule34video.com"
desc = ""
