id = "1394118962077372447"
name = "Furina"
archived = true
locked = false
createdAt = "2025-07-14T00:51:02.037Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394118962077372447"
author = "korieuko"
content = "https://rule34video.com/video/3926401/furina11/"
createdAt = "2025-07-14T00:51:02.037Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3926000/3926401/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3926401/furina11/"
title = "furina"
image = "https://rule34video.com/contents/videos_screenshots/3926000/3926401/preview.jpg"
site = "rule34video.com"
desc = ""
