id = "1329826552715673764"
name = "Furina Live2D"
archived = true
locked = false
createdAt = "2025-01-17T14:55:57.150Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1329826552715673764"
author = "korieuko"
content = "https://rule34video.com/playlists/97209/live2d9/"
createdAt = "2025-01-17T14:55:57.150Z"
pinned = false
attachments = ""
thumbnail = ""

[[messages.linkPreviews]]
url = "https://rule34video.com/playlists/97209/live2d9/"
title = "Live2d"
image = ""
site = "rule34video.com"
desc = "Rule 34 - If it exists, there is porn of it. We aspire to be the biggest video archive of rule34 content."
