id = "1467177318194876416"
name = "Furina (Compiled) [Ent_Duke]"
archived = true
locked = false
createdAt = "2026-01-31T15:18:51.494Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1467177318194876416"
author = "korieuko"
content = "https://rule34video.com/video/4217330/furina-compiled-ent-duke/"
createdAt = "2026-01-31T15:18:51.494Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4217000/4217330/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4217330/furina-compiled-ent-duke/"
title = "Furina (Compiled) [Ent_Duke]"
image = "https://rule34video.com/contents/videos_screenshots/4217000/4217330/preview.jpg"
site = "rule34video.com"
desc = ""
