id = "1443228439334097129"
name = "Furina NNN"
archived = true
locked = false
createdAt = "2025-11-26T13:14:33.825Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1443228439334097129"
author = "korieuko"
content = "https://rule34video.com/video/4121054/furina-nnn/"
createdAt = "2025-11-26T13:14:33.825Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4121000/4121054/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4121054/furina-nnn/"
title = "Furina NNN"
image = "https://rule34video.com/contents/videos_screenshots/4121000/4121054/preview.jpg"
site = "rule34video.com"
desc = ""
