id = "1314902086952943636"
name = "[Shaggy SUSU] ファルザンアニメ"
archived = true
locked = false
createdAt = "2024-12-07T10:31:27.229Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1314902086952943636"
author = "korieuko"
content = "https://avbebe.com/archives/183680"
createdAt = "2024-12-07T10:31:27.229Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
