id = "1371473535083745290"
name = "[Poison_KK] Kafka HardSex ~ Honkai Star Rail"
archived = true
locked = false
createdAt = "2025-05-12T13:06:11.510Z"
autoArchiveDuration = 4320
messageCount = 2
appliedTags = []

[[messages]]
id = "1371473535083745290"
author = "korieuko"
content = "https://rule34video.com/video/3831157/poison-kk-kafka-hardsex-honkai-star-rail/"
createdAt = "2025-05-12T13:06:11.510Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3831000/3831157/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3831157/poison-kk-kafka-hardsex-honkai-star-rail/"
title = "[Poison_KK] Kafka HardSex ~ Honkai Star Rail"
image = "https://rule34video.com/contents/videos_screenshots/3831000/3831157/preview.jpg"
site = "rule34video.com"
desc = "Sigue Y Apoya Al Autor\nhttps://www.iwara.tv/profile/poison_kk/videos?sort=date&page=0\n\nhttps://poison0215.fanbox.cc/\n\nhttps://www.patreon.com/KoikatsuLoop\n\nhttps://youtube.com/@poison-animation?si=ZKj1zi5GHMK5zDah\n\nhttps://x.com/PoisonAhe\n\nhttps://www.pixiv.net/en/users/15779064/artworks"

[[messages]]
id = "1371474141894676571"
author = "korieuko"
content = "Hella good"
createdAt = "2025-05-12T13:08:36.185Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
