id = "1479808318120788020"
name = "Kafka - Caressing Moonlight [AidenHet]"
archived = false
locked = false
createdAt = "2026-03-07T11:49:56.549Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1479808318120788020"
author = "korieuko"
content = "https://rule34video.com/video/4266150/kafka-caressing-moonlight-aidenhet/"
createdAt = "2026-03-07T11:49:56.549Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4266000/4266150/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4266150/kafka-caressing-moonlight-aidenhet/"
title = "Kafka - Caressing Moonlight [AidenHet]"
image = "https://rule34video.com/contents/videos_screenshots/4266000/4266150/preview.jpg"
site = "rule34video.com"
desc = ""
