id = "1404845767704969337"
name = "Kafka forced & toture"
archived = true
locked = false
createdAt = "2025-08-12T15:15:31.793Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1404845767704969337"
author = "korieuko"
content = "https://rule34video.com/video/3955903/kafka-forced-toture/"
createdAt = "2025-08-12T15:15:31.793Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3955000/3955903/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3955903/kafka-forced-toture/"
title = "kafka forced & toture"
image = "https://rule34video.com/contents/videos_screenshots/3955000/3955903/preview.jpg"
site = "rule34video.com"
desc = ""
