id = "1388430680370970706"
name = "Strinova[NaV]"
guildId = "1314839006717935696"
guildName = "Invrs ✦ NSFW"
backedUpAt = "2026-03-08T12:46:53.480Z"
contents = ["forum: forum-flavia", "forum: forum-celestia", "forum: forum-michele", "forum: forum-chiyo"]

[stats]
totalForums = 4
totalChannels = 0
totalThreads = 5
totalMessages = 5
