id = "1443228326129959075"
name = "[SP][25S4] 长夜月 Evernight"
archived = true
locked = false
createdAt = "2025-11-26T13:14:06.835Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1443228326129959075"
author = "korieuko"
content = "https://rule34video.com/video/4121414/sp-25s4-evernight/"
createdAt = "2025-11-26T13:14:06.835Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4121000/4121414/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4121414/sp-25s4-evernight/"
title = "[SP][25S4] 长夜月 Evernight"
image = "https://rule34video.com/contents/videos_screenshots/4121000/4121414/preview.jpg"
site = "rule34video.com"
desc = ""
