id = "1420407647601164289"
name = "[Full] Nefer x Lauma"
archived = true
locked = false
createdAt = "2025-09-24T13:52:53.086Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1420407647601164289"
author = "korieuko"
content = "https://rule34video.com/video/4042078/full-nefer-x-lauma/"
createdAt = "2025-09-24T13:52:53.086Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4042000/4042078/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4042078/full-nefer-x-lauma/"
title = "[Full] Nefer x Lauma"
image = "https://rule34video.com/contents/videos_screenshots/4042000/4042078/preview.jpg"
site = "rule34video.com"
desc = "Thank you so much for checking out my content ✨ Your support makes my work possible!\n\n✨ If you want to enjoy all my animations in 4K-1080p, videos everyday, polls and more: https://www.patreon.com/c/torakage\n\n✨ My Socials:\n✨ Twitter: https://www.x.com/Torakage268000\n✨ Pixiv: https://www.pixiv.net/en/users/118638111\n✨ Iwara: https://w..."
