id = "1446528106323116042"
name = "Lauma Double Churled (4K)"
archived = true
locked = false
createdAt = "2025-12-05T15:46:15.740Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1446528106323116042"
author = "korieuko"
content = "https://rule34video.com/video/4135167/lauma-double-churled-4k/"
createdAt = "2025-12-05T15:46:15.740Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4135000/4135167/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4135167/lauma-double-churled-4k/"
title = "Lauma Double Churled (4K)"
image = "https://rule34video.com/contents/videos_screenshots/4135000/4135167/preview.jpg"
site = "rule34video.com"
desc = ""
