id = "1432994330448236656"
name = "Lauma relaxes at the Spa... [Baracuda_balls]"
archived = true
locked = false
createdAt = "2025-10-29T07:27:52.126Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1432994330448236656"
author = "korieuko"
content = "https://rule34video.com/video/4095462/lauma-relaxes-at-the-spa-baracuda-balls/"
createdAt = "2025-10-29T07:27:52.126Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4095000/4095462/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4095462/lauma-relaxes-at-the-spa-baracuda-balls/"
title = "Lauma relaxes at the Spa... [Baracuda_balls]"
image = "https://rule34video.com/contents/videos_screenshots/4095000/4095462/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Baracuda_balls/status/1979206016634847237"
