id = "1464127245869252679"
name = "Lauma's Mating Season (Full) [SingularityNSFW]"
archived = true
locked = false
createdAt = "2026-01-23T05:18:57.584Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1464127245869252679"
author = "korieuko"
content = "https://rule34video.com/video/4209858/lauma-s-mating-season-full-singularitynsfw/"
createdAt = "2026-01-23T05:18:57.584Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4209000/4209858/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4209858/lauma-s-mating-season-full-singularitynsfw/"
title = "Lauma's Mating Season (Full) [SingularityNSFW]"
image = "https://rule34video.com/contents/videos_screenshots/4209000/4209858/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Singularity618/status/2012541186016498138"
