id = "1406615349293744158"
name = "Lauma x Lumine having some first time fun ;D"
archived = true
locked = false
createdAt = "2025-08-17T12:27:12.921Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1406615349293744158"
author = "korieuko"
content = "https://rule34video.com/video/3974732/lauma-x-lumine-having-some-first-time-fun-d/"
createdAt = "2025-08-17T12:27:12.921Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3974000/3974732/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3974732/lauma-x-lumine-having-some-first-time-fun-d/"
title = "Lauma x Lumine having some first time fun ;D"
image = "https://rule34video.com/contents/videos_screenshots/3974000/3974732/preview.jpg"
site = "rule34video.com"
desc = "Like what you see? Please consider supporting the creator ❤️✨\nYou can find more than 500+ videos with sound and in 4K 60fps at:\n\nhttps://www.patreon.com/c/PeachieFlavor\nhttps://www.pixiv.net/en/users/109804769\nhttps://www.iwara.tv/profile/peachieflavor"
