id = "1417433761787809863"
name = "Lauma | Genshin Impact [RayX]"
archived = true
locked = false
createdAt = "2025-09-16T08:55:43.456Z"
autoArchiveDuration = 4320
messageCount = 3
appliedTags = []

[[messages]]
id = "1417433761787809863"
author = "korieuko"
content = "https://rule34video.com/video/4030137/lauma-genshin-impact-rayx/"
createdAt = "2025-09-16T08:55:43.456Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4030000/4030137/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4030137/lauma-genshin-impact-rayx/"
title = "Lauma | Genshin Impact [RayX]"
image = "https://rule34video.com/contents/videos_screenshots/4030000/4030137/preview.jpg"
site = "rule34video.com"
desc = "Animation: https://x.com/RaymonoXXX\nModel: https://x.com/DaB_neko\nVA: https://x.com/SuccuAiniVoice"

[[messages]]
id = "1420407688680177665"
author = "korieuko"
content = "peak"
createdAt = "2025-09-24T13:53:02.880Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []

[[messages]]
id = "1424779719399964732"
author = "korieuko"
content = "peak"
createdAt = "2025-10-06T15:25:56.232Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
