id = "1446528400612130916"
name = "Mating with Lauma [GoonDuude]"
archived = true
locked = false
createdAt = "2025-12-05T15:47:25.904Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1446528400612130916"
author = "korieuko"
content = "https://rule34video.com/video/4134747/mating-with-lauma-goonduude/"
createdAt = "2025-12-05T15:47:25.904Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4134000/4134747/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4134747/mating-with-lauma-goonduude/"
title = "Mating with Lauma [GoonDuude]"
image = "https://rule34video.com/contents/videos_screenshots/4134000/4134747/preview.jpg"
site = "rule34video.com"
desc = "https://x.com/Goonduude/status/1990006730118566035/video/1\n\nhttps://x.com/Goonduude/status/1983517650685976693/video/1\n\nhttps://x.com/Goonduude/status/1977509200038428796/video/1"
