id = "1480057272439935130"
name = "[HSR] Yao Guang"
archived = false
locked = false
createdAt = "2026-03-08T04:19:11.884Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1480057272439935130"
author = "korieuko"
content = "https://rule34video.com/video/4278157/hsr-yao-guang/"
createdAt = "2026-03-08T04:19:11.884Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4278000/4278157/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4278157/hsr-yao-guang/"
title = "[HSR] Yao Guang"
image = "https://rule34video.com/contents/videos_screenshots/4278000/4278157/preview.jpg"
site = "rule34video.com"
desc = "Audio version & fully nude:\n\nhttps://spectreccx.fanbox.cc/\nhttps://www.patreon.com/c/Spectreccx\n\nThanks for your support!"
