id = "1379439975246073896"
name = "[Croove][4K] Rabbit Mama"
archived = true
locked = false
createdAt = "2025-06-03T12:41:58.854Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1379439975246073896"
author = "korieuko"
content = "https://rule34video.com/video/3679125/croove-4k-rabbit-mama/"
createdAt = "2025-06-03T12:41:58.854Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
