id = "1390665583938240552"
name = "Jean wants it"
archived = true
locked = false
createdAt = "2025-07-04T12:08:32.528Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1390665583938240552"
author = "korieuko"
content = "https://rule34video.com/video/3913745/jean-wants-it/"
createdAt = "2025-07-04T12:08:32.528Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3913000/3913745/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3913745/jean-wants-it/"
title = "Jean wants it"
image = "https://rule34video.com/contents/videos_screenshots/3913000/3913745/preview.jpg"
site = "rule34video.com"
desc = ""
