id = "1395759587516481637"
name = "Jean [olsa]"
archived = true
locked = false
createdAt = "2025-07-18T13:30:17.623Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1395759587516481637"
author = "korieuko"
content = "https://rule34video.com/video/3890829/jean-olsa/"
createdAt = "2025-07-18T13:30:17.623Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3890000/3890829/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3890829/jean-olsa/"
title = "Jean [olsa]"
image = "https://rule34video.com/contents/videos_screenshots/3890000/3890829/preview.jpg"
site = "rule34video.com"
desc = ""
