id = "1391322179328540742"
name = "Jean x Mitachurl Full Nelson (with sound)"
archived = true
locked = false
createdAt = "2025-07-06T07:37:37.068Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391322179328540742"
author = "korieuko"
content = "https://rule34video.com/video/3642725/jean-x-mitachurl-full-nelson-with-sound/"
createdAt = "2025-07-06T07:37:37.068Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3642000/3642725/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3642725/jean-x-mitachurl-full-nelson-with-sound/"
title = "Jean x Mitachurl Full Nelson (with sound)"
image = "https://rule34video.com/contents/videos_screenshots/3642000/3642725/preview.jpg"
site = "rule34video.com"
desc = "Jean full Nelson deep fuck"
