id = "1394119764485472496"
name = "Jean Thigh Job"
archived = true
locked = false
createdAt = "2025-07-14T00:54:13.346Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1394119764485472496"
author = "korieuko"
content = "https://rule34video.com/video/3062080/jean-thigh-job/"
createdAt = "2025-07-14T00:54:13.346Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3062000/3062080/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3062080/jean-thigh-job/"
title = "Jean Thigh Job"
image = "https://rule34video.com/contents/videos_screenshots/3062000/3062080/preview.jpg"
site = "rule34video.com"
desc = "Source : https://twitter.com/Tir_Al_/status/1443224091893198850?s=20"
