id = "1413831276561039371"
name = "Jean x Hilichurls [4K]"
archived = true
locked = false
createdAt = "2025-09-06T10:20:44.047Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1413831276561039371"
author = "korieuko"
content = "https://rule34video.com/video/3249129/jean-x-hilichurls/"
createdAt = "2025-09-06T10:20:44.047Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3249000/3249129/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3249129/jean-x-hilichurls/"
title = "Jean x Hilichurls [4K]"
image = "https://rule34video.com/contents/videos_screenshots/3249000/3249129/preview.jpg"
site = "rule34video.com"
desc = "Jean x Hilichurls [4K]"
