id = "1391322299592085595"
name = "Jean Captured"
archived = true
locked = false
createdAt = "2025-07-06T07:38:05.741Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1391322299592085595"
author = "korieuko"
content = "https://rule34video.com/video/3693413/jean-captured/"
createdAt = "2025-07-06T07:38:05.741Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3693000/3693413/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3693413/jean-captured/"
title = "Jean Captured"
image = "https://rule34video.com/contents/videos_screenshots/3693000/3693413/preview.jpg"
site = "rule34video.com"
desc = "All angles\n\nhttps://www.patreon.com/tir_al\nhttps://x.com/tir_al_"
