id = "1374239832607293551"
name = "(1080p60) Escoffier [Yuluer]"
archived = true
locked = false
createdAt = "2025-05-20T04:18:28.235Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1374239832607293551"
author = "korieuko"
content = "https://rule34video.com/video/3844493/1080p60-escoffier-yuluer/"
createdAt = "2025-05-20T04:18:28.235Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3844000/3844493/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3844493/1080p60-escoffier-yuluer/"
title = "(1080p60) Escoffier [Yuluer]"
image = "https://rule34video.com/contents/videos_screenshots/3844000/3844493/preview.jpg"
site = "rule34video.com"
desc = "Bad news guys (from what I read).\nDue to work, this artist appears to be stopping making videos.\nWho knows if it will be a goodbye or a see you soon for us.\n\n&#34;I've decided to stop making videos due to my busy work. I'm not sure when I'll be able to make them again, maybe never.\nThanks for your continued support, please stop sponsoring.&#34;\n..."
