id = "1375456884303069245"
name = "[Yuluer] Escoffier_uncen"
archived = true
locked = false
createdAt = "2025-05-23T12:54:35.971Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375456884303069245"
author = "korieuko"
content = "https://rule34video.com/video/3843645/yuluer-escoffier-uncen/"
createdAt = "2025-05-23T12:54:35.971Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3843000/3843645/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3843645/yuluer-escoffier-uncen/"
title = "[Yuluer] Escoffier_uncen"
image = "https://rule34video.com/contents/videos_screenshots/3843000/3843645/preview.jpg"
site = "rule34video.com"
desc = "Important message form Yuluer:\n&#34;˘ . ˘ I've decided to stop making videos due to my busy work. I'm not sure when I'll be able to make them again, maybe never.\nThanks for your continued support, please stop sponsoring.&#34;\n\no7 all the best to you good gentleman."
