id = "1416313810700079164"
name = "RDreamer Artoria FULL"
archived = true
locked = false
createdAt = "2025-09-13T06:45:26.309Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1416313810700079164"
author = "korieuko"
content = "https://rule34video.com/video/4024749/rdreamer-artoria-full/"
createdAt = "2025-09-13T06:45:26.309Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4024000/4024749/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4024749/rdreamer-artoria-full/"
title = "RDreamer Artoria FULL"
image = "https://rule34video.com/contents/videos_screenshots/4024000/4024749/preview.jpg"
site = "rule34video.com"
desc = ""
