id = "1408288940456411187"
name = "Saber x Stelle"
archived = true
locked = false
createdAt = "2025-08-22T03:17:28.148Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1408288940456411187"
author = "korieuko"
content = "https://rule34video.com/video/3991433/saber-x-stelle/"
createdAt = "2025-08-22T03:17:28.148Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3991000/3991433/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3991433/saber-x-stelle/"
title = "Saber x Stelle"
image = "https://rule34video.com/contents/videos_screenshots/3991000/3991433/preview.jpg"
site = "rule34video.com"
desc = "Thank you so much for checking out my content ✨ Your support makes my work possible!\n\n✨ If you want all my animations in 4K-1080p, videos everyday, polls and more: https://www.patreon.com/c/torakage\n\nhttps://x.com/Torakage268000"
