id = "1314856471325970482"
name = "Blue Archive[NSFW]"
guildId = "1314839006717935696"
guildName = "Invrs ✦ NSFW"
backedUpAt = "2026-03-08T12:46:37.913Z"
contents = ["forum: forum-rio-futaba", "forum: forum-kisaki", "forum: forum-ako-amau", "forum: forum-hina", "forum: forum-asuna", "forum: forum-tsubaki"]

[stats]
totalForums = 6
totalChannels = 0
totalThreads = 9
totalMessages = 9
