id = "1377545581433720853"
name = "Zani x Ciaccona Futa video (WuWa) 赞妮 x 夏空 [Requested]"
archived = true
locked = false
createdAt = "2025-05-29T07:14:20.173Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377545581433720853"
author = "korieuko"
content = "https://rule34video.com/video/3852381/zani-x-ciaccona-futa-video-wuwa-x-requested/"
createdAt = "2025-05-29T07:14:20.173Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3852000/3852381/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3852381/zani-x-ciaccona-futa-video-wuwa-x-requested/"
title = "Zani x Ciaccona Futa video (WuWa) 赞妮 x 夏空 [Requested]"
image = "https://rule34video.com/contents/videos_screenshots/3852000/3852381/preview.jpg"
site = "rule34video.com"
desc = "Full version (12:38) here:\n\nhttps://www.fanbox.cc/@acidrain002/posts/9934975"
