id = "1417112613057204305"
name = "Zani_Wuthering Waves [TY98]"
archived = true
locked = false
createdAt = "2025-09-15T11:39:35.632Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1417112613057204305"
author = "korieuko"
content = "https://rule34video.com/video/4029853/zani-wuthering-waves-ty98/"
createdAt = "2025-09-15T11:39:35.632Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4029000/4029853/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4029853/zani-wuthering-waves-ty98/"
title = "Zani_Wuthering Waves [TY98]"
image = "https://rule34video.com/contents/videos_screenshots/4029000/4029853/preview.jpg"
site = "rule34video.com"
desc = "Zani_Wuthering Waves [TY98]\n\n:||"
