id = "1398549937310011392"
name = "Zani get fuck"
archived = true
locked = false
createdAt = "2025-07-26T06:18:08.856Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1398549937310011392"
author = "korieuko"
content = "https://rule34video.com/video/3950317/zani-get-fuck/"
createdAt = "2025-07-26T06:18:08.856Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3950000/3950317/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3950317/zani-get-fuck/"
title = "Zani get fuck"
image = "https://rule34video.com/contents/videos_screenshots/3950000/3950317/preview.jpg"
site = "rule34video.com"
desc = ""
