id = "1424052420274552954"
name = "Zani [Tir_Al]"
archived = true
locked = false
createdAt = "2025-10-04T15:15:54.608Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1424052420274552954"
author = "korieuko"
content = "https://rule34video.com/video/4058706/zani-tir-al3/"
createdAt = "2025-10-04T15:15:54.608Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4058000/4058706/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4058706/zani-tir-al3/"
title = "Zani [Tir_Al]"
image = "https://rule34video.com/contents/videos_screenshots/4058000/4058706/preview.jpg"
site = "rule34video.com"
desc = "Zani [Tir_Al]"
