id = "1375456130750218372"
name = "Zani [SeventyFive3D]"
archived = true
locked = false
createdAt = "2025-05-23T12:51:36.310Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1375456130750218372"
author = "korieuko"
content = "https://rule34video.com/video/3844821/zani-seventyfive3d/"
createdAt = "2025-05-23T12:51:36.310Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3844000/3844821/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3844821/zani-seventyfive3d/"
title = "Zani [SeventyFive3D]"
image = "https://rule34video.com/contents/videos_screenshots/3844000/3844821/preview.jpg"
site = "rule34video.com"
desc = ""
