id = "1374239746561146970"
name = "Zani working on top"
archived = true
locked = false
createdAt = "2025-05-20T04:18:07.720Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1374239746561146970"
author = "korieuko"
content = "https://rule34video.com/video/3844081/zani-working-on-top/"
createdAt = "2025-05-20T04:18:07.720Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3844000/3844081/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3844081/zani-working-on-top/"
title = "Zani working on top"
image = "https://rule34video.com/contents/videos_screenshots/3844000/3844081/preview.jpg"
site = "rule34video.com"
desc = ""
