id = "1377546753255014450"
name = "Zani [Sound] Va: @LecheryAmoreVA"
archived = true
locked = false
createdAt = "2025-05-29T07:18:59.557Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1377546753255014450"
author = "korieuko"
content = "https://rule34video.com/video/3857245/zani-sound-va-lecheryamoreva/"
createdAt = "2025-05-29T07:18:59.557Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
