id = "1371869721607143525"
name = "Zani Tir_Al"
archived = true
locked = false
createdAt = "2025-05-13T15:20:29.738Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1371869721607143525"
author = "korieuko"
content = "https://rule34video.com/video/3828293/zani-tir-al/"
createdAt = "2025-05-13T15:20:29.738Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3828000/3828293/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3828293/zani-tir-al/"
title = "Zani Tir_Al"
image = "https://rule34video.com/contents/videos_screenshots/3828000/3828293/preview.jpg"
site = "rule34video.com"
desc = "Video: https://x.com/Tir_al_\nVA https://x.com/PleasedByViolet\n\nSupport: patreon.com/tir_al"
