id = "1457733215216206029"
name = "Zani seggs"
archived = true
locked = false
createdAt = "2026-01-05T13:51:21.881Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1457733215216206029"
author = "korieuko"
content = "https://rule34video.com/video/4182116/zani-seggs/"
createdAt = "2026-01-05T13:51:21.881Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4182000/4182116/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4182116/zani-seggs/"
title = "Zani seggs"
image = "https://rule34video.com/contents/videos_screenshots/4182000/4182116/preview.jpg"
site = "rule34video.com"
desc = "Artist: Kizumashiro (KIZU"
