id = "1474738803020402951"
name = "Yvonne Upside down"
archived = false
locked = false
createdAt = "2026-02-21T12:05:29.962Z"
autoArchiveDuration = 4320
messageCount = 1
appliedTags = []

[[messages]]
id = "1474738803020402951"
author = "korieuko"
content = "https://rule34video.com/video/4252970/yvonne-upside-down/"
createdAt = "2026-02-21T12:05:29.962Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4252000/4252970/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4252970/yvonne-upside-down/"
title = "Yvonne Upside down"
image = "https://rule34video.com/contents/videos_screenshots/4252000/4252970/preview.jpg"
site = "rule34video.com"
desc = "Animation: x.com/PoisonAhe\npatreon.com/cw/KoikatsuLoop\npoison0215.fanbox.cc/\n\nVA & SFX: x.com/SquishSuccubus"
