id = "1447932537954631760"
name = "[AidenHet] Astra - A gift for you"
archived = true
locked = false
createdAt = "2025-12-09T12:46:58.334Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447932537954631760"
author = "korieuko"
content = "https://rule34video.com/video/3753429/aidenhet-astra-a-gift-for-you/"
createdAt = "2025-12-09T12:46:58.334Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3753000/3753429/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3753429/aidenhet-astra-a-gift-for-you/"
title = "[AidenHet] Astra - A gift for you"
image = "https://rule34video.com/contents/videos_screenshots/3753000/3753429/preview.jpg"
site = "rule34video.com"
desc = ""
