id = "1447932027407175722"
name = "【Kasayami】2025.06 Astra Yaobngm"
archived = true
locked = false
createdAt = "2025-12-09T12:44:56.610Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447932027407175722"
author = "korieuko"
content = "https://rule34video.com/video/4008025/kasayami-2025-06-astra-yaobngm/"
createdAt = "2025-12-09T12:44:56.610Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4008000/4008025/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4008025/kasayami-2025-06-astra-yaobngm/"
title = "【Kasayami】2025.06 Astra Yaobngm"
image = "https://rule34video.com/contents/videos_screenshots/4008000/4008025/preview.jpg"
site = "rule34video.com"
desc = "Astra Yaobngm.mp4"
