id = "1447932905295970385"
name = "Astra Yao riding"
archived = true
locked = false
createdAt = "2025-12-09T12:48:25.915Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447932905295970385"
author = "korieuko"
content = "https://rule34video.com/video/3727037/astra-yao-riding/"
createdAt = "2025-12-09T12:48:25.915Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3727000/3727037/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3727037/astra-yao-riding/"
title = "Astra Yao riding"
image = "https://rule34video.com/contents/videos_screenshots/3727000/3727037/preview.jpg"
site = "rule34video.com"
desc = "Astra Yao is riding on one of her fans for a sweet present. This is no sound version. Sound version available on the Patreon link below.\n\nArtist: Lazyrice3d\n\nPatreon: https://www.patreon.com/Lazyrice3D\nTwitter-X: https://x.com/lazyrice3d\nPixiv: https://www.pixiv.net/users/109285416\nIwara: iwara.tv/profile/lazyrice"
