id = "1447933099756486726"
name = "Astra Yao x Wise [Akt]"
archived = true
locked = false
createdAt = "2025-12-09T12:49:12.278Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447933099756486726"
author = "korieuko"
content = "https://rule34video.com/video/3691213/astra-yao-x-wise-akt/"
createdAt = "2025-12-09T12:49:12.278Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3691000/3691213/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3691213/astra-yao-x-wise-akt/"
title = "Astra Yao x Wise [Akt]"
image = "https://rule34video.com/contents/videos_screenshots/3691000/3691213/preview.jpg"
site = "rule34video.com"
desc = "Artist:\nhttps://akt.fanbox.cc\nhttps://www.patreon.com/c/akt_shop\nhttps://ganknow.com/animationakt"
