id = "1447933006281965598"
name = "Astra animation 4k 60fps"
archived = true
locked = false
createdAt = "2025-12-09T12:48:49.992Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447933006281965598"
author = "korieuko"
content = "https://rule34video.com/video/3718645/astra-animation-4k-60fps/"
createdAt = "2025-12-09T12:48:49.992Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3718000/3718645/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3718645/astra-animation-4k-60fps/"
title = "Astra animation 4k 60fps"
image = "https://rule34video.com/contents/videos_screenshots/3718000/3718645/preview.jpg"
site = "rule34video.com"
desc = "sweet_gpt:\nI wonder why Astra popped out from \nbehind the couch in her PV. So, I simulated that situation.\n\nI'm not betraying the Koikatsu community, I just want to try using Blender."
