id = "1447931504901623819"
name = "Astra Yao BBC"
archived = true
locked = false
createdAt = "2025-12-09T12:42:52.035Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447931504901623819"
author = "korieuko"
content = "https://rule34video.com/video/4141687/astra-yao-bbc/"
createdAt = "2025-12-09T12:42:52.035Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/4141000/4141687/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/4141687/astra-yao-bbc/"
title = "Astra Yao BBC"
image = "https://rule34video.com/contents/videos_screenshots/4141000/4141687/preview.jpg"
site = "rule34video.com"
desc = "Astra Yao BBC"
