id = "1447932315346014239"
name = "Astra Yao (Sound) VA: [MarziccVA]"
archived = true
locked = false
createdAt = "2025-12-09T12:46:05.260Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447932315346014239"
author = "korieuko"
content = "https://rule34video.com/video/3829921/astra-yao-sound-va-marziccva/"
createdAt = "2025-12-09T12:46:05.260Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3829000/3829921/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3829921/astra-yao-sound-va-marziccva/"
title = "Astra Yao (Sound) VA: [MarziccVA]"
image = "https://rule34video.com/contents/videos_screenshots/3829000/3829921/preview.jpg"
site = "rule34video.com"
desc = "Animation: https://x.com/TwiistedLewds\nAstra VA: https://x.com/MarziccVA\nSFX: https://x.com/ReNanoByte\nModels - @WaffleNSFW & @DaB_neko\n\n\nPls add a new tag for the VA"
