id = "1447932670784045056"
name = "Date night with Astra Yao"
archived = true
locked = false
createdAt = "2025-12-09T12:47:30.003Z"
autoArchiveDuration = 1440
messageCount = 1
appliedTags = []

[[messages]]
id = "1447932670784045056"
author = "korieuko"
content = "https://rule34video.com/video/3755197/date-night-with-astra-yao/"
createdAt = "2025-12-09T12:47:30.003Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3755000/3755197/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3755197/date-night-with-astra-yao/"
title = "Date night with Astra Yao"
image = "https://rule34video.com/contents/videos_screenshots/3755000/3755197/preview.jpg"
site = "rule34video.com"
desc = "If you'd like to see more, support me on Twitter/X! https://x.com/HeliosPrimes\n︀︀\n︀︀Wise Model\\: [@DaB_neko](https://x.com/DaB_neko)\n︀︀Astra Model\\: [@WaffleNSFW](https://x.com/WaffleNSFW) / [@DaB_neko](https://x.com/DaB_neko)\n︀︀Map\\: [@LamboXiao](https://x.com/LamboXiao)\n︀︀Shaders\\: [@SarlSys](https://x.com/SarlSys)\n︀︀VA..."
