id = "1447933177061441596"
name = "Your new look is too seductive [HD][Full Cloth][No Sound]"
archived = true
locked = false
createdAt = "2025-12-09T12:49:30.709Z"
autoArchiveDuration = 1440
messageCount = 3
appliedTags = []

[[messages]]
id = "1447933177061441596"
author = "korieuko"
content = "https://rule34video.com/video/3688425/your-new-look-is-too-seductive-hd-full-cloth-no-sound/"
createdAt = "2025-12-09T12:49:30.709Z"
pinned = false
attachments = ""
thumbnail = "https://rule34video.com/contents/videos_screenshots/3688000/3688425/preview.jpg"

[[messages.linkPreviews]]
url = "https://rule34video.com/video/3688425/your-new-look-is-too-seductive-hd-full-cloth-no-sound/"
title = "Your new look is too seductive [HD][Full Cloth][No Sound]"
image = "https://rule34video.com/contents/videos_screenshots/3688000/3688425/preview.jpg"
site = "rule34video.com"
desc = "Public Commission by : @LamboXiao\n\nModel : @WaffleNSFW\n\nScene : @LamboXiao\n\nAnimation : @Brilleas\n\nFollow me on :\nX : https://x.com/Brilleas\nPatreon : https://www.patreon.com/c/GoodGuyInTheBottle\nPixiv : https://www.pixiv.net/en/users/17274477\nIwara : https://www.iwara.tv/profile/brilleas\nTikTok : https://www.tiktok.com/@salieri121"

[[messages]]
id = "1447933268249804910"
author = "korieuko"
content = "Your new look is too seductive [HD][Full Cloth][No Sound]"
createdAt = "2025-12-09T12:49:52.450Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []

[[messages]]
id = "1453312332649205801"
author = "korieuko"
content = "sleeping peak"
createdAt = "2025-12-24T09:04:21.341Z"
pinned = false
attachments = ""
thumbnail = ""
linkPreviews = []
